rdl/test/Makefile

swapped the order of the static and dynamic libraries in the compile
line.  This now compiles on both my local ubuntu installation and
hype.

fixed compilation error on Ubuntu 14.04.1

---

t/Makefile
t/t0001-basic.t

After some API changes to flux-core I wanted to make sure flux-sched still built and ran OK. 
I ran into a couple minor issues with the test suite which are fixed below.
After these changes, I'm able to successfully build and run `make check' with the current flux-core master.

minor test suite fixes

---

simulator/sim_execsrv.c
simulator/sim_schedsrv.c
simulator/simsrv.c
simulator/simulator.c
simulator/submitsrv.c

This update follows PR flux-framework/flux-core#182.
All changes affected only the simulator.

stop using deprecated flux-core functions

---

Makefile
sched/schedsrv.c
simulator/Makefile
simulator/sim_execsrv.c
simulator/sim_schedsrv.c
simulator/submitsrv.c
t/Makefile

This PR contains fixes for a couple warnings when building with `clang` in travis-ci (which are hard errors due to -Werror), and also rectifies an issue with commit 826a3b48f6906336ea392228a0efeedbcc2dcb48 wherein `check` was accidentally made the default target of `make` instead of `all`.

clang and build fixes

---

rdl/RDL.lua
rdl/RDL/Resource.lua
t/Makefile
t/lua/t0001-rdl-basic.t
t/lua/t0002-multilevel.t
t/lua/t0003-default-tags.t
t/lua/t0004-derived-type.t

This PR adds some nominal RDL tests (for the Lua code) under `t/lua/*.t`, as well as some minor enhancements to RDL, including:
* Set default tags on resource types, inherited by all base types. See `t/lua/t0003-default-tags.t` for examples.
* A reference to loaded type is returned with `uses` function, so `local N = uses "Node"` now works.
* Resource class is loaded as if by `uses` command, so the class is reinitialized with each new RDL file or string parsed.

rdl testing and small enhancements

---

rdl/rdl.h
sched/schedsrv.c
simulator/sim_schedsrv.c

Avoid including `<json/json.h>` as on some systems it is `<json-c/json.h>`.
Simply include`<json.h>` as CFLAGS from flux-core's Makefile.inc
will set -I appropriately.

simple tweak to get flux-sched building with debian/ubuntu json-c packaging

---

sched/schedsrv.c
simulator/sim_schedsrv.c
simulator/simsrv.c

Tracks the latest mods to flux-core

sched: replace use of flux_event_send() with flux_sendmsg()

---

sched/schedsrv.c
simulator/sim_execsrv.c
simulator/simsrv.c

FluxFreeFn is being renamed to flux_free_f upstream.
Change the function signature to avoid the cast, and thus the
reference to this name, in the three places in flux-sched
where this was done.

avoid cast to FluxFreeFn

---

resrc/resrc.c
resrc/test/tresrc.c

Use a resource's size field to determine whether the resource is a
pool.  This is a transitional commit that provides a practical replacement for a hard-coded placeholder.  I'll be looking into streamlining this area even further.

resrc: eliminate the hard-coded memory pool

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_tree.c
resrc/test/tresrc.c

Eliminate the dedicated pool structure and enhance the resrc structure
to support a size component.  This makes the resrc model conform with
the design described in RFC 4.  Update the tresrc test to match the
new model.  No changes were needed to the sched module.

resrc: redesign pool support

---

.travis.yml
resrc/test/Makefile
t/sharness.d/flux-sharness.sh

As in flux-framework/flux-core#265, update `.travis.yml` to use the new container builds for much faster build times (and fix some minor items along the way).
For flux-sched, we also cache the flux-core git directory to speed things up.

update travis-ci to new container build infrastructure

---

sched/schedsrv.c
simulator/sim_execsrv.c
simulator/sim_schedsrv.c
simulator/simsrv.c
simulator/submitsrv.c

This change goes along with flux-framework/flux-core#289 where the prototype of `mod_main()` changed to use argc, argv style argument passing rather than a zhash_t.
I repeated that silly `zhash_fromargv()` several times thinking that people would probably want to revise the way arguments are handled in those modules one at a time;  feel free to move that somewhere shared if you want to keep it.

modules: update mod_main() prototype per RFC 5

---

.travis.yml
resrc/Makefile
simulator/submitsrv.c

The travis-ci build had a few issues which should be addressed here:
* We weren't getting the latest flux-core/master because the git repo was being updated via `git-pull`, which was failing due to changes in the working tree. We now use a hard reset to ensure we're building against latest flux-core
* Latest flux-core now has python dependencies and these are now installed
* Latest flux-core removes the libuuid dependency which broke linking in `resrc`. Since resrc directly requires libuuid it should specify that on link line
* We need to support two styles of comparator functions for zlist in simulator, depending on czmq version. (Hopefully I got the compare function correct enough, it only has build testing)

travis updates and build fixes

---

.travis.yml
Makefile.inc

flux-core started tagging deprecated functions with the 'deprecated'
attribute, which results in a compiler warning when those functions
are used.
Add CFLAGS to make that particular warning non-fatal.

build: make deprecated function warnings non-fatal

---

sched/schedsrv.c
simulator/sim_execsrv.c
simulator/sim_schedsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c

kvsitr_t  is now a struct not a pointer to struct.
kvs callback typedefs changed names.  Eliminate places in simulator
where this was being cast, as doing so is a bit dangerous - changes
in prototype would be hidden.  Case in point, these functions are
expected to return an integer result and were declared with return
type void.
Use the (deprecated) jsc _obj interfaces

update flux-core API usage after changes

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_reqst.c
resrc/resrc_reqst.h
resrc/resrc_tree.c
resrc/resrc_tree.h
resrc/test/tresrc.c
sched/schedplugin1.c
sched/schedsrv.c
sched/schedsrv.h

Essentially undoes the 6bdf47c2cf36b3d5826dbf70dceabc3b3167b7ae commit
and changes the resrc and sched code to comply with the decision in
RFC7 that abstract types SHOULD NOT be defined as pointers to
incomplete types.

resrc: conform to RFC 7

---

sched/Makefile
sched/flux-submit
sched/flux-waitjob.c
sched/schedsrv.c
t/Makefile
t/sharness.d/flux-sharness.sh
t/t0001-basic.t
t/t1000-jsc.t
t/t2000-fcfs.t

Note that this PR should not be merged before PR #386 of flux-core is merged. This PR contains initial support for reliable jsc including a sharness test case. 
To facilitate testing, a new utility called `flux-waitjob` is added so that a shareness test can wait until all of the jobs are complete, which are submitted through `flux-submit`. 
In addition, to get notified of the “submitted” event, flux-submit now emits wreck.state.submitted as well. 
Finally, this PR also contains other minor fixes and a workaround (i.g., removing the use of posix.signal from within flux-submit).

support for reliable jsc

---

sched/flux-submit

Acts on suggestion:  https://github.com/flux-framework/flux-sched/commit/89df88f7a69568ec6b583515c50050f64c2eb6da#commitcomment-13078867

sched: simplify two lines of flux-submit

---

resrc/Makefile
resrc/resrc.c

Eliminates the use of hostlist and allows the build to succeed.  Will have no adverse affects in operation, but I will work on a replacement solution next week.

resrc: Shortterm fix to fix the build

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_reqst.c
resrc/resrc_tree.c
resrc/resrc_tree.h
resrc/test/tresrc.c
sched/schedsrv.c
sched/schedsrv.h

More than a PR, this is ping to get a feedback from everyone on the extending the resrc with time component (mainly for @lipari to see if the resrc extension is close to what he envisioned and @SteVwonder to check if this does seem to suit his needs). If its good, I will continue working on it after feedback and bring it to a mergable state. Otherwise, we can close the PR and I can rework differently.
Here is a summary of the changes and logic:
1. resrc is extended with another hash table "twindow". When allocated/reserved for future with jobs, this will store job_id as key and a json string as value - { "starttime" :  epoch_start_time, "endtime" : epoch_end_time }. Note that this is valid only for nodes and cores at this point. 
2. When root loads the RDL from configuration, all the …

Time component to resrc

---

sched/flux-submit

Upcoming PR in flux-core will move flux-lua interfaces around a bit (rename to "flux"). In order to avoid breaking `flux-submit` remove the unnecessary use of `flux-lua.posix` and `flux-lua.timer`.

sched/flux-submit: remove references to flux-lua

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_reqst.c
resrc/resrc_tree.c
resrc/test/tresrc.c
sched/flux-waitjob.c
sched/schedplugin1.c
sched/schedsrv.c
t/Makefile

The original design included a hash table of all the resources.  The thinking was that this table would provide an alternate means to search and update resources that could perform better than a tree search.  This facility has gone unused and now serves no purpose other than to unnecessarily complicate the code

Eliminate flat resources

---

sched/schedsrv.c
simulator/scheduler.c
simulator/scheduler.h
simulator/sim_execsrv.c
simulator/sim_sched_easy.c
simulator/sim_sched_easy_aware.c
simulator/sim_sched_fcfs.c
simulator/sim_sched_fcfs_aware.c
simulator/simsrv.c
simulator/submitsrv.c

Use the new message handler interfaces that changed in flux-core.
Fixes #72 
Once PR flux-framework/flux-core#418 is merged, flux-sched should be back on its feet again.

update message handler API usage

---

resrc/resrc.c
resrc/resrc.h

Change the name to only include the name without the id appended.  Add
id, path, and uuid to the list of serialized (and deserialized)
resource members.
Addresses https://github.com/flux-framework/flux-sched/issues/74

resrc: modify the serialized resources

---

.travis.yml
rdl/RDL.lua
rdl/RDL/lib/ListOf.lua
rdl/RDL/memstore.lua
rdl/test/test-rdl.lua
resrc/test/Makefile
sched/flux-waitjob.c
simulator/test/Makefile
t/Makefile
t/sharness.d/flux-sharness.sh
t/t0002-waitjob.t
t/t1000-jsc.t

This PR contains fixes for two distinct issues: 1) intermittent jsc test failures and 2) Travis CI build failures because `hostlist` and `posix` have moved to the flux namespace (e.g., `src/bindings/lua/flux/hostlist.so`). 
1) is captured in PR #64 along with other issues. I suspect the issue is due to some less precise synchronization mechanisms used between `flux-waitjob` and subsequent `flux-submit`s within the test script (`t/t1000-jsc.t`). To make synchronization air-tight, better synchronization support has been added within `flux-waitjob` (along with its own test case --- `t/t0002-waitjob.t`) and `t/t1000-jsc.t` has also been improved.  
2) is captured in #76. To debug this better in the future, I've made a very minor modification to  `.travis.yml` such that I can see the …

jsc/etc: beefing up the jsc tests and adjusting for a recent lua binding churn

---

rdl/flux-rdltool.c

optparse_t was redefined as a struct rather than a pointer to one
per RFC 7.  The single use in flux-sched also needs to be updated.

flux-rdltool: update optparse_t usage

---

t/Makefile

I got a little lost trying to figure out what sharness test belonged to what output, especially the ones that repeat the same tests for different scheduler algs.  This prints PASS or FAIL: and the name of the test after each test is run similar to the automake test driver.

test: print PASS/FAIL after each sharness test

---

sched/schedsrv.c

Addresses the concern that, with the addition of the new simulator options, users could stipulate incompatible sched module load options.  Also, includes the replacement of a deprecated function call.

Consistent options

---

sched/flux-waitjob.c
sched/schedsrv.c
t/t1000-jsc.t

- Add a very simple patch to the jsc sharness test to cover the new hwloc reader mode
- Add a LOG_INFO to make it easy to verify hwloc is used

jsc: extend the test to cover hwloc reader mode

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_reqst.c
resrc/resrc_reqst.h
resrc/resrc_tree.c
resrc/resrc_tree.h
resrc/test/tresrc.c
sched/Makefile
sched/backfillplugin1.c
sched/schedsrv.c
sched/schedsrv.h
t/t2002-easy.t

A new backfillplugin1 was added as an alternative to the original FCFS
schedplugin1 plugin.  The EASY_BACKFILL definition in this plugin
controls whether the backfill is EASY or conservative.  It's currently
defined to be EASY so as to function as an exact replacement.
3 new API's were added to the sched framework: sched_loop_setup(),
allocate_resources(), and reserve_resources().
Includes many changes across sched as well as resrc.  resrc now
includes support for time-based as well as now-based resource
matching, allocations and reservations.  The backfill scheduler uses
the time-based functionality while the schedplugin1 FCFS uses the
now-based versions.
The stage_tree_list() was removed and instead staging was moved to the
selection function.  As size elements of a resource are …

sched:  extract the backfill scheduling code from the sched framework

---

resrc/resrc.c

The allocation and reservation logic uses the resource state to decide
whether to do time or now-based allocations/reservations.  This commit
fixes some places where the state was being improperly set.

resrc: Fix bug in resource state assignment

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_reqst.c
resrc/resrc_reqst.h
sched/backfillplugin1.c
sched/schedplugin1.c

The old argument to resrc_match_resource() matched a specified
resource against a sample resource.  The sample resource was the
resource part of a resource request object.  This proved to be
combersome as we proceed with the next round of changes.  So, now we
pass the whole request to resrc_match_resource().
This complies with a request made in https://github.com/flux-framework/flux-sched/pull/103#issuecomment-164945235 to break [PR 103](https://github.com/flux-framework/flux-sched/pull/103) into two pieces.

resrc: Change resrc_match_resource() to match a request

---

sched/flux-waitjob.c
t/scripts/waitfile.lua
t/sharness.d/sched-sharness.sh
t/t0002-waitjob.t
t/t1000-jsc.t

This PR has two items:
1) Remove the redundant heartbeat-based synchronization logic from flux-waitjob.c. This was discussed in `flux-core` issue [#505](https://github.com/flux-framework/flux-core/issues/505) and [#498](https://github.com/flux-framework/flux-core/issues/498) 
2) Clean up waitjob and jsc tests:
- Specifically refactor test session management and synchronization management into the subroutines in the project-local sharness script (t/sharness.d/sched-sharness.sh);
- Copy @grondo's waitfile.lua into t/scripts/ as part of it;
- waitjob and jsc test scripts now use the new support;
- Finally, the local sharness test script also contains submit-and-verification subroutines that will ease writing some of my future test scripts.

test: clean up waitjob and jsc tests

---

resrc/resrc.c
sched/backfillplugin1.c
sched/schedplugin1.c
sched/schedsrv.c
sched/schedsrv.h

Fix some minor bugs in requesting a resource size greater than one.  Also, use a new flux_res_t member to replace hard coded behavior.

Exclusive mods

---

resrc/resrc.c
resrc/resrc.h

Add resrc_to_string so that a resrc's state can be printed to a string which then can be directed to `flux_log ()`. For now, the debug print function (`resrc_print_resource ()`) prints the state stdout, which gets lost when used in a comms module (e.g., `schedsrv`). `resrc_print_resource ()` is now a thin wrapper on top of `resrc_to_string ()`.

resrc: add to_string to print a resrc's state to a string

---

Makefile.inc
README.md
simulator/Makefile
t/sharness.d/flux-sharness.sh

flux(1) utility command line options --module-path (-M), --lua-path (-L),
--lua-cpath (-C), and --python-path (-P) will be removed from upstream
flux-core. This commit removes use of those options from flux-sched
build and test infrastructure, in preference for environment variables
that perform a a similar function.
This change should be applied immediately after flux-framework/flux-core#516
is merged. It cannot be applied beforehand because `flux(1)` does not currently
support extending `FLUX_MODULE_PATH` from the environment.
If we'd rather not temporarily break flux-sched, we could break this into parts
1. flux-core: Add `FLUX_MODULE_PATH` environment support to `flux(1)`
2. flux-sched: Merge this PR
3. flux-core: Remove -M, -P, -L, -C

build/test: Update flux commandline options

---

t/sharness.d/sched-sharness.sh
t/t1002-rs2rank-64ranks.t
t/t1003-stress.t

I was getting OOMs and EAGAIN errors from `fork` on a small VM when trying to run `make check` in flux-sched, due to the 64 rank flux session being started in `t1002-rs2rank-64ranks.t`, even when LONGTEST is not set. 
It seemed the intent here (and in `t1003-stress.t`) was to skip all tests if `--long` or `TEST_LONG` is not set, so, in addition to setting `LONGTEST` prereq in one place, this PR puts the stanza:
```sh
if ! test_have_prereq LONGTEST; then
skip_all='LONGTEST not set, skipping...'
test_done
fi
```
At the top of these functions, which results in skipping these entire files, thus avoiding unnecessary launch of a flux session.

Improved LONGTEST usage in testsuite

---

.travis.yml
README.md
rdl/Makefile.am
rdl/RDL/types/Socket.lua
rdl/test/Makefile.am
resrc/test/Makefile.am
sched/Makefile.am
simulator/Makefile.am
t/Makefile.am
t/sharness.d/sched-sharness.sh

This PR adds support for an "install" target for travis-ci testing. This target builds flux-sched with `--prefix=$HOME/local2` (same prefix as flux-core), does `make install`, and then runs `make check` against the *installed* flux-sched components via a newly supported `FLUX_SCHED_TEST_INSTALLED` env var.

travis-ci: add install target for testing

---

t/t0001-basic.t

Now that flux-core can return mod_main() errors to flux module load,
re-enable t0001-basic.t test 4.
Discussed in issue #13

test/basic: re-enable commented out test

---

t/t1001-rs2rank-basic.t

Reverts commit 39d2b26 which bypassed the tests due to an intermittent
timing-related failure when run by travis.  The merge of flux-core
PR 586 eliminates the timing problem.

t1001-rs2rank-basic.t: restore all tests

---

t/Makefile.am

Fix use of non-POSIX $(if ...) usage in t/Makefile.am to keep automake
from complaining. The replacement uses POSIX variable substitution to
substitute the build-tree LUA_PATH and LUA_CPATH to the PREPEND variables
iff FLUX_SCHED_TEST_INSTALLED *is not* set.
When FLUX_SCHED_TEST_INSTALLED *is* set, then the value of that variable
(`t` or maybe `1`) is substituted, which still isn't quite right, but at least
the build-tree Lua modules will not be used. Unfortunately, this was the
best that we could do at this time.
If this isn't acceptable, then we can take some other approach like discussed in #136,
or we could add the `-Wno-portability` flag to automake, since we probably don't support
non-GNU systems anyway. (However, it might be useful to keep portability warnings for
the rest of the …

testsuite: fix non-POSIX warning from automake

---

sched/Makefile.am
sched/plugin.c
sched/plugin.h
sched/sched.c

Factor out plugin loading functions to plugin.[ch], creating a semi-abstract plugin loader.
Retain the default fcfs plugin loading behavior, with sched module command line override.
Add insmod, rmmod, lsmod handlers that operate within the plugin loader.  Now this works:
```
$ flux module load sched
$ flux module list sched
Module               Size    Digest  Idle  S  Nodeset
sched.fcfs             43228 CD51E2B    0  R  0
$ flux module remove sched.fcfs
$ flux module list sched
Module               Size    Digest  Idle  S  Nodeset
$ flux module load sched.backfill
$ flux module list sched
Module               Size    Digest  Idle  S  Nodeset
sched.backfill         47843 D775294    0  R  0
```
This addresses the first part of #144.
Assertions were placed at locations in sched where the …

sched: add dynamic plugin loading

---

Makefile.am
configure.ac
etc/Makefile.am
etc/sched-start
etc/sched-stop
t/Makefile.am
t/sharness.d/flux-sharness.sh
t/sharness.d/sched-sharness.sh
t/t0003-basic-install.t

If sched is not installed into flux-core's $prefix,
one should set FLUX_RC_EXTRA environment variable to flux-sched's $prefix/etc/flux
so that flux start can automatically locate and execute sched's runlevel 1 and 3.
In addition, users can set FLUX_SCHED_OPTIONS if they want flux
to load in the sched module with non-default options.
(e.g., FLUX_SCHED_OPTIONS="plugin=sched.backfill" will cause
the flux session to load the sched module with the backfil scheduling plugin.
For LLNL's /opt rpm package, I plan to add FLUX_RC_EXTRA to its module script.
Also, module load flux-sched-xxx.rpm will print out available load options
of sched to console to help users to choose options to play with.

runlevel: Add runlevel support

---

conf/cab.lua
conf/hype-io.lua
conf/hype.lua
rdl/RDL/ResourceData.lua
rdl/RDL/memstore.lua
rdl/RDL/types/Node.lua
rdl/rdl.c
rdl/rdl.h
rdl/test/test-rdl.lua
rdl/test/trdl.c
resrc/resrc.c
resrc/resrc.h
resrc/test/tresrc.c
t/data/hwloc-data/004N/exclusive/cab.hwloc1.lua
t/data/hwloc-data/004N/exclusive/cab.hwloc2.lua
t/data/hwloc-data/004N/exclusive/cab.hwloc3.lua
t/lua/t0001-rdl-basic.t
t/lua/t0002-multilevel.t
t/lua/t0003-default-tags.t
t/lua/t0004-derived-type.t

Tracks the changes made in [PR 41](https://github.com/flux-framework/rfc/pull/41) to [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc) as a result of the discussion in [Issue 157](https://github.com/flux-framework/flux-sched/issues/157).  Modifies the rdl and resrc code to add separate members for name and basename.  Provides the groundwork for the resolution of [Issue 155](https://github.com/flux-framework/flux-sched/pull/155).  The result is better consistency between the rdl and resrc code with regard to resource naming conventions.

Resource name disambiguity

---

sched/rsreader.c
sched/rsreader.h
sched/sched.c
t/sharness.d/sched-sharness.sh
t/t0001-basic.t
t/t0002-waitjob.t
t/t1000-jsc.t
t/t1001-rs2rank-basic.t

Fix Issue #153. 
- Remove rdl-config=RDL-file option from the tests that are not designed to test a RDL-hwloc inconsistency
- Improve the verbosity for RDL != hwloc condition
- Add fail-on-error option to the sched module for better testing

Issue153: Better resource unmatch test and etc

---

.gitignore

My 'git status' is becoming rather unruly with all of the untracked files (mainly from autotools).  Any objections to pulling flux-core's .gitignore into flux-sched?

Copy gitignore over from flux-core

---

sched/sched.c
simulator/simulator.c

Minor fixes to some free'ing that causes a segfault when running under the simulator.
The problem only occurs when the simulator is being shutdown.

sim & sched: fix segfaults when running in sim

---

sched/plugin.c
sched/plugin.h
sched/plugin_version.map
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
t/t1004-module-load.t
t/t2002-easy.t

Addresses issue #159 
To pass options through to the plugin when launching sched, use plugin-opts.  This list is comma separated. (e.g. `flux module load sched plugin=sched.backfill plugin-opts=reserve-depth=1,foo=bar`)
To pass options through to the plugin when loading just the plugin, specify them as a space separated list. (e.g. `flux module load sched.backfill reserve-depth=1 foo=bar`)
Examples of launching with various backfilling algorithms:
- Conservative
- `flux module load sched.backfill reserve-depth=-1`
- EASY
- `flux module load sched.backfill reserve-depth=1`
- Hybrid
- `flux module load sched.backfill reserve-depth=4`
- Pure
- `flux module load sched.backfill reserve-depth=0`

Add runtime option to select backfill algorithm

---

resrc/resrc.c
resrc/resrc_reqst.c
resrc/resrc_reqst.h
resrc/resrc_tree.c
resrc/resrc_tree.h
resrc/test/tresrc.c
sched/plugin.h
sched/rsreader.c
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
sched/scheduler.h

Replace tree list searches with tree searches
Modifies the resrc search code to search a resource tree instead of a resource tree list.  This has two benefits:
* Can now search for an isolated resource (like cores) without regard to its parent resource (like nodes).  Formally, we had to define a request that include one node and multiple cores to find resource composites of node+cores.  Now we can just search for cores.
* The code now conforms to the RFC 4 requirement:
"The job ID for a job that is allocated a resource in a composite hierarchy MUST be annotated not only to the resource, but to each parent up the tree of those resources allocated to the enclosing
instance"
Also in this PR are minor mods that prepared the way for the tree search changes.

Versatile Scheduling

---

.travis.yml
NEWS
NEWS.md
codecov.yml
simulator/sim_execsrv.c
simulator/simsrv.c

This PR updates flux-sched travis-ci with new dependencies from flux-core, adds gcc-4.9 and clang-3.8, as well as a new `cppcheck` target for testing (along with a couple fixes required for cppcheck to pass, these should be vetted by @SteVwonder).
Additionally, a `deploy:` section is added to auto-upload travis releases on tags.
Finally, a `NEWS.md` file is created with content for the upcoming `0.2.0` release. (Actually I could split that out into a separate PR if people want)

travis updates, and NEWS for 0.2.0

---

configure.ac

This is a copy of @garlick's fix to allow `v` prefix tags from flux-core. 
We'll need this to tag `v0.2.0` of flux-sched.
When generating PACKAGE_ variables from git describe, drop a
leading "v" character if present.  This allows release tags
to be prefixed with a "v" as is the common convention,
without that being reflected in the dist tarball, etc..

build: strip leading "v" from tag name

---

sched/Makefile.am
sched/plugin.c
sched/plugin.h
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
sched/scheduler.h
t/t1004-module-load.t

This PR adds two enhancements to address some of the performance issues discovered from the phase I of our CTS scheduler scalability milestone work [flux-distribution#14](https://github.com/flux-framework/distribution/issues/14).
- Queue-depth support that allows sched to only consider a limited, configurable number of jobs for scheduling on each scheduling event;
- Faster job search using an job index instead of a linear search over all of the job queues.
More details can be found in the individual commit messages. Fix Issue #182 and #183.

optimizations: add queue-depth and better job search support

---

conf/hype.lua
rdl/RDL/types/Node.lua
resrc/Makefile.am
resrc/resrc.c
resrc/resrc.h
resrc/resrc_flow.c
resrc/resrc_flow.h
resrc/resrc_reqst.c
resrc/resrc_reqst.h
resrc/resrc_tree.c
resrc/test/tresrc.c
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c

Introduce flow graph support to the resrc
Expanded the resrc module to support associations to hierarchies beyond just the physical, composite hierarchy.  Multiple hierarchies are now represented by the new flow_graph module.
Yet to do is expand the sched module to exercise scheduling of the flow graphs.  However, I wanted to provide an early preview of the changes.

Graph work

---

sched/Makefile.am
sched/sched.c
sched/scheduler.h
t/Makefile.am
t/t1005-sched-params.t

This is an experimental PR. My apology that this PR contains other optimization items as they are pending for @lipari's review. Commit [22236](https://github.com/flux-framework/flux-sched/commit/22236289334b1c64c2ea6ec64dce5d390b415d2b) is the main commit that I can use your review.  It implements the techniques we discussed at Issue #185. 
Two things:
- This currently breaks a test case: `t2002-easy.t.` I don't understand why changing the timing of invoking schedule_jobs changes the order of a schedule under EASY backfill... There could be some integration I need to do further to make our emulator happy. Since I am not super familiar enough with the emulator code, I thought I could use @SteVwonder's review for this. 
- It is not yet clear whether this actually improves the performance of …

optimization: delayed scheduling support 

---

simulator/simulator.c
simulator/submitsrv.c

flux-framework/flux-core#823 added format attributes to applicable kvs functions, and this caused one place in simluator to exit with a secure-format error where a non-literal format was used.
This PR fixes that build error, and additionally adds some error checking (and removes an extraneous `kvs_commit()`), while I was in there.

fix build error in simulator against latest flux-core master

---

rdl/RDL/memstore.lua
rdl/flux-rdltool.c
rdl/rdl.c
rdl/rdl.h
rdl/test/trdl.c
t/Makefile.am
t/data/rdl/hype.lua
t/lua/t0005-multi-hierarchy.t
t/t0004-rdltool.t

As requested by @dongahn, this PR introduces `rdl:hierarchy_next()` method for Lua rdl to iterate over all hierarchies registered in a give rdl config.
Additionally a C interface `rdl_next_hierarchy (const char *prev)` is introduced to iterate over the hierarchies from C.

Add functions to iterate over all hierarchies in an RDL conf

---

sched/plugin.c

The flux_modlist_t typedef in flux-core no longer hides a pointer.
Change flux-sched's declaration of "mods" to explicitly be a pointer.

Declare flux_modlist_t variable as a pointer

---

sched/flux-waitjob.c
sched/plugin.c
sched/plugin.h
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
sched/scheduler.h
simulator/sim_execsrv.c
simulator/simsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c

The flux_t typedef in flux-core no longer hides a pointer.
Change flux-sched's use of flux_t to match the new pointer-less
definition of flux_t.

Adjust to flux_t no longer containing pointer

---

.travis.yml
rdl/test/Makefile.am
src/test/backtrace-all.sh

Since we build flux-core in travis, and flux-core
recently added a dependency on libjansson, ensure
that it is present in the travis build environment.
Fixes #209

travis-ci: install libjansson-dev package

---

resrc/resrc.c

Check for null when reading the property and tag values from the json
objects.  This check is an improvement independent from the work to
disambiguate json-c and jansson symbols.

resrc:  modify the creation of the properties and tags

---

simulator/sim_execsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c
t/sharness.d/sched-sharness.sh
t/t1004-module-load.t
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t

Remove assumptions where necessary that path to kvs for job `$id` is `lwj.$id`.
Where available, use the `job.kvspath` service to translate jobid to kvs path, if `job.kvspath` is not available, fall back to `lwj.$id`.
@dongahn, the flux-sched branch here, in combination with flux-framework/flux-core#811 should allow PerfExplore testing, once PerfExplore is similarly updated as here. For examples, see `job_kvs_path()` function in `t/sharness.d/sched-sharness.sh` for shell function, or `job_kvspath()` function in `simulator/simulator.c` for C example.
Currently this PR is built on top of #215, if that is merged I can rebase and retest.

Do not assume kvs path to jobs is lwj.ID

---

simulator/sim_execsrv.c
simulator/simsrv.c
simulator/simulator.c
simulator/submitsrv.c

This should not be merged until after flux-framework/flux-core#857 is merged.
Also, before merging, we should restart travis and verify tests pass.  I was having some test problems in my own environment that I don't see how could be related to this PR, but best to be safe.

use new names for JSON accessors

---

simulator/simulator.c
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t

Restores the `kvs_get_dir` that was removed in #281
Cleans up the sim testing scripts so that they are consistent, use flux-waitjob, and have debug printing.

sim: testing and kvs operation cleanup

---

.travis.yml
configure.ac
rdl/jansson-lua.c
src/common/libutil/shortjansson.h

flux-core will shortly require jansson >= 2.6, which tightens up the API allowed in the new functions based on json_pack/json_unpack.
flux-sched should require the same minimum version and by doing so can drop some conditional code for older jansson releases.
This PR should be merged after flux-framework/flux-core#884 is merged.

require jansson >= 2.6 and eliminate conditional code for older versions

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_flow.c
sched/sched.c

A test of performance with the ATS backend found that more than 55% of the overall samples taken in the broker were in json_loads, in sched_backfill, almost all of that time inside the encoding and decoding of twindow entries.  There may be a couple more tweaks here, and the zhashx is not terribly fast and it still sorts and so-forth, but this should cut out almost all of that overhead.

Ats fixes, performance and memory leaks

---

simulator/sim_execsrv.c
simulator/simulator.c

Add flags argument to kvs_commit() calls to work with new KVS API.
To be merged after flux-core PR #982 is merged.

simulator: Update for recent kvs API changes

---

resrc/Makefile.am
resrc/resrc.c
resrc/resrc.h
resrc/resrc_api.h
resrc/resrc_api_internal.h
resrc/resrc_flow.c
resrc/resrc_flow.h
resrc/resrc_reqst.c
resrc/resrc_reqst.h
resrc/resrc_tree.c
resrc/resrc_tree.h
resrc/test/tresrc.c
sched/plugin.h
sched/rsreader.c
sched/rsreader.h
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c

Add resource API context support + some minor cleanup

resrc: Add resource API context support

---

sched/sched.c
simulator/sim_execsrv.c

Corrects a problem that was revealed with
https://github.com/flux-framework/flux-sched/pull/238

sched/simulator:  Add missing sim_state = NULL assignments

---

sched/plugin.c

Adjust flux_request_decode() usage given behavior change in flux-core.
In particular, check json_str for non-NULL after calling to ensure
payload was received.

simulator: Fix flux_request_decode() usage

---

sched/flux-waitjob.c
t/sharness.d/sched-sharness.sh
t/t0002-waitjob.t

The main point of this PR is to add a workaround for flux-framework/flux-core#1027 so we don't have to push out another tag immediately, but the workaround turned out to be a bug fix in `flux-waitjob`, which was not exiting when a job had already run.
The "remove old sentinel files" fix was not based on any observed failure.  Happy to rebase without that one if it's not correct, but it seems right based on my read of hte code.

avoid flux-core bug 1027

---

configure.ac
sched/plugin.c
sched/sched.c
simulator/sim_execsrv.c
simulator/simsrv.c
simulator/submitsrv.c

This PR should be merged after flux-framework/flux-core#1032 is merged.
It adds `-Werror=missing-field-initializers` to CFLAGS and adds missing initializers to the various statically defined `struct flux_msg_handler_spec` arrays.  In flux-core, a "rolemask" field has been added to this struct, and due to ambiguities about how these arrays might be declared and implicitly initialized, it is probably best to make sure rolemask isn't ever registered without explicit initialization.

build: enable -Werror=missing-field-initializers

---

simulator/simsrv.c
simulator/simulator.c
simulator/submitsrv.c
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t

This just updates the single rpc in flux sched for api changes proposed in flux-framework/flux-core#1089
Travis should be re-run after that gets merged.

simulator: use future-based RPC API

---

sched/sched.c
simulator/simsrv.c
simulator/simulator.c
simulator/submitsrv.c
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t

Problems with the simulator were unearthed in https://github.com/flux-framework/flux-sched/pull/246 since this was the first PR to sched in several months.  We temporarily disabled the simulator integration tests until the problems were resolved.   This PR fixes those problems and re-enables the simulator integration tests.
I also refactored a few functions in the simulator to simplify their main loops and logging (I can put these changes into a separate PR, if desired)
To avoid this situation in the future, we have setup a nightly cron job on Travis CI for flux-sched.
Fixes https://github.com/flux-framework/flux-sched/issues/249

Fix simulator and re-enable sim integration tests

---

simulator/simsrv.c
simulator/simulator.c
simulator/submitsrv.c

Tracks changes in https://github.com/flux-framework/flux-core/pull/1104
Old | New
-- | --
flux_kvs_lookup_getf() | flux_kvs_lookup_get_unpack()
flux_msg_set_jsonf() | flux_msg_pack()
flux_msg_vset_jsonf() | flux_msg_vpack()
flux_msg_get_jsonf() | flux_msg_unpack()
flux_msg_vget_jsonf() | flux_msg_vunpack()
flux_rpcf() | flux_rpc_pack()
flux_rpc_getf() | flux_rpc_get_unpack()
flux_event_decodef() | flux_event_unpack()
flux_event_encodef() | flux_event_pack()
flux_request_decodef() | flux_request_unpack()
flux_respondf() | flux_respond_pack()
Fixes #254

sim: track changes in flux-core to jansson functions

---

simulator/submitsrv.c

It would be nice if we could take the output of `sacct` with no (or very little) modification and use it in a simulator run. This is the first step towards this.
You'll notice a bit of weirdness around line 119. This was required to get make check to pass, and I believe it has to do with the semantics when the Submit column is missing or ill-formed. Normally this should be an error but `atof` never returns an error. I tried to just set `stime = 0.0` or something, but that didn't work either. I'm not quite sure what is going on, but this passes `make check` so I am tempted to just leave it.

Added ISO time parsing to job traces

---

sched/sched.c
simulator/sim_execsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c

This PR tracks flux-core API changes proposed in flux-framework/flux-core#1233.  It should not be merged until after that one (and sched travis-ci can be shown to run successfully)
The first commit simply renames functions and types to get sched to comple.
The rest of the commits migrate sched off of functions that now cause "deprecated" warnings from the compiler.  In the process, I did some minor refactoring and error handling cleanup in the simulator code surrounding KVS access to job data.  I hope it's not a pain to review @SteVwonder!

track KVS API changes in flux-core

---

Makefile.am
configure.ac
resource/Makefile.am
resource/planner/Makefile.am
resource/planner/README.md
resource/planner/planner.c
resource/planner/planner.h
resource/planner/test/Makefile.am
resource/planner/test/planner_test01.cpp
src/common/Makefile.am
src/common/librbtree/Makefile.am
src/common/librbtree/compiler.h
src/common/librbtree/rbtree.c
src/common/librbtree/rbtree.h
src/common/librbtree/rbtree_augmented.h

This PR adds the initial support for planner.
Resolve Issue #267

planner: initial planner work

---

simulator/sim_execsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c

This PR was peeled off of #271.  It migrates sched off of functions that now cause "deprecated" warnings from the compiler.  In the process, I did some minor refactoring and error handling cleanup in the simulator code surrounding KVS access to job data.

avoid deprecated KVS functions, minor simulator cleanup

---

rdl/test/Makefile.am
resource/planner/test/Makefile.am
resrc/test/Makefile.am
sched/plugin.c
sched/sched.c
simulator/sim_execsrv.c
simulator/simsrv.c
simulator/submitsrv.c
t/t1004-module-load.t

This PR will allow sched to compile after flux-framework/flux-core#1277 is merged.
I was able to compile test this but for some reason could not get `make check` to pass on my desktop.  I reverted back to master on both flux-core and flux-sched and couldn't get that to work either so I assume it's environmental and unrelated to this PR, so submitted it anyway.
After the above gets merged, travis will need to be manually restarted here.

track bulk message handler registration API change

---

resource/planner/planner.c
resource/planner/test/planner_test01.cpp

- Add a bug fix for a mintime resource tree corruption problem.
- Add a test case.
- This will be needed for upcoming `resource-query` test cases.

planner: fix mintime resource tree corruption bug

---

resource/dfu_traverse_impl.hpp
resource/scoring_api.hpp
sched/flux-waitjob.c
sched/sched.c
t/Makefile.am
t/sharness.d/sched-sharness.sh
t/t1006-cancel.t

This adds support for cancelling pending jobs in response to the `flux wreck cancel` command. (Please see [flux-core Issue #1359](https://github.com/flux-framework/flux-core/issues/1359)).
Note that this PR requires [flux-core PR #1374](https://github.com/flux-framework/flux-core/pull/1374) to be merged into flux-core first. 
Two more items:
- add `errno` support when resource loading fails. [flux-core Issue #1361](https://github.com/flux-framework/flux-core/issues/1361).
- add some log print statements which can be used to help identify the performance/scalability bottleneck of resource loading. [flux-core Issue #1363](https://github.com/flux-framework/flux-core/issues/1363).
Maybe, @SteVwonder and/or @grondo can review this?

sched: Add pending job cancellation support

---

sched/plugin.c
sched/plugin.h
sched/plugin_version.map
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
sched/scheduler.h
t/Makefile.am
t/t2003-fcfs-inorder.t

Avoid traversing the entire resource tree to release reservations at every schedule loop invocation when a very simple, high performance, in-order (queue-depth=1) FCFS policy is used.
See the discussion in https://github.com/flux-framework/flux-core/issues/1358#issuecomment-375429011

sched: Add queue-depth=1 FCFS perf/scalability optimization

---

sched/sched.c
simulator/submitsrv.c
t/t1000-jsc.t
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t
t/t2003-fcfs-inorder.t

This requires the pending [flux-core PR #1389](https://github.com/flux-framework/flux-core/pull/1389).
Add support within the scheduler and emulator for the new `wreck.state.submitted` event with which job request info such as nnodes and walltime is piggybacked.
Use the event's payload and other changes within jsc to optimize job submission handling performance -- i.e., reducing KVS accesses and the number of state transitions.
This should improve the job throughput when the submission rate is super high although I didn't measure the improvements.

Add support for the new wreck.state.submitted event

---

rdl/lua-cpuset.c
resrc/resrc.c
resrc/resrc_reqst.c
simulator/submitsrv.c
src/common/liblsd/Makefile.am

Here are a few minor fixes for issues that came up building sched on my i386 Ubuntu 17.10 test VM, which has gcc-7.2.0.
No issues with the native boost 1.62 on this system.

solve portability issues for Ubuntu 17.10 

---

simulator/submitsrv.c
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t
t/t2003-fcfs-inorder.t

The main problem was a pre-mature destruction of the flux_future.  The unpacked values were later accessed in the packing of the wreck event.  While making changes in the simulator, went ahead and added some additional error checking/messaging and refactored to take advantage of the new `job.submit-nocreate` RPC.
Fixes: #303

sim: fix emulator after introduction of new submit RPC

---

resrc/resrc.c
t/data/hwloc-data/004N/exclusive/04-brokers-sierra/0.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra/1.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra/2.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra/3.xml
t/t1001-rs2rank-basic.t

Per discussion at https://github.com/flux-framework/flux-sched/issues/308:
Incorporate @trws' patch to handle group type.
Add a test case using hwloc xml files collected from Sierra nodes.

Fix for reading hwloc xml files generated from Sierra compute nodes

---

resrc/resrc.c
resrc/resrc.h
resrc/resrc_flow.c
resrc/resrc_reqst.c
sched/flux-waitjob.c
sched/sched.c
sched/sched_backfill.c
sched/sched_fcfs.c
t/Makefile.am
t/t1007-exclude.t

This is an experimental PR. Please don't merge yet.
As requested in https://github.com/flux-framework/flux-core/issues/1415#issuecomment-378117471, I added rudimentary support for excluding or including a node resource by the node's name.
To facilitate testing, this PR also adds support for node-exclusion support. 
This PR has not been fully validated for backfill scheduling. Also, only manually tested with no addition test cases yet.
An node-exclusion command is valid only when the target node has nothing allocated or reserved.
This requires another experimental PR I will post to flux-core that includes `flux wreck exclude` and `flux wreck include`

Add node exclusion support

---

.travis.yml
README.md
configure.ac
t/sharness.d/flux-sharness.sh
t/t0001-basic.t
t/t0003-basic-install.t
t/t1000-jsc.t
t/t1001-rs2rank-basic.t
t/t1005-sched-params.t
t/t1007-exclude.t
t/t2000-fcfs.t
t/t2001-fcfs-aware.t
t/t2002-easy.t
t/t2003-fcfs-inorder.t

This PR syncs `t/sharness.d/flux-sharness.sh` with the version in flux-core.
The `flux-broker --quiet` option was removed recently flux-core, but sched's version of `flux-sharness.sh`  was still using it, resulting in sadness.  Rather than making a small change to sched's verison, I copied over core's version including some other changes.
One such change is a test that any modules loaded within a sharness script are unloaded when the script exits.  This necessitated trivial additions to some tests.

sharness: update flux-sharness.sh script

---

t/t1007-exclude.t

wait-job now waits until the last job gets backfilled and running.
This way, "flux wreck exclude" is guaranteed to happen after
cab1235 resource gets two reservations.

test: Fix a race condition bug in a node exclusion test

---

sched/rs2rank.c
sched/rs2rank.h
sched/rsreader.c
sched/sched.c
sched/scheduler.h
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c
t/data/hwloc-data/004N/exclusive/04-brokers-butte/0.xml
t/data/hwloc-data/004N/exclusive/04-brokers-butte/1.xml
t/data/hwloc-data/004N/exclusive/04-brokers-butte/2.xml
t/data/hwloc-data/004N/exclusive/04-brokers-butte/3.xml
t/data/hwloc-data/004N/exclusive/butte.lua
t/t1001-rs2rank-basic.t

Note that this will fail in Travis because it needs @trws mod in flux-core. I will submit a PR to flux-core soon for that. This addresses the overscheduling issue (#311) that arises when running multiple ranks on a node.

GPU scheduling support

---

resource/Makefile.am
resource/color.cpp
resource/color.hpp
resource/data_std.hpp
resource/edge_eval_api.cpp
resource/edge_eval_api.hpp
resource/fold.hpp
resource/infra_data.cpp
resource/infra_data.hpp
resource/resource_data.cpp
resource/resource_data.hpp
resource/resource_gen_spec.hpp
resource/resource_graph.hpp
resource/sched_data.cpp
resource/sched_data.hpp
resource/scoring_api.cpp
resource/scoring_api.hpp

This PR addresses https://github.com/flux-framework/flux-sched/issues/322.
Refactor Scoring API, Resource Data and Color code.
Now use "using" instead of typedef as we are at C++11.

Refactor the new scheduling infrastructure code + cleanup

---

.travis.yml
rdl/rdl.c
resrc/resrc.c
resrc/resrc_tree.c
sched/rs2rank.c
sched/sched.c
src/common/libutil/shortjansson.h
t/Makefile.am
t/t5000-valgrind.t
t/valgrind/valgrind-workload.sh
t/valgrind/valgrind.supp

This somewhat experimental PR adds the `t5000-valgrind.t` to flux-sched, and fixes some of the leaks found. The valgrind test has the following differences from flux-core:
* runs with `test_expect_failure` because there are still many leaks. Once all detected leaks are fixed the test can be updated.
* A hacky attempt to determine if flux-broker was built with the `dlclose` valgrind wrapper is added, and the test is skipped if the symbol `ZZ_Za_dlclose` isn't found.
* The path to `flux-broker` is determined via `$(PATH=${FLUX_EXEC_PATH} /usr/bin/which flux-broker)`. This should be the flux-broker for the version of flux-core under which flux-sched was configured.
* An extra test is added to ensure the found path to `flux-broker` is executable.
The `valgrind-workload.sh` is also just a copy …

experimental: add valgrind test to flux-sched, fix some leaks

---

configure.ac
m4/ax_valgrind.m4
sched/Makefile.am
sched/plugin.c
t/t5000-valgrind.t

@dongahn, can you try these two commits and see if they have any effect on the results you are seeing with `t5000-valgrind.t`?
IIUC, this should allow flux-sched valgrind test to work with even a flux-core that was not configured with `valgrind/valgrind.h`. Once `sched.so` is dlopened by `flux-broker`, the valgrind spec added to `sched/plugin.c` should become active and reroute future calls to `dlclose()` to the noop wrapped version.
You will have to apply these two commits and rerun `./autogen` and `./configure`. Then ensure that valgrind/valgrind.h was found with 
```
$ grep VALGRIND config.h
#define HAVE_VALGRIND_VALGRIND_H 1
```
Then retry the valgrind tests and ensure there are no false positives/missing symbols.
Thanks!

Add valgrind wrap specification for dlclose in sched/plugin.c

---

configure.ac
resrc/Makefile.am
resrc/resrc_reqst.c
resrc/resrc_tree.c
resrc/resrc_tree.h
sched/sched.c

Add the newly added `idset` support and incorporate `idset` in the `R_lite` generator in resrc_tree.c to condense the core list.

Condensing core id list in R_lite

---

resrc/test/tresrc.c
sched/sched.c
t/scripts/R_lite.lua
t/sharness.d/sched-sharness.sh

This PR drops rank.N and introduces GPU support into `R_lite`. If GPUs are involved, `R_lite` will look like:
`[ { "node": "cab1234", "children": { "core": "0-15", "gpu": "0-1" }, "rank": 0 } ]`
@trws and @grondo: will this representation work? I think `wreck` is okay with the introduction of the `gpu` field.
Now, a bunch of scheduler tests will fail with these changes because of this [sharness script code](https://github.com/flux-framework/flux-sched/blob/master/t/sharness.d/sched-sharness.sh#L127).
I will have to adjust this script code to make use of `R_lite` instead of `rank.N.cores`. I can write a simple C wrapper that makes use of jansson and idset for this purpose, but I'm wondering if flux-core already has some utilities that I can use for this purpose. @grondo?

Drop rank.N support in favor of R_lite

---

sched/sched.c
simulator/sim_execsrv.c
simulator/simsrv.c
simulator/simulator.c
simulator/simulator.h
simulator/submitsrv.c
t/scripts/kvs-watch-until.lua
t/sharness.sh
t/t0000-sharness.t
t/t1000-jsc.t
t/valgrind/valgrind-workload.sh

```
PASS: t2000-fcfs.t 1 - sim: started successfully
FAIL: t2000-fcfs.t 2 - sim: scheduled and ran all jobs
FAIL: t2000-fcfs.t 3 - jobs scheduled in correct order
PASS: t2000-fcfs.t 4 - sim: unloaded
ERROR: t2000-fcfs.t - exited with status 1
PASS: t2001-fcfs-aware.t 1 - sim: started successfully
FAIL: t2001-fcfs-aware.t 2 - sim: scheduled and ran all jobs
FAIL: t2001-fcfs-aware.t 3 - jobs scheduled in correct order
PASS: t2001-fcfs-aware.t 4 - sim: unloaded
ERROR: t2001-fcfs-aware.t - exited with status 1
PASS: t2002-easy.t 1 - sim: started successfully
FAIL: t2002-easy.t 2 - sim: scheduled and ran all jobs
FAIL: t2002-easy.t 3 - jobs scheduled in correct order
PASS: t2002-easy.t 4 - sim: unloaded
ERROR: t2002-easy.t - exited with status 1
PASS: t2003-fcfs-inorder.t 1 - sim: started …
```

sched: Add completing state support

---

sched/sched.c

Problem: exclude_request_cb() unpacks a 'b' boolean
JSON value to a bool, but unpack expects an int.
This caused a segfault on i386 (32-bit).
Change bool to an int.
Fixes #345

sched: fix request handler type mismatch on i386

---

simulator/sim_execsrv.c
simulator/simsrv.c
simulator/submitsrv.c

Use flux_msg_get_string () instead of flux_msg_get_json ().
Resolve Issue #350.

simulator: track a flux-core API change

---

sched/sched.c

sched: Print error messages when schedule_job cannot run

---

resrc/resrc.c
sched/rsreader.c
sched/sched.c
t/data/hwloc-data/004N/exclusive/04-brokers-sierra2/0.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra2/1.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra2/2.xml
t/data/hwloc-data/004N/exclusive/04-brokers-sierra2/3.xml
t/t1001-rs2rank-basic.t

This PR requires a flux-core PR, which I will post soon.
- Modify resrc to recognize and use CoProc devices  as gpu resource type. Include CUDA GPU as well as AMD GPU (at least in theory since I couldn't test this on AMD).
- Add a test using hwloc xml data generated from Sierra using a hwloc library configured with CUDA
- Minor cleanups

Add hwloc-based GPU scheduling support

---

resource/generators/gen.cpp
resource/planner/Makefile.am
resource/planner/planner.c
resource/planner/planner.h
resource/planner/planner_multi.c
resource/planner/planner_multi.h
resource/planner/test/Makefile.am
resource/planner/test/planner_test01.cpp
resource/planner/test/planner_test02.cpp
resource/schema/infra_data.cpp
resource/schema/infra_data.hpp
resource/schema/sched_data.cpp
resource/traversers/dfu.cpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/resource-query.cpp
t/data/resource/commands/basics/cmds03.in

This PR is still experimental: I thought I should post this now as I will be busy with travel for awhile. 
This PR mainly addresses a minimum time resource tree problem within the planner layer. This reverse search tree is designed to satisify a query like "when is the earliest scheduled point at which I can schedule *n* amounts of resources" in `O(lg N)` time. However, this advanced algorithm only works when it deals with a single resource type and doesn't work correctly when it deals with multiple resource types.
In response, this PR limits the planner layer such that that it only manages a single resource type. Instead, it adds `planner_multi_t` layer to handle multiple resources. It also adjusted the rest of the resource code for this change.
Finally a bunch of test cases has also …

Introduce planner_multi_t 

---

.travis.yml

This should make the cron failure notifications more visible to the flux-sched devs (and generally anyone interested in being notified of flux-sched build changes).
Does anyone know who the owner of flux-sched-dev is?  I went to make my own list and noticed this one already existed.  I requested to subscribe.  Maybe @garlick or @grondo is the owner?
I marked it as "in progress" until we know at least 1 person has successfully subscribed to the list.

travis: change email notifications to go to the flux-sched-dev listserv

---

NEWS.md

Add a NEWS entry for v0.6.0 before tagging the release.

NEWS.md: update for flux-sched v0.6.0

---

sched/sched.c

Just noticed trailing whitespaces that were introduced from the latest changes. 
If vim is used, adding the following to `~/.vimrc` should highlight the trailing whitespaces for C code, which can help one not introduce them:
```
let c_space_errors = 1
```

sched: remove trailing whitespaces

---

resource/planner/planner.c

planner_new () can be called from a hot section
of the code and performance profilers discovered that
zhash_new () is way too slow.
With zhash_t, planner_new () accouted for 9.1% of the
graph data store populating. With zhashx_t, it
only accouts for 2.88% for the same operation.
See Issue #390.

planner: Replace zhash_t to zhashx_t for higher performance

---

.travis.yml
Makefile.am
m4/tap-driver.sh
src/test/cppcheck.sh
src/test/docker/bionic/Dockerfile
src/test/docker/centos7/Dockerfile
src/test/docker/docker-run-checks.sh
src/test/travis-lib.sh
src/test/travis_run.sh
t/sharness.d/flux-sharness.sh
t/t2002-easy.t
t/t5000-valgrind.t

I went ahead and copied over the docker scripts from flux-core to get flux-sched building with docker as well. Unfortunately, I wasn't clever enough to write the scripts so they could be exactly shared between different flux-* projects, so the copies here are modified slightly, but work generally the same.
The other difference is that the flux-sched Dockerfiles pull directly from `fluxrm/flux-core:${IMAGE}-latest`, i.e. from the docker images auto-deployed from the flux-core travis builds. If a branch or PR of flux-sched ever requires a specific version of flux-core, the Dockerfiles could be modified to instead pull for `fluxrm/flux-core:${IMAGE}-vx.y.z` to get the tagged flux-core instead.
I also copied over support for TAP_DRIVER_QUIET in `tap-driver.sh`.

travis-ci: use docker for test builds

---

autogen.sh

This PR uses `libtoolize` to resolve Issue #402. It also pulls in some of the options that `flux-core` is using for consistency. 
The autoreconf verbose option catches `autoreconf: configure.ac: not using Gettext`. But I don't think we are ready to add Gettext support so I will leave it this way.

config: Add libtoolize into autogen.sh

---

sched/plugin.c

Problem: flux-core dropped the RFC 5 payload encode/decode
helper functions, and changed the prototype of the
flux_modname() and flux_modfind() functions.
Update sched/plugin to conform to these API changes.
This should go in after flux-framework/flux-core#1856

sched/plugin: track flux-core module API changes

---

resource/Makefile.am
resource/modules/Makefile.am
resource/policies/base/matcher.cpp
resource/utilities/Makefile.am

Solves two common compilations currently affecting master.
Fixes #404 
Fixes #416

Compilation fixes

---

configure.ac
etc/Makefile.am
etc/resource-start
etc/resource-stop
resource/modules/resource_match.cpp
t/Makefile.am
t/sharness.d/sched-sharness.sh
t/t0003-basic-install.t
t/t4001-match-allocate.t
t/t4002-match-reserve.t
t/t4003-cancel-info.t
t/t4004-match-hwloc.t

- Change the default argument of the `prune-filters` load option to `ALL:pu`
- Adjust test cases
- Add `rc1` and `rc3` script for resource
- Update make rules
Resolve Issue #389.

resource: Add run-level support for resource matching module

---

.travis.yml

This addresses missing Docker image deploy as noted by @SteVwonder in #423 (sorry about that!), and also moves the Github release deploy test to look for an explicit environment variable (`GITHUB_RELEASES_DEPLOY`) instead of triggering off `TRAVIS_BUILD_NUMBER == 1`. (Though there was nothing to fix here, keeping in sync with flux-core seemed wise)
To generate the `DOCKER_PASSWORD` environment variable, I ran `travis encrypt` within the flux-sched repo, and pasted in the current password for the `travisflux` user on DockerHub:
```console
$ travis encrypt
Reading from stdin, press Ctrl+D when done
blah blah blah blah
<C-d>
Please add the following to your .travis.yml file:
secure: "sqG5Gimp...="
Pro Tip: You can add it automatically by running with --add.
```
Then pasted the `secure:` key …

travis: fix docker and github release deployment

---

.travis.yml

Ok this fixes the encoding of DOCKER_PASSWORD under `env.global.secure` in `.travis.yml`. I tested in my own repo (but of course that requires a different encryption key, so there is still room for error)

travis-ci: fix docker deploy better

---

.travis.yml
src/test/docker/bionic/Dockerfile
src/test/docker/centos7/Dockerfile

Ok, a couple more cleanups of the Docker build/deploy here:
* Update Dockerfiles to pull from `fluxrm/flux-core:bionic` or `:centos7` tags
* Pass `--prefix=/usr` to docker-deploy builds so that flux-sched is installed to the same prefix as flux-core.

docker: update repo tag names, ensure flux-sched installed with prefix=/usr

---

resource/generators/gen.cpp
resource/modules/resource_match.cpp
resource/planner/planner.c
resource/policies/base/matcher.cpp
resource/policies/base/matcher.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/resource-query.cpp
t/Makefile.am
t/t3011-resource-filt.t
t/t4000-match-params.t

This PR add various fixes to ensure correctness around the use of pruning filters.
- Use at least one pruning filter type to ensure the schedule method within dfu.cpp can traverse resource state changing scheduled points for all cases.
- Enable the pruning filter planner, even if the specified filter types are not present at the subtree of the anchor type. This ensures correctness when such a condition ever arises.
- Add test cases using previous failed test codes
- Add test cases to test various module load options for the resource match service
- Other misc. changes
Resolve Issue #400
Resolve Issue #388

Ensure scheduling correctness with different prune filter configurations

---

sched/priority/modified_fair_tree/Makefile.am
sched/priority/modified_fair_tree/priority_external_api.cpp

As discussed in #433, this PR fixes a couple build issues for the modified fair tree plugin.

Fix build issues for priority_mod_fair_tree.so

---

resource/modules/resource_match.cpp
sched/sched.c
simulator/simulator.c

Update usage of flux_kvs_lookup(), flux_kvs_watch_once(), and
flux_kvs_commit() given changes in flux-core https://github.com/flux-framework/flux-core/pull/1977

resource/sched/simulator: Update KVS API usage

---

resource/modules/resource_match.cpp

Replace call to flux_kvs_watch_once() with flux_kvs_lookup().
Should be merged after https://github.com/flux-framework/flux-core/pull/2011 is accepted.

resource: Update for kvs watch API removal

---

t/scripts/flux-resource

This PR resolves Issue #449. 
Replace `rpc_send ()` to `rpc ().get ()` within `flux-resource` testing front end to track the recent Python API change.

API: remove the use of deprecated Python API

---

resource/modules/resource_match.cpp

Basically just substitute `flux_respond_error (h, msg, errno, NULL)` with `flux_respond_error()`.
Also added `"flux_respond_error"` to the error log for these functions, for ease of debugging if something goes wrong.

resource_match: update to flux_respond_error()

---

resource/generators/gen.cpp
t/data/hwloc-data/001N/amd_gpu/corona11.xml
t/data/hwloc-data/001N/multi_gpu_types/chimera.xml
t/data/resource/commands/basics/cmds11.in
t/data/resource/expected/basics/019.R.out
t/data/resource/expected/basics/020.R.out
t/data/resource/jobspecs/basics/test012.yaml
t/t4004-match-hwloc.t

- Add support for OpenCL device naming convention within hwloc reader
- Add tests for systems with AMD GPUs and mixed GPU types
Please don't merge this before PR #455 and #460 get merged. Because the changes in the previously submitted PRs are substantially, I didn't want to do this PR without those changes.

Add test cases for AMD GPUs

---

qmanager/modules/qmanager.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
src/common/libschedutil/hello.c
src/common/libschedutil/hello.h
t/Makefile.am
t/t1002-qmanager-reload.t

This PR fills in hello callback and exception callback as required by job-manager. The hello callback allows `qmanager` to fill in its running queue as part of load sequence and the exception callback allows for canceling the pending jobs (i.e., jobs with pending alloc requests).
Note that the hello callback is working in progress towards full resilience. More comprehensive solution with respect to `resource` will require a solution for Issue #470. This isn't planned until later this year.
Resolve #492.

qmanager: Add hello/exception callback support

---

resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
t/data/resource/commands/basics/cmds40.in
t/data/resource/expected/basics/040.R.out
t/t1001-qmanager-basic.t
t/t3001-resource-basic.t

This PR fixes a bug where an implicit resource exclusivity created by slot is incorrectly handled.
Problem: When we have some sub-resources under the visiting resource have been allocated to another job, we can prune the further walk even though the visiting resource itself has not been exclusively allocated to another job. But it appears `dfu_impl_t::by_excl ()` does not factor into account the implicit exclusivity that can arise from slot: e.g., with slot[2]->socket[1]->core[1], sockets and cores under slots are implicitly exclusive.
Augment `dfu_impl_t::by_excl ()` to handle this case. 
Augment `t/t3001-resource-basic.t` to cover this case.

Bug fix for incorrectly handling implicit exclusivity

---

etc/resource-start
qmanager/config/queue_system_defaults.hpp
qmanager/modules/Makefile.am
qmanager/modules/qmanager.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
qmanager/policies/queue_policy_conservative.hpp
qmanager/policies/queue_policy_conservative_impl.hpp
qmanager/policies/queue_policy_easy.hpp
qmanager/policies/queue_policy_easy_impl.hpp
qmanager/policies/queue_policy_factory_impl.hpp
qmanager/policies/queue_policy_fcfs.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
qmanager/policies/queue_policy_hybrid.hpp
qmanager/policies/queue_policy_hybrid_impl.hpp
resource/modules/resource_match.cpp
resource/traversers/dfu_impl.cpp
t/Makefile.am
t/scripts/flux-resource
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t4003-cancel-info.t

This PR adds various backfill queuing polices and queue-depth support for optimization:
- Add EASY/HYBRID/CONSERVATIVE policies
Introduce queue_policy_bf_base.hpp and queue_policy_bf_base_impl.hpp that implement core algorithms for a majority of backfillling strategies. Derive from this class to implement EASY/HYBRID/CONSERVATIVE policies.
- Add queue-depth support for backfill policies
This PR builds on PR #502 and PR #503 so please don't merge it before those PRs land. Resolve #476, #482, and #498.

Add EASY/HYBRID/CONSERVATIVE policies

---

resource/modules/resource_match.cpp
t/Makefile.am
t/scripts/flux-resource
t/t4006-properties.t

Resolve issue #494, get/set property is now supported in `flux resource` through RPC.

resource: add set- and get-property support to match service

---

t/sharness.d/flux-sharness.sh

The flux-broker no longer supports FLUX_RC1_PATH and FLUX_RC3_PATH.
Update to flux-sharness.sh from flux-core so that test_under_flux
no longer uses these variables.
When testing this update I was getting some hangs, though I'm not sure how it is related to this PR. I'll keep poking at it, but wanted to propose this update sooner than later.

testsuite: update flux-sharness.sh to version from flux-core

---

configure.ac

Fix a copy-and-paste error in the rc3 directory definition for qmanager. Without a proper rc3, qmanager wasn't cleanly exited when the Flux instance is torn down:
```
module 'qmanager' was not cleanly shutdown
```
Resolve #524.

rc3: Fix a bug in RC3 dir definition within configure.ac

---

qmanager/modules/qmanager.cpp
qmanager/policies/queue_policy_factory.hpp
qmanager/policies/queue_policy_factory_impl.hpp
resource/libjobspec/jobspec.cpp
resource/libjobspec/jobspec.hpp
resource/modules/resource_match.cpp
resource/policies/dfu_match_policy_factory.cpp
resource/policies/dfu_match_policy_factory.hpp
resource/readers/resource_reader_base.cpp
resource/readers/resource_reader_base.hpp
resource/readers/resource_reader_grug.cpp
resource/readers/resource_reader_grug.hpp
resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_hwloc.hpp
resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
resource/readers/resource_spec_grug.cpp
resource/store/resource_graph_store.cpp
resource/store/resource_graph_store.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu.hpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/command.cpp
resource/utilities/command.hpp
resource/utilities/grug2dot.cpp
resource/utilities/resource-query.cpp
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp

This PR adds smart pointer support using `std::shared_ptr` to:
- Improve memory management by disallowing memory leaks in general;
- Allow the traverser code to use shared pointers on a few key member variables: filtered graph, metadata and match policy callback members. The traverser does not solely "own" these objects (in fact they are being passed from outside), and this means using raw pointers requires a careful manual coordination between the owners of these objects. Sharing the ownership of these objects using std::shared_ptr should be safer and far more elegant.
This PR also adds a few other cleanups:
- Use fully qualified `std` namespace paths for all of the symbols in this namespace;
- Change log messages within the `resource` module to include the function name in the message, …

Add smart pointer support and misc. cleanup

---

etc/qmanager-start
etc/resource-start
t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t4000-match-params.t
t/t4004-match-hwloc.t
t/t4008-match-jgf.t

This PR makes some minor changes to the the way `flux module` is called, preparing for flux-framework/flux-core#2612 to be merged.  This PR should go in first or sched will no longer work with the flux-core master once the core PR is merged.

drop flux module -r option

---

t/t4000-match-params.t

Problem: flux-core changed flux module unload to return failure
if the module is not loaded.  This breaks flux-sched tests that
depended on that behavior.
Ignore that error where appropriate in the test.

t4000-match-params.t: suppress flux module unload failure

---

.github/workflows/main.yml

Copy workflow config from flux-core which validates that no commits in a PR are not valid for merging (i.e. have "fixup" or "squash" in the subject, or are merge commits)

github: add workflow action to validate PR commits

---

.travis.yml
configure.ac
src/test/docker/centos8/Dockerfile
t/scripts/flux-jsonschemalint
t/scripts/flux-resource
t/t4003-cancel-info.t
t/t4006-properties.t

This PR enables a CentOS 8 build for flux-sched and fixes associated errors.
Many of the changes here were required due to the fact that Python 3.6 is the default /usr/bin/python in the centos8 docker image. I have no idea if I made the right fixes there, so feedback welcome!
Fixes #563

Fix build/test issues and enable travis on CentOS 8

---

t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t

Problem: In upstream flux-core the `flux job list` plumbing tool
was changed to only output JSON, which breaks some of the flux-sched
tests which use this tool to count active and running jobs.
Update flux-job list usage in the qmanager tests to prevent failures.
Note: although `flux job list` and `flux job list --states=active`
are currently equivalent, use the latter form in tests to be
explicit as well as protect the tests from potential changes
in the default output of `flux job list.
Fixes #570

testsuite: update flux-job list usage

---

README.md

also change the python-yaml dependency to python3-yaml, since flux-core has moved to python3 by default

README: add copy-and-pastable dependency install line for ubuntu

---

config/ax_python_devel.m4
configure.ac

copy python m4 macro and usage from flux-core
`PYTHON_VERSION=3.6 ./configure` will now work even if `/usr/bin/python` is `2.7`.
Closes #567

configure: support PYTHON_VERSION precious variable

---

t/t1002-qmanager-reload.t

In flux-framework/flux-core#2733, the github workflow build against flux-sched is hanging in teardown of the qmanager-reload test.
Recently we added cleanup of running jobs to rc3 with `flux job cancelall --states=RUN`, and a call to `flux  queue idle` which blocks until jobs in RUNNING or CLEANUP states transition to INACTIVE.  Since the qmanager-reload test leaves jobs running and exits wtihout a scheduler loaded, this cleanup hangs because the job manager can't free the resources of those jobs, so they are stuck in CLEANUP.
Before the above PR, rc3 just timed out and the rc3 failure was ignored.
After the PR, rc3 doesn't run under the timeout, so the test hangs running `flux queue idle`.
The tools like `flux job cancelall` that make cleaning up the running jobs within the test easy are …

testsuite: avoid rc3 hang in qmanager-reload test

---

README.md

Reference the flux-core install instructions, rather than copying them.
Provide flux-sched install instructions for both the cases where flux-core is "system installed" and "side installed".
Add a note about the convenience of having flux-core and flux-sched installed to the same prefix.
Closes #594

README: clarify install instruction to better align with flux-core

---

configure.ac
src/Makefile.am
src/cmd/Makefile.am
src/cmd/flux-tree
t/Makefile.am
t/sharness.d/sched-sharness.sh
t/t2000-tree-basic.t

This PR is experimental as I wanted to  get some feedback from end users (in particular @jamescorbett) who are waiting for this feature. 
This adds a new flux command called flux-tree, which creates Flux instance hierarchy according to the specified policies and schedule/run the specified number of Jobscripts at the last level of this hierarchy.
As a next step, in addition to gathering feedback from the users, I plan to heavily use the `--dry-run` option to add test cases.

Add flux-tree support

---

t/t1002-qmanager-reload.t

Problem: A qmanager reload test is randomly
failing in Travis CI, which tests jobs in
the job-manager queue aren't lost during
the reload. This test enqueues a few jobs
and removes/reloads qmanager before checking
if those jobs are still in the queue.
But because this test only gives
1 second walltime for those jobs, there is
a chance that a job can complete before
the reload is done.
Use 100 seconds as the walltime for
those jobs to break those jobs "effectively".

testsuite: break a race in a qmgr reload test

---

src/cmd/flux-tree

Option has been removed in flux-core issue #2796 (PR https://github.com/flux-framework/flux-core/pull/2807)
Credit to @SteVwonder for patch.

cmd/flux-tree: Remove -j option to kvs put

---

etc/qmanager-start
etc/resource-start
t/t1005-qmanager-conf.t

This PR changes the behavior of the rc1 scripts of flux-sched modules. 
Currently, some of the in-tree tests are failing when flux-sched is  already installed within flux-core. Their rc1 scripts are executed and load those "installed" modules instead of "in-tree" modules.
Use "flux reload -f <qmanager|resource>" so that when these failing tests load them via the FLUX_RC_EXTRA environment variable, the in-tree versions are loaded.
Discussed at https://github.com/flux-framework/flux-core/issues/2788#issuecomment-593131902. 
Fix #607 and #604 .

rc: use reload -f to load qmanager/resource

---

resource/modules/resource_match.cpp
resource/readers/resource_reader_jgf.cpp
resource/traversers/dfu_impl_update.cpp
resource/utilities/command.cpp
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp
t/t6001-match-formats.t

This PR reworks the match writers to use Jansson for emitting JSON-based writers.
Currently, the match writers commonly use C++ `std::stringstream` to emit resource set information regardless of emitting formats: i.e., plain-text formats or JSON-based formats alike. For a JSON-based format, however, this approach is becoming increasingly more complex to modify when we change the format.
Use Jansson to emit all of the JSON-based resource set information including `rlite`, `jgf`, `rv1` and `rv1_nosched` formats.
This should address the issues identified from my previous attempt: #613.
Fix #610 and #383.

Use Jansson for JSON-based writers + time keys in RV1

---

src/cmd/Makefile.am
src/cmd/flux-tree
src/cmd/flux-tree-helper.py
t/sharness.d/flux-sharness.sh
t/t2000-tree-basic.t

Problem: constructing and manipulating JSON blobs via the command line
has a high overhead and quickly exceeds the limit for command line
argument length set in the linux kernel.
Solution: Add a helper written in python that performs the same
action but using python's standard library utilities and the flux python
bindings.  This reduces the number of processes launched, eliminates the
need for using command line arguments to pass JSON blobs between
programs, and reduces the total number of times the JSON needs to
be (de-)serialized.
Results:
Before the helper, for a tree topology of 32x36, the perf
results record a runtime of 45 seconds, but the `time` utility used on
the flux-tree command directly reports a runtime of 3 minutes 45
seconds.  After the introduction of the helper, for the …

Flux tree helper

---

src/cmd/flux-tree
src/cmd/flux-tree-helper.py
t/Makefile.am
t/t2000-tree-basic.t
t/t2001-tree-real.t

This PR adds `--flux-rundir` support to `flux-tree`.
Problem: For a large flux-tree test where lots of flux instances are used, the content store back-ends can use lots of memory leading to OOM.
Provide `--flux-rundir=DIR` option which sets the rundir to DIR so that the content stores can be redirected to a subdirectory in DIR for this case. Use the rundir attribute because upon the exit of each Flux instance, its content store sqlite file is removed.
Add two test cases that uses `--dry-run`

flux-tree: add rundir support

---

resource/readers/resource_reader_jgf.cpp
resource/utilities/resource-query.cpp
t/t6000-graph-size.t

Problem: when loading a JGF graph, the JGF reader does not insert key-value pairs into the `by_path` map in `resource_graph_metadata_t` (issue #639).
This patch populates the map in the `add_graph_metadata` member function as intended.

Add path, vertex pair to by_path map

---

src/test/docker/docker-run-checks.sh
src/test/travis_run.sh

Use the `entrypoint.sh` from flux-core by default in published flux-sched docker images, so that `docker run -ti fluxrm/flux-sched` works the same as `docker run -ti fluxrm/flux-core`, i.e. munged is started and user is dropped into an instance of size=1.
Also, pull in @trws' `--build-directory` option for `docker-run-checks.sh` since this has been useful.

docker: add ENTRYPOINT to start munged by default

---

etc/qmanager.toml
qmanager/modules/Makefile.am
qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_opts.cpp
qmanager/modules/qmanager_opts.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
qmanager/policies/queue_policy_conservative_impl.hpp
qmanager/policies/queue_policy_factory.hpp
qmanager/policies/queue_policy_factory_impl.hpp
qmanager/policies/queue_policy_hybrid_impl.hpp
src/common/liboptmgr/optmgr.hpp
src/common/liboptmgr/optmgr_impl.hpp
t/conf.d/01-default/qmanager.toml
t/conf.d/02-no-keys/qmanager.toml
t/conf.d/03-extra-keys/qmanager.toml
t/conf.d/04-conservative/qmanager.toml
t/conf.d/05-small-queue-depth/qmanager.toml
t/conf.d/06-hybrid/qmanager.toml
t/conf.d/07-hybrid2/qmanager.toml
t/conf.d/08-no-queue-depth/qmanager.toml
t/conf.d/09-invalid-policy/qmanager.toml
t/conf.d/10-neg-value/qmanager.toml
t/conf.d/11-no-params/qmanager.toml
t/conf.d/12-no-policy-params/qmanager.toml
t/conf.d/13-bad-value/qmanager.toml
t/conf.d/14-no-queue-params/qmanager.toml
t/conf.d/15-no-qmanager/qmanager.toml
t/t1005-qmanager-conf.t

This PR adds a better module option-set management support and update `qmanager` on top of it.
- Add generic module option management helper classes into `src/common/liboptmgr`: `optmgr_composer_t`, `optmgr_kv_t` and `optmgr_parse_t`;
- Add a `qmanager`-specific option-set class that uses and conforms to the generic management class (`qmanager_opts_t`);
- Integrate `qmanager_opts_t` into `qmanager` to reduce the complexity of option-set management. This will be particularly essential as I will add multi-queue support into `qmanager` soon with more complex set of options;
- Adjust test cases and `qmanager` configuration files.

Add new option-set management support

---

configure.ac
qmanager/modules/Makefile.am
qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_callbacks.hpp
src/common/Makefile.am
src/common/c++wrappers/Makefile.am
src/common/c++wrappers/eh_wrapper.hpp
src/common/c++wrappers/test/Makefile.am
src/common/c++wrappers/test/exception_safe_wrapper_test01.cpp

This PR uses the `eh_wrapper_t` class to add
exception safety for schedutil callbacks.
- Refactor callbacks for `schedutil` into two classes
in new header and source files:
`qmanager_cb_t` contains the existing code;
`qmanager_safe_cb_t` wraps it with `eh_wrapper_t`.
-  Avoid interdepedency between `qmanager` and
the classes in `qmanager_callbacks.hpp` by
introducing `qmanager_cb_ctx_t` to make
it easy for the `qmanager` module to
pass its state to these new classes.
- Update `qmanager` code and build rules to add
the new files.

qmanager: add exception safety for schedutil callbacks

---

qmanager/modules/Makefile.am
qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_callbacks.hpp
qmanager/modules/qmanager_opts.cpp
qmanager/modules/qmanager_opts.hpp
resource/libjobspec/jobspec.cpp
resource/libjobspec/jobspec.hpp
src/common/liboptmgr/optmgr.hpp
src/common/liboptmgr/optmgr_impl.hpp
t/Makefile.am
t/conf.d/16-multiqueue/qmanager.toml
t/conf.d/17-mq-hetero/qmanager.toml
t/conf.d/18-mq-override/qmanager.toml
t/t1005-qmanager-conf.t
t/t1006-qmanager-multiqueue.t

This PR is work in progress to add multi-queue support within `qmanager`.
Build on top of a merge of two pending PRs: PR #645 and PR #646.
As described in Issue #640, it adds the following modifications:
- Replace a single queue object (of `queue_policy_base_t` class) with
a `std::map` that contains a configurable number of queue objects
keyed off of distinct queue names.
- Add ways to specify multiple queues both through configuration files
and module load options while keeping the current conf/load option
set backward compatible as much as possible. 
Each specified queue can enforce a queueing policy, queuing
parameters and queueing-policy parameters, independent of one another.
- Bring in libjobspec to fetch the queue information from
`system.attributes.queue` key of a jobspec and use …

qmanager: add multi-queue support

---

.travis.yml
src/test/docker/docker-run-checks.sh
t/scripts/run_timeout.py
t/sharness.d/flux-sharness.sh
t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t4008-match-jgf.t
t/t6001-match-formats.t

This PR updates `t/sharness.d/flux-sharness.sh` from flux-core, including
* @trws's `run_timeout.py` test timeout improvements
* Support for `TEST_CHECK_PREREQS` to validate `jq` usage protected by `HAVE_JQ`
Also adds `TEST_CHECK_PREREQS=t` to one travis builder, and fixes resulting fallout.
The test is based on #655, so that name changes would not conflict. This PR should go in after that one is merged.

testsuite: update flux-sharness.sh from flux-core

---

t/t1002-qmanager-reload.t

This PR fixes a hang that will come up once flux-framework/flux-core#2949 is merged. Since the `resource` module now shares resource configuration with sched-simple via the acquire interface, this module must be reloaded once hwloc data is manually overridden, or else sched-simple will reject free requests after it is reloaded at the end of the test.
I suppose since #657 has not been merged yet, I can tack this onto that PR if that would be better.

Fix t2002-qmanager-reload.t with new core resource module

---

resource/modules/resource_match.cpp

Avoid any name collision with the new resource module within flux-core.

resource: use the full module name for flux_aux_get|set()

---

resource/modules/Makefile.am
resource/modules/resource_match.cpp
resource/readers/resource_reader_grug.cpp
resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_jgf.cpp
resource/store/resource_graph_store.hpp
resource/utilities/resource-query.cpp
t/Makefile.am
t/scripts/flux-ion-resource.py
t/t6000-graph-size.t
t/t6002-graph-hwloc.t

This PR addresses [item II.3](https://github.com/flux-framework/flux-sched/issues/662#issue-628053510) from issue #662 by introducing a `by_rank` map to `resource_graph_metadata_t`.  The map is keyed by the `int64_t` `rank` and takes a `std::vector` of `vtx_t` corresponding to the subgraph associated with the rank.  The changes include populating the map in the GRUG, JGF, and hwloc readers and the addtion of testsuite checks for correct subgraph sizes.
This PR should be merged before #665 and #667 as those depend on the features created here.

Add by_rank map to graph store

---

resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_jgf.cpp
resource/schema/resource_data.cpp
resource/schema/resource_data.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu.hpp
resource/traversers/dfu_impl.hpp
resource/traversers/dfu_impl_update.cpp
resource/utilities/command.cpp
resource/utilities/command.hpp
t/Makefile.am
t/data/resource/commands/status/cmds01
t/data/resource/commands/status/cmds02
t/data/resource/commands/status/cmds03
t/data/resource/commands/status/cmds04
t/data/resource/commands/status/cmds05
t/data/resource/commands/status/cmds06
t/data/resource/commands/status/cmds07
t/data/resource/commands/status/cmds08
t/data/resource/expected/status/001.R.out
t/data/resource/expected/status/002.R.out
t/data/resource/expected/status/003.R.out
t/data/resource/expected/status/004.R.out
t/data/resource/expected/status/005.R.out
t/data/resource/expected/status/006.R.out
t/data/resource/expected/status/007.R.out
t/data/resource/expected/status/008.R.out
t/t3024-resource-status.t

This PR addresses issue #662 item II.1 by creating an enum class as part of [`resource_pool_t`](https://github.com/flux-framework/flux-sched/blob/master/resource/schema/resource_data.hpp#L41) that tracks resource status (e.g. `UP` and `DOWN`).  To read, change status values, and enable testing, this PR makes additional contributions:
1. enable the JGF reader to unpack the optional `status` key
2. a new `resource-query` command (`dump`) to write the resource graph to a file according to status
2. a new `resource-query` command (`set-status`) to perform a DFV update of a resource subtree status
A follow-up PR will enable scheduling by resource status based on the additions here.

Resource status

---

etc/sched-fluxion-resource-start
resource/modules/resource_match.cpp
resource/readers/resource_reader_base.cpp
resource/readers/resource_reader_base.hpp
resource/readers/resource_reader_grug.cpp
resource/readers/resource_reader_grug.hpp
resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_hwloc.hpp
resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
resource/utilities/command.hpp
resource/utilities/resource-query.cpp
src/cmd/flux-tree
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t1007-recovery-full.t
t/t1008-recovery-none.t
t/t1009-recovery-multiqueue.t
t/t2000-tree-basic.t
t/t2001-tree-real.t
t/t4004-match-hwloc.t
t/t4009-match-update.t

This was done via simple search & replace, nothing more than that.
Fixes #669

Globally rename whitelist to allowlist

---

t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t1006-qmanager-multiqueue.t
t/t1007-recovery-full.t
t/t1008-recovery-none.t
t/t1009-recovery-multiqueue.t

To avoid test failures on slower systems like travis, increase
wait-event timeouts from 2 to 10 in all sharness tests.
Fixes #687

testsuite: increase wait-event timeouts

---

qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_callbacks.hpp
t/t1001-qmanager-basic.t

@dongahn and flux-sched team
I know you were going to handle the changes, but since https://github.com/flux-framework/flux-core/pull/2960  has a lot of changes to `libschedutil`, I decided to do a quick run to get `flux-sched` to compile to show you the high level changes.  This patch is mostly informational.  You can just close the PR if you'd like or take the patch as a starting point or if you think it's close to what you'd want, LMK and I can clean it up and finish it.
I did not look at anything beyond just "make it compile" and did not look at any fallout from these changes.  And (somewhat naturally) it doesn't take advantage of anything new (which should probably be later, once support is in `flux-jobs`).
The 1 logical change made was to the `exception_cb` functions, which should …

qmanager: Update for flux-core annotation support changes

---

resource/Makefile.am
resource/readers/resource_reader_jgf.cpp
resource/schema/sched_data.cpp
resource/traversers/dfu_impl_update.cpp

This PR removes compiler workarounds that were needed
as g++ 5.4.0 wouldn't compile some versions of
boost graph library.
Without these workarounds, compilers caught a few issues
with unused variables so this PR also fixes them.
Fix Issue #300.

Undo compiler workarounds

---

resource/modules/resource_match.cpp
t/t4000-match-params.t

This PR fixes Issue #561 
Problem:
We currently set `errno=EIO` when
`ifstreamm::good()` returns false after
`ifstream::open()`. Errno from
`std::ifstream` operations is undefined
in C++ standards so we manually set it
this way to describe "all IO errorrs."
However, `EIO` is often too broad for this
purpose. For example, if `open` fails because
the file does not exist, the most common case,
you would rather want to see `errno=ENOENT`
Solution:
Leverage the fact that most of platforms will
actually set `errno` correctly as they are set
from the underlying system libraries and we
only set `errno=EIO` when it is not the case.
Augment the testing of `errno` behavior for
a few failure modes.

resource: errno support for std::ifstream open

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
t/Makefile.am
t/t1013-qmanager-priority.t

This is a bug fix PR fixing Issue #612.
Order pending jobs by priority and submit time:
Problem: Currently the pending jobs within
fluxion's qmanager is ordered by enqueue time
as seenby qmanager, not by the enqueue time as seen
by job-manager. Further, it doesn't take
into account the job's priority either, which
can lead to various side-effects.
Change the "key" of the pending queue map from
uint64_t to be std::vector<double> such that
pending jobs are now ordered lexicographically
according to this vector.
Use <priority, t_submit> as the current key.
This change can easily accomodate other
order-affecting changes that are expected
to be introduced in the future including
fair share priorities.
Fixes Issue #612.
This PR is written on top of PR #694
and only consists of three commits.

qmanager: order pending jobs by priority/submit time

---

NEWS.md

The release note includes the pending PR #694. So don't merge this before that PR. I don't know if PR #695 can also be merged in time. If it does, we should add the following to our note as well.
* qmanager: support for ordering pending jobs by priority/submit time

NEWS.md: add release notes for v0.10.0

---

resource/evaluators/expr_eval_api.cpp

Problem: `find_first_not_of` can return `string::npos`, which if passed
as an index to an element acess, can cause an out-of-bounds access
Solution: check for this possible return value, and handle it
appropriately
Related: #711

resource: check return value of `find_first_not_of`

---

src/cmd/flux-tree
t/scripts/flux-ion-resource.py
t/t1006-qmanager-multiqueue.t
t/t1009-recovery-multiqueue.t

This small PR updates various parts of flux-sched to avoid the assumption of integer-only jobids.
Most of the changes are straightforward, and should work whether flux-core commands are emitting integer or F58 encoded jobids. So this paves the way for an update in flux-core to allow more F58 encoded jobids.

Update for non-integer jobid encodings

---

qmanager/modules/qmanager.cpp
resource/modules/resource_match.cpp
t/t1008-recovery-none.t
t/t1010-sync-modules.t
t/t4000-match-params.t

This PR is the rework of @garlick's closed PR #716.
- Call flux_module_set_running() before beginning synchronous RPCs in `sched-fluxion-qmanager` and `sched-fluxion-resource` so that flux module load doesn't block until the initialization completes. This resolves a deadlock introduced by broker initialization changes introduced in flux-framework/flux-core#3057.
- Adjust the test cases that require `flux module load` of a fluxion module to fail. When `flux_module_set_running()` was called, the error hasn't yet happened so `flux module load` returned successfully, producing some test failures. Use `flux module stats` to test the module initialization failure, instead.
Fixes #712 and #713.

Let flux module load return early

---

resource/modules/resource_match.cpp
t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t1007-recovery-full.t
t/t1009-recovery-multiqueue.t
t/t1010-sync-modules.t
t/t1011-dynstate-change.t

This PR fixes various errors that manifest themselves under `FLUX_TEST_VALGRIND=t`
- Fix a few double frees detected by Valgrind!
- Fix various synchronization issues in our test scripts that led to hangs and failures. They were exposed as Flux significantly slows down under Valgrind.
Fix Issue #506, #585, #733.

Fix various errors detected when run tests under valgrind

---

resource/evaluators/edge_eval_api.cpp
resource/evaluators/edge_eval_api.hpp
resource/evaluators/scoring_api.cpp
resource/evaluators/scoring_api.hpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
t/Makefile.am
t/data/resource/commands/sibling/cmds01.in
t/data/resource/commands/sibling/cmds02.in
t/data/resource/commands/sibling/cmds03.in
t/data/resource/expected/sibling/001.R.out
t/data/resource/expected/sibling/002.R.out
t/data/resource/expected/sibling/003.R.out
t/data/resource/jobspecs/sibling/test001.yaml
t/data/resource/jobspecs/sibling/test002.yaml
t/data/resource/jobspecs/sibling/test003.yaml
t/t3026-resource-sibling.t

This PR adds support for detecting and more gracefully handling a class of invalid sibling requests within jobspecs. While our DFU traverser has in-line documents and README to describe its fundamental inability to match a jobspec containing sibling requests with the same resource type, for example,
```
node[1]->socket[1]
->socekt[1]
```
the current code does not detect and handle this condition gracefully.
- Detect this condition at the `match()` method and bubble this up to the upper calls so that they can deem this as `match_kind_t::NONE_MATCH`;
- Related, avoid a potential buffer overflow that can arise when we iterate through the slots discovered by the DFU walk from the visiting resource vertex. This condition can occur if `cnt_slot()` incorrectly counts the number of available …

Handle invalid sibling requests in jobspec more gracefully 

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
t/Makefile.am
t/t1012-find-status.t
t/t1014-annotation.t

This PR adds support for annotating jobs with their belonging queue name and start-time estimate.
- Modify the backfill scheduler queue policy base class code such that all reservations are removed in the beginning, instead of at the end, of each scheduler loop iteration. This way, the reserved time for each high priority job is preserved until the next scheduler loop is called and can be used as its start-time estimate during this window.
- As part of our scheduler loop iteration epilogue, send a job annotation for each of the pending jobs that have reservations. Only send the annotation when the reserved time changes from its previously calculated reserved time.
- Add tests to ensure annotating jobs with queue and start-time estimate (`t_estimate`) work as expected. Test covers all …

qmanager: Add support for job annotation

---

NEWS.md

flux-sched version 0.11.0 - 2020-08-31
--------------------------------------
Note: Fluxion can now annotate its jobs with their
start-time estimate and queue info (to be displayed by `flux-jobs`).
* Handle invalid sibling requests in jobspecs more gracefully (#737)
* Fix various errors detected when tests are run under valgrind (#734)
* fluxion-resource: check return value of `find_first_not_of` (#715)
* Add support for job annotation including its start-time estimate (#735)
* Add support for node-local storage to hwloc reader (#714)
* flux module load returns early for staggered system-instance bring-up (#719)
* Update for non-integer jobid encodings (#718)
* Use version 9999 for test jobspecs (#739)
Fix #738

news: Add NEWS.md for v0.11 release

---

etc/01-sched-fluxion-qmanager-stop
etc/01-sched-fluxion-resource-start
etc/02-sched-fluxion-qmanager-start
etc/02-sched-fluxion-resource-stop

Problem: flux-core is about to transition to rc1/rc3 scripts executing
on all ranks, which would cause the fluxion scheduler to be loaded
on all ranks.
Check the rank at the beginning of the rc scripts and exit 0 if running
on a rank other than 0.
This change has no effect when run with the current 0.19.0 flux-core, but it will allow flux-sched to continue to work into 0.20.0 development.

rc: only load/unload scheduler on rank 0

---

t/t1014-annotation.t

Skip test expected to fail in flux-core, so that flux-core fix can pass travis.
I didn't know if there was a convention for how to skip a test in this instance, so just added a prerequisite FLUXCORESKIP, which is not defined anywhere.

t/t1014-annotation: skip expected flux-core fail

---

t/t1014-annotation.t

Remove expected test failure now that flux jobs is fixed in flux-core.
Add a successful test check into the prior test instead.

t/t1014-annotation: Remove expected test fail

---

qmanager/modules/qmanager_callbacks.cpp
t/t1014-annotation.t

When a job allocation is successful, rather than set t_estimate to
0.0, remove the annotation.
Update tests in t/t1014-annotation.t accordingly.

qmanager: remove t_estimate when job alloc success

---

t/sharness.d/sched-sharness.sh
t/t4004-match-hwloc.t
t/t4009-match-update.t
t/t6002-graph-hwloc.t

This PR changes the `load_test_reosurces()` shell function to load the core resource module wiith the `monitor-force-up` option to ensure that all broker ranks are marked UP in the first response to `resource.acquire`.
The ensures that the change proposed in flux-framework/flux-core#3207 does not break scheduler tests.
Also, fix a couple of tests that were still calling `flux hwloc reload` directly to use `load_test_resources()`.
There is no harm in merging this PR before the core one, as the new option will simply be ignored by the resource module.

testsuite:  use monitor-force-up in load_test_resources()

---

configure.ac

For consistency to flux-core issue #3239, increase the minimum
jansson version to 2.10.

build: bump minimum jansson version to 2.10

---

config/ax_boost_base.m4

Problem: when using the latest gcc/clang compilers, older boost versions
create multiple warnings to be emitted.  Our use of `-Werror` turns
these warnings in boost into hard errors, despite being in a third-party
dependency.
Solution: use `-isystem` rather than `-I` for the boost cppflags to
denote that the boost headers are system-provided headers, which turns
off most static analysis warnings for those headers.
Related Documentation:
- Clang: http://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-in-system-headers
- GCC: https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html
Closes #300 
Closes #747 
Closes #732

makefile: workaround boost errors under latest compilers

---

config/ax_flux_core.m4
qmanager/modules/qmanager.cpp
resource/Makefile.am
resource/modules/Makefile.am
resource/utilities/Makefile.am
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp
t/Makefile.am
t/data/resource/expected/RV/R1.out
t/data/resource/expected/RV/R2.out
t/data/resource/expected/RV/R3.out
t/data/resource/jgfs/4node.rank0123.nid0123.mod.json
t/data/resource/jgfs/4node.rank0123.nid0123.orig.json
t/data/resource/jgfs/4node.rank1230.nid0123.mod.json
t/data/resource/jobspecs/RV/full.yaml
t/t1010-sync-modules.t
t/t3027-resource-RV.t

This PR adds support for the recent RV1 change: https://github.com/flux-framework/rfc/pull/268. Other changes include:
- Compress the `execution.R_lite` JSON array. Without the actual node names in this array, we will get an extremely high compression rate and thus we do this now.
- Add test cases using three simple 4-node machine configurations. 
- Move `schedutil_create` into the "constructor" of qmanager as starting up a multi-node testing was failing on the latest rc1 change in flux-core.
Fix Issue #761, #753.

Add support for nodelist for RV1 change and R_lite compression

---

.mergify.yml
.travis.yml

flux-sched has be migrated from travis-ci.org to travis-ci.com. Update mergify config accordingly (also, remove one deprecated key in the .travis.yml config)

update configs for travis-ci.com migration

---

resource/modules/resource_match.cpp
t/data/hwloc-data/001N/exclusive/01-brokers-sierra2/0.xml
t/data/hwloc-data/001N/exclusive/01-brokers/0.xml
t/data/hwloc-data/004N/exclusive/04-brokers/0.xml
t/data/hwloc-data/004N/exclusive/04-brokers/1.xml
t/data/hwloc-data/004N/exclusive/04-brokers/2.xml
t/data/hwloc-data/004N/exclusive/04-brokers/3.xml
t/sharness.d/sched-sharness.sh
t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t1007-recovery-full.t
t/t1008-recovery-none.t
t/t1009-recovery-multiqueue.t
t/t1013-exclusion.t
t/t1013-qmanager-priority.t
t/t1014-annotation.t
t/t4009-match-update.t
t/t6002-graph-hwloc.t

This is tracking changes in flux-framework/flux-core#3265 to the way that dummy resources are loaded in test.
That PR is still undergoing development and this one should wait until it is merged.

expect Rv1 from resource.acquire, use flux resource reload

---

NEWS.md

This release notes assumes that #743 will go in before we tag a release

NEWS.md: prepare for 0.13.0 release

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
t/t1013-qmanager-priority.t

Per RFC21 update (flux-framework/rfc#277) the "administrative priority" has been renamed to "urgency".
Globally update flux-sched for this change. This is built on and dependent on https://github.com/flux-framework/flux-core/pull/3394

Globally rename "administrative priority" to "urgency"

---

t/t0000-sharness.t

Problem:  The sharness tests fail if debug=t or verbose=t is set
in the environment since sub-sharness tests cannot tolerate the
extra output triggered by these variales.
Unset 'debug' and 'verbose' in sharness sub-tests to ensure they
do not add extra output in the subtests.
Copied from @grondo's commit in https://github.com/flux-framework/flux-core/pull/3379

t0000-sharness.sh: fix test with debug/verbose set in env

---

src/shell/data-staging.cpp
t/t7000-shell-datastaging.t

Problem: when running a job without staging requirements, the shell logs
information that is high-enough level to be printed to the job's stdout
by default:
```
herbein1@4dd0461cee30:/usr/src$ flux mini run -N1 -n1 hostname
0.038s: flux-shell[0]: Jobspec does not contain data-staging attributes. No staging necessary.
4dd0461cee30
```
Solution: change `shell_log` to `shell_debug` to decrease the verbosity
of most messages enough that the datastaging shell plugin does not print
to stdout by default on non-staged jobs:
```
herbein1@4dd0461cee30:/usr/src$ flux mini run -N1 -n1 hostname
4dd0461cee30
```
You can still get access to the logging via a verbose option to the
job shell:
```
herbein1@4dd0461cee30:/usr/src$ flux mini run -N1 -n1 -o verbose=2 hostname
0.032s: flux-shell[0]: DEBUG: 0: …
```

shell: reduce logging verbosity of datastaging plugin

---

src/test/docker/bionic/Dockerfile
src/test/docker/centos7/Dockerfile
src/test/docker/centos8/Dockerfile
src/test/docker/focal/Dockerfile
src/test/travis_run.sh

Problem: flux-core no longer requires user CURVE keys to run Flux,
but flux-sched still generates them in ci scripts.
Drop flux keygen from Dockerfiles and travis_run.sh.

ci: drop unnecessary flux keygen

---

resource/Makefile.am
resource/modules/resource_match.cpp
resource/readers/resource_namespace_remapper.cpp
resource/readers/resource_namespace_remapper.hpp
resource/readers/resource_reader_base.hpp
resource/readers/resource_reader_hwloc.cpp
t/Makefile.am
t/scripts/flux-ion-resource.py
t/t1016-nest-namespace.t

This PR adds basic support for resource Id namespace remapping and solves hwloc GPU ID remapping.  
* Add initial support to aid in remapping resource Id and rank efficiently for nested instances (i.e., `class resource_namespace_remapper_t`)
* Integrate it into the base resource reader class to make it available for all of the reader classes
* Fix incorrect GPU numbering of our hwloc reader using this support
* Modify `sched-fluxion-resource` to establish correct GPU remapping for hwloc reader. The hwloc reader of a nested flux instance discovers the GPU resources using hwloc. However, hwloc uses the logical Id space for each discovered GPU resource, which does not work with GPU affinity at execution time (i.e., `CUDA_VISIBLE_DEVICES`).

Add resource Id remapping support

---

resource/modules/resource_match.cpp
resource/readers/resource_namespace_remapper.cpp
resource/readers/resource_namespace_remapper.hpp
resource/readers/resource_reader_base.cpp
resource/readers/resource_reader_base.hpp
resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
resource/readers/resource_spec_grug.cpp
resource/traversers/dfu_impl_update.cpp
t/Makefile.am
t/scripts/flux-ion-R.py
t/scripts/jsongraph/LICENSE
t/scripts/jsongraph/objects/edge.py
t/scripts/jsongraph/objects/graph.py
t/scripts/jsongraph/objects/multigraph.py
t/scripts/jsongraph/objects/node.py
t/scripts/waitfile.lua
t/sharness.d/sched-sharness.sh
t/t1017-rv1-bootstrap.t
t/t1018-rv1-bootstrap2.t

This PR adds support to use RV1+JGF to populate graph data store.
- Extend the JGF reader to make use of namespace remapper in order
to remap the rank field of all of the resources as well as the Id fields
of the compute core resources.
- Delay creating the reader object within `sched-fluxion-resource` so
that this service can pick the right resource reader type depending
on the condition (e.g., if JGF is embedded in RV1, use the JGF reader.)
- Fetch the job RV1 from the parent if exists and use it in combination
with the RV1 received from core's resource.acquire to remap the
JGF information.
- Add test cases based on nested Flux instances. 
- Add `flux-ion-R.py` which takes in a RV1 JSON as input, generates JGF
and adds it to the `scheduling` key. This is currently a test-aiding internal …

Add support to use RV1+JGF to populate graph data store

---

NEWS.md

This PR updates NEWS.md in preparation for 0.14.0 release.
It assumes that #787 will go in before we tag a release. So please don't merge before #787.

NEWS.md: prepare for 0.14.0 release

---

t/t1017-rv1-bootstrap.t
t/t1018-rv1-bootstrap2.t

Problem: When Travis CI is slow, it can take
a long time for the RV1 output files flushed out.
This leads to a false positive for some of the tests.
Increase timeout by a factor of 2 (20 seconnds)
to avoid the false positive.

testsuite: increase timeout for waitfile to 20 secs

---

qmanager/modules/qmanager_callbacks.cpp
resource/jobinfo/jobinfo.cpp
resource/jobinfo/jobinfo.hpp
resource/utilities/command.cpp
t/t4003-cancel-info.t

Problem: The spelling of "canceled" is inconsistently
used in flux.  Sometimes the British spelling "cancelled" is
used and othertimes the American spelling "canceled" is used.
Solution: Change all spellings of "cancelled" to "canceled".
Fixes #795

Globally standardize spelling of "canceled"

---

.mergify.yml

Problem: the GH action name is `bionic - clang-6.0` but Mergify was
looking for `bionic - clang6.0`.
Solution: change the name in mergify to match the GH action name

mergify: fix referenced test name

---

qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_callbacks.hpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp

Changes per `libschedutil` changes in https://github.com/flux-framework/flux-core/pull/3447
We should wait for changes upstream to be accepted before merging this of course.
These commits could be collapsed into fewer ones if desired.

qmanager: update per libschedutil API changes

---

qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_callbacks.hpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
t/t1013-qmanager-priority.t

Support re-prioritization of pending jobs by adding a prioritize callback through `libschedutil`.
Built on top of PR #801

qmanager: support re-prioritization of jobs

---

qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
resource/modules/resource_match.cpp

This PR adds minor safety enhancements that can work around some issues caused by potentially buggy C++ compilers and/or other unexpected faults. 
- Add pre-check on the input strings that are passed to `std::stoi`
- Add catch-all exception handling for the `sched-fluxion-resource` module scope.

Add minor C++ safety improvements

---

t/scripts/flux-builtin-conf.py
t/t7000-shell-datastaging.t

Use a more foolproof method of discovering the default flux-shell path from the enclosing flux instance in `t7000-datastaging.t`. Without this, `make check` for flux-sched built against a side-installed flux-core may fail since the test could use the flux-shell from the system instance unless PKG_CONFIG_PATH happens to be set appropriately.

testsuite: fix shell path discovery in datastaging test

---

resource/readers/resource_namespace_remapper.hpp
resource/readers/resource_reader_base.hpp

I was looking at the `resource` directory for some example code of the `reader` class and I happened to notice a tiny misspelling of "namespace" in a couple of the `.hpp` files in the directory.
This PR fixes the spelling of "namespace" in **resource_namespace_remapper.hpp** and **resource_reader_base.hpp**.

resource: fix 'namespace' spelling

---

resource/traversers/dfu.cpp
resource/traversers/dfu.hpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/traversers/dfu_impl_update.cpp
resource/utilities/command.cpp
t/Makefile.am
t/data/resource/commands/pruning/cmds01.in
t/data/resource/commands/pruning/cmds02.in
t/data/resource/commands/pruning/cmds03.in
t/data/resource/jobspecs/pruning/test001.yaml
t/data/resource/jobspecs/pruning/test002.yaml
t/data/resource/jobspecs/pruning/test003.yaml
t/t3029-resource-prune.t

This PR adds a bug fix for `by_subplan` pruning. The problem was discovered as I analyzed the performance of Fluxion against the MuMMI workflow @ ORNL Summit.
- Fix the main bug where the pruning filter state was miscalculated, which led to higher numbers of graph visits than necessary: For aggregate-based pruning, `accum_to_parent()` should propagate to the parent resource vertex the amount of resources that will become "unavailable" after each allocation. But code was propagating the new (reduced) available resource amount after the allocation.
- Improve performance by enabling `by_subplan` pruning filter for "headless" jobspecs, the class of jobspecs whose first resource type in the resource section is `slot`. 
- Add graph visit count reporting support into our traverser
- Add tests …

Add bug fix for by_subplan pruning

---

t/sharness.d/flux-sharness.sh

Problem: flux-start options have changed in flux-core
so sharness script for starting an instance is out of date.
Change flux start --size to -s, and drop --bootstrap=selfpmi
which was superfluous anyway.
The flux-core change is proposed in flux-framework/flux-core#3605.  This should be merged first.

sharness: update flux start options

---

configure.ac
src/shell/Makefile.am

Currently, the datastaging shell plugin is being built as a versioned shared library, such that `datastaging.so` is a link to `datastaging.so.0` which is a link to `datastaging.so.0.0.0`. Unfortunately, this means that the current RPM built for flux-sched v0.16 is broken, since only `datastaging.so` was packaged :facepalm:
This PR replaces the unused `shellplugin_ldflags` in `configure.ac` with `fluxplugin_ldflags` from flux-framework/flux-core#3647 and uses it when building the datastaging plugin so that only `datastaging.so` is built.
Fixes #796

datastaging: add -avoid-version to LDFLAGS

---

resource/schema/infra_data.hpp

Fails to compile with gcc@8.3.1 due to a missing header. Here is the log of the error.
```
3 errors found in build log:
355      CXX      traversers/libresource_la-dfu_impl.lo
356      CXX      traversers/libresource_la-dfu_impl_update.lo
357      CXX      policies/base/libresource_la-matcher.lo
358      CXX      readers/libresource_la-resource_namespace_remapper.lo
359    In file included from /var/tmp/bhatia4/spack-stage/spack-stage-flux-sched-0.16.0-mjcdorvmfpxazvekorm3e6if577kzvfn/spack-src/resource/schema/resource_data.hpp:35,
360                     from /var/tmp/bhatia4/spack-stage/spack-stage-flux-sched-0.16.0-mjcdorvmfpxazvekorm3e6if577kzvfn/spack-src/resource/schema/resource_data.cpp:23:
>> 361    /var/tmp/bhatia4/spack-stage/spack-stage-flux-sched-0.16.0-mjcdorvmfpxazvekorm3e6if …
```

bugfix: include missing header (limits.h)

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
resource/hlapi/bindings/c++/reapi.hpp
t/Makefile.am
t/t1019-qmanager-async.t

This PR adds provisional cancel support into the base queue policy layer to fix a cancel race introduced by the FCFS async support PR (PR #826).
Problem: The `sched.cancel` request handling semantics used to be that when a request is received by `qmanager`, the pending job state was deterministic. The job is either pending or not. It is no longer true because there is a *maybe-pending* state: a match request could have been sent out to `sched-fluxion-resource` and the corresponding stream RPC has not been received. Because the mishandling, an intermittent crash occurs. 
Introduce a provisional cancel request queue and handle a request received during the *maybe pending* state when the schedule loop invocation completes.
Fixes Issue #836. I ran `t1009-recovery-multiqueue.t` 30 times on the …

Fix cancel race

---

qmanager/config/queue_system_defaults.hpp
resource/modules/resource_match.cpp
resource/utilities/resource-query.cpp
t/t1005-qmanager-conf.t
t/t1007-recovery-full.t
t/t1009-recovery-multiqueue.t
t/t1010-sync-modules.t
t/t1012-find-status.t
t/t1013-exclusion.t
t/t1016-nest-namespace.t
t/t3027-resource-RV.t
t/t4000-match-params.t
t/t4009-match-update.t
t/t5000-valgrind.t
t/t6000-graph-size.t
t/t6001-match-formats.t

This PR changes the default match policy to "first match" and the default queue-depth to 32. Given that many of the current users require high throughput scheduling and it would make sense the default values are tuned for them. For system-instance, the policies will be configured and set differently through configuration and rc files.
Fixes #827, #830.

Default policy changes

---

.github/workflows/main.yml

Problem: The "fetch annotated tag" step of Github fails on master
because the command  `git fetch -f origin master:master` reports
fatal: Refusing to fetch into current branch refs/heads/master
of non-bare repository
which in turn causes the CI overall to fail.
Skip this step on the master branch
Fixes #847

github: fix ci builds on master

---

README.md
configure.ac
resource/utilities/Makefile.am
resource/utilities/resource-query.cpp
src/test/docker/bionic/Dockerfile
src/test/docker/centos7/Dockerfile
src/test/docker/centos8/Dockerfile
src/test/docker/fedora33/Dockerfile
src/test/docker/focal/Dockerfile

This PR adds support for the editline library
and deprecates the use of GNU readline within
Fluxion.
Editline uses a BSD style license which is
much more compatible with more permissive
licensing including LGPL.
This PR does not yet include new LICENSE
term changes for Fluxion yet because PR #846 
still needs to be merged in before we can do that.
Terms will change in the near future at once
after both this PR and PR #846 will be merged.

Replace GNU readline with editline

---

NEWS.md

Just thought I'd post a first cut at release notes for flux-sched v0.17. I just made a random stab at the release summary.
Feel free to change anything here by directly pushing. Once #850 and this go in we can tag and I'll build RPMs.

NEWS.md: add news item for v0.17.0

---

NEWS.md

We recently tagged flux-core v0.29.0, but there was one API change that required an update to flux-sched, so we'll need a Fluxion release as well.
This PR adds an entry to the NEWS.md for flux-sched v0.18.0. (there was only a that single compatibility change)

NEWS.md: Add release notes for v0.18.0

---

resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_jgf.cpp

Potential fix for #856. Cannot currently compile master version of flux-sched, and instead have compiled 0.16.0 with this change. There is a slight difference between these versions in the readers, but the bug remains the same -- regardless, the change to this particular version is untested. However, to the best of my knowledge, this will ensure that type differences do not prevent compilation on platforms using GCC.

Using static_cast to ensure type compatibility in readers.

---

src/shell/data-staging.cpp

Problem: Future versions of flux-core will require shell plugins
to define FLUX_SHELL_PLUGIN_NAME or the build will fail.
Define FLUX_SHELL_PLUGIN_NAME to "data-staging" and use this to
define the plugin name to prep for this change.

data-staging: define FLUX_SHELL_PLUGIN_NAME

---

t/t7000-shell-datastaging.t

Unfortunately I was lazy and didn't test #864 after application of flux-framework/flux-core#3879. It turns out one of the datastaging tests fails after those changes since now a prefix will appear in the logging output of the shell.
This updates the test to (hopefully) work with or without flux-framework/flux-core#3879.
(This time tested against the changes above)
Sorry!

testsuite: fix logging test in t7000-shell-datastaging.t

---

t/t1001-qmanager-basic.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t

Problem: flux jobspec command is going away, but flux-sched tests are still using it.
Convert to flux mini run --dry-run.

testsuite: use flux mini not flux jobspec

---

README.md

This PR adds LLNL code release number to the main README file. This makes fluxion README more consistent with other flux framework projects.

doc: add LLNL code release number to README.md

---

t/t3301-system-latestart.t

Problem: the flux overlay status interface is changing in
flux core but flux sched is still using the old one
in t3301-system-latestart.t.
Drop the calls to flux overlay status from this test so it
can work with flux-core both before and after the change
proposed in flux-framework/flux-core#3974.
The test is no worse for the wear.

testsuite: drop flux overlay status from test

---

src/test/checks_run.sh
t/t5000-valgrind.t

Problem: The t5000-valgrind.t test is susceptible to false positives
when run on new systems and different distros due to the potential
for new false positives from system libraries which have not yet been
added to the suppressions file. This can confuse new users when the
test unnecessarily fails.
Disable the valgrind test by default to avoid these situations.
The test can be run with FLUX_ENABLE_VALGRIND_TEST (e.g. in CI) or
by passing the `-d, --debug` flag (since this is common when running
the test by hand).

t5000-valgrind.t: do not run valgrind test by default

---

qmanager/modules/qmanager_opts.hpp
resource/planner/planner.h
resource/schema/sched_data.hpp

This PR adds a few compilation issues that were reported against clang-12, clang-13 and gcc-11.
- Use `nullptr` instead of `NULL` within `resource/schema/sched_data.hpp` (Issue with gcc-11 and clang-13);
- Include `stddef.h` to pick up `size_t` for `resource/planner/planner.h` (Issue with gcc-11 and clang-13);
- Drop `const` from one of the class members to use defaulted constructors within `qmanager/modules/qmanager_opts.hpp` (Issue with clang-12 and clang-13).
Fixes Issue #877

Fix compilation issues with clang-12 and gcc-11

---

.mergify.yml

This PR description is adapted from the mergify update commits in flux-core authored by @grondo.
Problem 1: Mergify.io has deprecated the strict merge mode action:
https://blog.mergify.io/strict-mode-deprecation/
Replace the strict mode configuration with a default queue with a rebase action which should be equivalent.
Problem 2: The current mergify config specifies that PRs are merged using a rebase method and not merge. This would result in the PR branch being rebased onto the main branch instead of creating a merge commit, which we use to generate release notes. Luckily, flux-sched branch protection rules prevent the rebase from being completed by mergify.
Change the queue action for PRs to be merge, with an update_method of rebase, which should be similar to the previous 'strict' mode …

mergify: update configuration to replace deprecated keys

---

qmanager/modules/Makefile.am
qmanager/policies/queue_policy_factory_impl.hpp
resource/hlapi/bindings/c++/reapi.hpp
resource/hlapi/bindings/c++/reapi_cli.hpp
resource/hlapi/bindings/c++/reapi_cli_impl.hpp
resource/hlapi/bindings/c/reapi_cli.cpp
resource/hlapi/bindings/c/reapi_cli.h

This PR adds new capability to the Fluxion C/C++ CLI resource HLAPI so that clients such as KubeFlux can initialize a Fluxion context (and maintain it in an external binding).  This PR implements the `match_allocate`, `cancel`, and `info` functions which KubeFlux needs first.  Other HLAPI functions can be implemented in straightforward analogy to the changes in this PR.
Data structures such as `resource_context_t` and `resource_params_t` are defined as in `resource-query` and provide a foundation for the `reapi_cli`.  Note that the implementation of `reapi_cli_info` changes the public API to add a mode argument that returns the job status.
Since the `resource_ctx_t` is created as a raw pointer (as distinct from `resource_query` where it's a `std::shared_ptr`) , a threaded client must be …

HLAPI: add CLI initialization and implement match_allocate, cancel, and info

---

resource/hlapi/bindings/c++/reapi_cli_impl.hpp

Fixed compilation error because <cfloat> was not included.

Replace DBL_MAX with std::numeric_limits

---

t/t1006-qmanager-multiqueue.t
t/t1011-dynstate-change.t

This PR fixes issues seen recently in `t1006-qmanager-multiqueue.t` and `t1011-dynstate-change.t` as discussed in issues #907 and #908.

testsuite: fix a couple brittle tests

---

doc/Makefile.am

Problem: A missing line continuation character in doc/Makefile.am
caused doc/man5/flux-config-sched-fluxion-resource.rst to be
missed from the `make dist` tarball.
Add the missing line continuation to fix the distribution build.
Fixes #914

build: fix missing doc file in distributed tarball

---

resource/readers/resource_reader_hwloc.cpp
t/data/hwloc-data/001N/amd_gpu/rsmi_corona240.xml
t/data/resource/expected/basics/019.2.R.out
t/t4004-match-hwloc.t

Some AMD ROCm SMI GPUs do not appear as type COPROC devices. Instead they are discovered as GPU OSDev type devices with name `rsmiX`. This PR extends the resource hwloc reader to allow these types of devices to be discovered as gpus.
This allows the sched-fluxion-resource module to discover GPUs on the corona system.

resource: support discovery of AMD RSMI GPUs in hwloc reader

---

t/t1016-nest-namespace.t

Problem: resource.get-xml RPC is being deprecated in flux-core,
but the fluxion hwloc reader still depends on it.
Disable sharness tests that fail without this RPC as a stopgap
measure, so flux-core can proceed with removal.
Fixes #925

testsuite: disable hwloc reader tests

---

NEWS.md

This PR adds a NEWS entry for flux-sched v0.22.0 so that we can tag and release today, so that RPMs can be included in the upcoming TOSS 4 release.

NEWS.md: add release notes for v0.22.0

---

resource/modules/resource_match.cpp
resource/readers/resource_reader_grug.cpp
resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
resource/readers/resource_reader_rv1exec.cpp
resource/store/resource_graph_store.hpp
resource/traversers/dfu_impl_update.cpp
resource/utilities/command.cpp
t/data/resource/expected/resource_property/003.R.out
t/data/resource/expected/resource_property/006.R.out
t/scripts/flux-ion-resource.py
t/t3012-resource-properties.t
t/t3027-resource-RV.t
t/t4006-properties.t

Problem: We currently assume that there exits one and only one unique
graph vertex that corresponds to a path. But in various emulation
modes where we run multiple brokers on a single node, this unique path
assumption does not hold: having more than one node vertex with
an identical hostname breaks this assumption. As a result, our reader
code balks at loading our resource graph data store under certain
conditions. The JGF reader will fail to initialize with:
"grow_resource_db_jgf: db.load: error inserting an edge to outedge
metadata map"
Add support so that we can drop the unique path assumption.
- Modify `by_path` graph metadata index to be a map of vector of vertices
instead of a map of vertices. Since this map is keyed by paths, one 
path can have multiple vertices corresponding to …

Don't assume each hierarchical path is unique

---

resource/readers/resource_reader_rv1exec.cpp

Fix error reported by gcc 11.2.0: "comparison of integer expressions of different signedness: 'int' and 'size_t'"
I verified jansson expects `size_t` here:
https://jansson.readthedocs.io/en/latest/apiref.html?highlight=json_array_foreach#c.json_array_foreach

reader: fix index type

---

resource/readers/resource_reader_base.cpp
resource/readers/resource_reader_base.hpp
resource/readers/resource_reader_hwloc.cpp
resource/readers/resource_reader_hwloc.hpp
resource/readers/resource_reader_rv1exec.cpp
resource/readers/resource_reader_rv1exec.hpp
resource/traversers/dfu_impl.cpp
t/t3027-resource-RV.t

This PR adds fixes for the following problems.
With the recently added lonode[x]/hinode[x] match policies, each node's
numeric ID (e.g., node1231 where ID=1231) is used in our score calculation
of all of its containing resource vertices (e.g., cores, gpus...). When its ID
becomes high, however, a type coercion bug can result in an integer
overflow of the score, leading to a undefined behavior. In addition, when
a node's ID becomes even larger such that it can't fit into a signed
32-bit integer, our graph loading fails. While it is less likely we will have
such a huge node ID, it would be ideal to prevent that from happening at all.
-  Use `int64_t` to capure a score within our traverser to match the type
with the rest of the code that is involved in scoring;
- Change `std::atoi` to …

Fix an integer overflow bug etc.

---

qmanager/modules/qmanager_callbacks.cpp
resource/libjobspec/jobspec.cpp
resource/libjobspec/jobspec.hpp
resource/modules/resource_match.cpp
resource/readers/resource_reader_rv1exec.cpp
resource/readers/resource_reader_rv1exec.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/resource-query.cpp
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp
src/python/fluxion/resourcegraph/V1.py
t/Makefile.am
t/data/resource/jobspecs/validation/invalid/attributes_bad_properties.yaml
t/data/resource/jobspecs/validation/invalid/attributes_bad_properties2.yaml
t/data/resource/jobspecs/validation/invalid/attributes_bad_properties3.yaml
t/data/resource/jobspecs/validation/invalid/attributes_bad_properties4.yaml
t/data/resource/jobspecs/validation/valid/attributes_properties.yaml
t/data/resource/jobspecs/validation/valid/use_case_1.8.yaml
t/t1022-property-constraints.t
t/t3027-resource-RV.t
t/t3034-resource-pconstraints.t
t/t8001-util-ion-R.t

This is a WIP PR that adds  property constraints-based matching support.
This builds on a pending PR #921 so don't merge this before landing that  PR.
- Add property support into flux ion-R encode: e.g., `flux R encode -r 0 -c 0-1 -g 0-1 -p "arm-v9@core:0" -H foo2 | flux ion-R encode` is now supported.
- Add properties support into libjobspec in accordance with new property addition to RFC14.
- Add property support within our new rv1exec reader
- Extend our job meta class to capture the property information
- Extend our traverser to use the properties captured in our job meta object to do perform property-based matching
- A bunch of test cases
I want to see if we can land this as part of this month's release? I still need to add a one end-to-end test case using `sched-fluxion-resource`.

Add property constraints-based matching support

---

qmanager/modules/qmanager_callbacks.cpp

Problem: If an alloc request results in a jobspec parse error, the
jobspec string is leaked.
Free the newly created jobspec string in the error path to avoid
the leak.

qmanager: fix potential leak in alloc callback

---

README.md
configure.ac
resource/modules/Makefile.am
src/test/docker/bionic/Dockerfile
src/test/docker/el7/Dockerfile
src/test/docker/el8/Dockerfile
src/test/docker/fedora33/Dockerfile
src/test/docker/fedora34/Dockerfile
src/test/docker/focal/Dockerfile

Problem: The fluxion build system wants libxml and libdl, neither of which appear to actually be used.
Drop these from the build system and update the README.md.
Also, modernize and trim down the "Fluxion Scheduler in Flux" section of the README.md.

build: drop unnecessary preqreqs, update README

---

qmanager/modules/qmanager_callbacks.cpp
t/t1006-qmanager-multiqueue.t

Problem: submitting a job to an unknown queue or failure to insert a job into a queue (an unlikely internal error) cause a fatal job exception with no "note", so the user doesn't get any reason why their job failed.
Add a note to the exception.

add an exception note to fatal queue exceptions

---

t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1014-annotation.t
t/t1019-qmanager-async.t

Problem: flux mini will fail when small durations are specified without units after flux-framework/flux-core#4565.
Add explicit units to flux mini CMD -t where necessary.

testsuite: use explicit duration units

---

resource/policies/base/test/matcher_util_api_test01.cpp

Problem: matcher_util_api_test01 tries to encode a value of 2^32 with jansson "i" which overflows, then the Jobspec yaml parser refuses to parse a negative value.
Encode the value with jansson "I" instead.
Fixes #967

testsuite: fix integer overflow

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/modules/qmanager_opts.cpp
qmanager/modules/qmanager_opts.hpp
t/t1006-qmanager-multiqueue.t
t/t1009-recovery-multiqueue.t
t/t1011-dynstate-change.t
t/t1014-annotation.t

This drops the `default-queue` key from the qmanager configuration since it is now the ingest module's job to assign a default queue if one is configured per RFC 33.  
In addition, update the sharness tests that use queues to include RFC 33 style config in addition to the qmanager config, which should help ease the transition to the new style.

qmanager: drop default-queue configuration

---

t/Makefile.am
t/t1006-qmanager-multiqueue.t
t/t1009-recovery-multiqueue.t
t/t1011-dynstate-change.t
t/t1023-multiqueue-constraints.t

This adds a sharness test with  high level testing for queues with non-overlapping (partitioned) resources.  Nothing too fancy, just ensuring that the scheduler remains responsive when both queues are processing active jobs, a node gets drained, etc..
There's also some test cleanup, enabled by recent flux-core changes.

testsuite: cover queues with non-overlapping resource constraints

---

resource/hlapi/bindings/c++/reapi_cli_impl.hpp
resource/hlapi/bindings/c/reapi_cli.cpp

C++ bindings have an issue where match_allocate doesn't set allocation, reservation or job info correctly. This was done in the C bindings, which is not the right place for it.

Fix REAPI C++ bindings 

---

resource/config/system_defaults.hpp
resource/modules/resource_match.cpp
resource/store/resource_graph_store.cpp
resource/store/resource_graph_store.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu_impl.hpp
t/Makefile.am
t/data/resource/expected/RV/R21.out
t/data/resource/jobspecs/RV/duration3600.yaml
t/data/resource/jobspecs/duration/test001.yaml
t/data/resource/jobspecs/duration/test002.yaml
t/t3027-resource-RV.t
t/t4001-match-allocate.t
t/t4011-match-duration.t

This PR fixes issue #913 by introducing a `graph_duration_t` struct to hold a `std::chrono::time_point` for start and end times into the resource graph metadata and then setting it based on a `resource.acquire` RPC. At schedule time, jobs that specify a `duration` greater than the resource graph duration are rejected. However, jobs with scheduled runtimes that extend beyond the resource graph duration are fit into the resource graph duration procrustean bed.
~~This PR is WIP.~~ First, we need to determine if the procrustean approach complies with updated RFC 14 (https://github.com/flux-framework/rfc/pull/315). Furthermore, we need to consider if the `reader` is the right place for setting the resource graph duration. Beyond that, several items need to be addressed before it can be merged: …

Resource graph duration and job expiration to conform to RFC 14

---

qmanager/modules/qmanager.cpp
t/conf.d/16-multiqueue/sched-fluxion-qmanager.toml
t/conf.d/17-mq-hetero/sched-fluxion-qmanager.toml
t/conf.d/18-mq-override/sched-fluxion-qmanager.toml
t/t1005-qmanager-conf.t
t/t1006-qmanager-multiqueue.t
t/t1009-recovery-multiqueue.t
t/t1011-dynstate-change.t
t/t1023-multiqueue-constraints.t

Problem: fluxion queues are currently configured in the qmanager in the sched-fluxion-qmanager table, but a framework-wide TOML configuration was proposed in RFC 33.
Implement RFC33 queues in the qmanager by transforming the RFC 33 configuration into the old sched-fluxion-qmanager syntax.
Raise an error if queues are configured in the sched-fluxion table instead of in the RFC33-compliant way.

qmanager: support RFC33 TOML queue config

---

NEWS.md

Here are some tentative release notes for 0.25.0 that assume we merge #980.  Feel free to push updates directly to this branch.
I tried building the current master against flux-core 0.43.0 on fluke and  encountered test failures, hence the note about the test suite requiring 0.44.0 or newer.  I didn't investigate deeply, but did note that some tests now use `flux mini CMD --queue` which  was only recently added.  I suspect the scheduler will work fine on older releases but since that has not been tried, I figured the test suite failures were enough to justify that note.

NEWS: add release notes for 0.25.0

---

resource/utilities/README.md

Problem: one of the yaml examples in resource/utilities/README is invalid - it is missing a with: header for a section (and does not load). This fixes it.

fix invalid yaml in resource utilities README

---

t/scripts/flux-tree-helper.py

Problem: The flux.util.OutputFormat class in flux-core will get an improved constructor where `headings` becomes an optional keyword argument, but this will break the PerfOutputFormat class in t/scripts/flux-tree-helper.py
Try the new-style constructor arguments in PerfOutputFormat. If that fails, fall back to the old style so that either works for the flux-tree-helper.py test script.
This PR will need to be merged to avoid a future PR in flux-core from breaking the `flux-tree` tests in flux-sched.

testsuite: update flux-tree-helper.py for new OutputFormat constructor

---

.github/workflows/main.yml

Problem: Using ubuntu-latest in the python-lint and python-format builders causes the check to fail with an error message saying that Python 3.6 cannot be found.
This PR just switches the version of Ubuntu to match flux-core's Ubuntu
version in their python-lint check: 20.04.
----
Just copying what was done in
https://github.com/flux-framework/flux-core/pull/4794
and
https://github.com/flux-framework/flux-accounting/pull/300
hopefully i did it right :P

github: change ubuntu version for python ci

---

t/sharness.d/sched-sharness.sh
t/t1023-multiqueue-constraints.t

Problem: flux-core PR 4776 added the ability for queues to be individually started and stopped.  As an update, starting/stopping all queues with the `flux queue` command now requires the --all option to be specified.  This is not specified in several flux-sched tests, leading to test failures.
Update all callers to specify --all when multiple queues are started or stopped.
***This should not be merged until https://github.com/flux-framework/flux-core/pull/4776 is merged***

testsuite: start/stop all queues with --all option

---

t/t1006-qmanager-multiqueue.t
t/t1009-recovery-multiqueue.t
t/t1011-dynstate-change.t
t/t1023-multiqueue-constraints.t

Problem: In several tests, it is assumed that newly created named queues are "started" by default.  This is not a safe assumption going forward.
Solution: In tests that create named queues, start the queues immediately after they are configured.
This PR is needed to ensure `flux-sched` can pass once PR https://github.com/flux-framework/flux-core/pull/4857 is merged.  It is safe to merge before that PR (and necessary for that PR to pass `flux-sched` tests).

testsuite: do not assume queues started by default

---

qmanager/modules/qmanager.cpp
resource/modules/resource_match.cpp

This PR simply logs the flux-sched version when the qmanager and resource modules are loaded. This can aid users in determining if they've loaded the expected version of Fluxion, and can also be helpful to developers when users report issues.
e.g.
```console
$ flux dmesg | grep version
2023-01-26T18:39:18.234157Z sched-fluxion-resource.info[0]: version 0.25.0-12-gecf20b37
2023-01-26T18:39:18.311059Z sched-fluxion-qmanager.info[0]: version 0.25.0-12-gecf20b37
f(s=1,d=0) grondo@corona82:~/git/flux-core.git$ 
```

report Fluxion version when broker modules are loaded

---

resource/Makefile.am
resource/libjobspec/Makefile.am
resource/libjobspec/constraint.cpp
resource/libjobspec/constraint.hpp
resource/libjobspec/hostlist_constraint.cpp
resource/libjobspec/hostlist_constraint.hpp
resource/libjobspec/jobspec.cpp
resource/libjobspec/jobspec.hpp
resource/libjobspec/parse_error.hpp
resource/libjobspec/rank_constraint.cpp
resource/libjobspec/rank_constraint.hpp
resource/libjobspec/test/constraint.cpp
resource/schema/resource_base.hpp
resource/schema/resource_data.hpp
resource/schema/resource_graph.hpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/resource-query.cpp
resource/utilities/test/benchmark.yaml
t/data/resource/jobspecs/validation/valid/constraints.yaml
t/t1022-property-constraints.t

This PR is a WIP. The current solution almost works, but there is a compilation error discussed on slack in `resource/utilities/resource-query.cpp` due to the addition of a `Flux::resource_model::resource_t` base class.
```
CXX      resource_query-resource-query.o
resource-query.cpp: In function ‘void write_to_graphviz(Flux::resource_model::f_resource_graph_t&, Flux::resource_model::subsystem_t, std::fstream&)’:
resource-query.cpp:319:33: error: conversion from ‘vec_adj_list_vertex_property_map<[...],[...],[...],[...],std::__cxx11::basic_string<char> Flux::resource_model::resource_t::*>’ to non-scalar type ‘vec_adj_list_vertex_property_map<[...],[...],[...],[...],std::__cxx11::basic_string<char> Flux::resource_model::resource_pool_t::*>’ requested
319 |     f_res_name_map_t vmap = get …
```

complete support for RFC 31 Job Constraints 

---

resource/libjobspec/hostlist_constraint.cpp
resource/libjobspec/test/constraint.cpp
t/t1022-property-constraints.t

This PR fixes cases of the resource module returning "Internal match error" when job requests should be "unsatisfiable" and a hostlist constraint is provided. The problem is that the hostlist constraint implementation overwrites `errno`, confusing the resource module which is looking specifically for `ENODATA`.
Fixes #1004

resource: fix 'Internal match error' when hostlist constraint is provided

---

resource/evaluators/fold.hpp
resource/policies/dfu_match_multilevel_id.hpp
resource/policies/dfu_match_multilevel_id_impl.hpp

As reported in issue #1001 `flux mini submit` experiences pronounced slowdown for most of the Fluxion match policies except `first`. With the debugging help of @grondo and @trws we traced one source to an un-inlined accumulate operation. 
Adding the `inline` hint to the function allows the compiler to properly inline it and performance improves by a factor of >100 for all policies except `lonodex` and `hinodex` (or, e.g., `lonode` with `--exclusive -N1`.
Another hotspot we encountered in debugging is the `accumulate` operation in `calc_multilevel_scores`: https://github.com/flux-framework/flux-sched/blob/f7bdcb508d4e93ac880845a40d670c03bebf0306/resource/policies/dfu_match_multilevel_id_impl.hpp#L71
This O(_n_) `accumulate` operation is called for each `finish_vtx`, and even worse, …

Improve Fluxion match performance

---

.github/workflows/main.yml

Problem: we should be able to build the container on request without needing to commit.
Solution: add a workflow_dispatch event to the main workflow.

add workflow dispatch

---

resource/jobinfo/jobinfo.hpp
resource/readers/resource_reader_jgf.cpp
resource/traversers/dfu_impl_update.cpp

Fixes these build errors using GCC 13:
```
In file included from jobinfo/jobinfo.cpp:12:
../resource/jobinfo/jobinfo.hpp:22:25: error: expected ')' before 'j'
22 |     job_info_t (uint64_t j, job_lifecycle_t s, int64_t at,
|                ~        ^~
|                         )
../resource/jobinfo/jobinfo.hpp:26:25: error: expected ')' before 'j'
26 |     job_info_t (uint64_t j, job_lifecycle_t s, int64_t at,
|                ~        ^~
|                         )
../resource/jobinfo/jobinfo.hpp:29:5: error: 'uint64_t' does not name a type
29 |     uint64_t jobid = UINT64_MAX;
|     ^~~~~~~~
../resource/jobinfo/jobinfo.hpp:1:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
+++ |+#include <cstdint>
1 | …
```

Fix build for GCC 13

---

README.md
t/scripts/flux-tree
t/t1001-qmanager-basic.t
t/t1002-qmanager-reload.t
t/t1003-qmanager-policy.t
t/t1004-qmanager-optimize.t
t/t1006-qmanager-multiqueue.t
t/t1007-recovery-full.t
t/t1009-recovery-multiqueue.t
t/t1011-dynstate-change.t
t/t1012-find-status.t
t/t1013-exclusion.t
t/t1013-qmanager-priority.t
t/t1014-annotation.t
t/t1016-nest-namespace.t
t/t1017-rv1-bootstrap.t
t/t1018-rv1-bootstrap2.t
t/t1019-qmanager-async.t
t/t1020-qmanager-feasibility.t
t/t1021-qmanager-nodex.t
t/t1022-property-constraints.t
t/t1023-multiqueue-constraints.t
t/t2001-tree-real.t
t/t3027-resource-RV.t
t/t3034-resource-pconstraints.t
t/t3301-system-latestart.t
t/t4009-match-update.t
t/t4011-match-duration.t
t/t7000-shell-datastaging.t
t/valgrind/workload.d/00-job

This PR replaces the use of `flux mini <cmd>` with `flux <cmd>` in flux-sched.
This will cause the testsuite to fail when run using versions of flux-core <= 0.47.0, but thought I'd go ahead and post the PR in case that is acceptable.

avoid use of deprecated flux mini commands

---

NEWS.md

Problem: the NEWS.md file needs to be updated for v0.27.0
Add notes for this release to NEWS.md.

NEWS.md: add release notes for flux-sched v0.27.0

---

t/t3300-system-dontblock.t
t/t3301-system-latestart.t

Problem: if the number if fields output by 'flux module list' changes, some checks will fail.
Use $NF when grabbing the last field of output with awk instead of hard coding the column number of the last field.
flux-framework/flux-core#5085 proposes to change the output and would break this test.

testsuite: make module list awk less fragile

---

t/t1010-sync-modules.t

Problem: t1010-sync-modules.t calls 'flux module info' to "check if the module is still intact", but this command is for static queries of the module DSO so will always succeed.
flux-framework/flux-core#5085 proposes to remove the info subcommand.
This test seems like it wasn't needed anyway, so just drop it.

testsuite: drop meaningless check

---

Makefile.am
src/common/Makefile.am
src/python/fluxion/Makefile.am

@jan-janssen noticed that the Fluxion `LICENSE` file is currently not included in the distribution tarball created by `make dist`.
Add this and other licenses to `EXTRA_DIST` so that they are included in the distribution.

ensure licenses appear in distribution tarball

---

doc/requirements.txt

Readthedocs CI tests are fail due to an old version of Sphinx. This quick PR Updates the version in `requirements.txt`

Update sphinx version

---

.github/workflows/main.yml
.mergify.yml
.typos.toml
resource/traversers/dfu.hpp

Problem: The current typos workflow check only checks a select number of files because there are so many false positives in flux-sched.
Solution: Add a .typos.toml configuration file to eliminate false positives so we can run the typo check on all of flux-sched.  The config file either skips files with lots of false positives or lists common false positives we wish to ignore.

 Add false positives typos config

---

resource/reapi/bindings/c++/reapi_cli.hpp
resource/reapi/bindings/c++/reapi_cli_impl.hpp

This MR adds functionality to the reapi. 
The new function, `find` is implemented based off of the old find function from resources query and by using the structure many of the other functions from reapi_cli use. It uses a `traverser_find` helper function to performs the actual query then uses a writer to handle the out put. 
This functionality has had some simple tests done using the new resource query tool that uses the reapi, though those changes are not yet ready to be merged into the main repo.

reapi: implement find

---

resource/modules/resource_match.cpp

This changes the behavior a bit, in that it marks *all* ranks known to the database.  The original tried to mark all ranks active in flux, but marked the first N.  The new behavior seems more intuitive, but we may want to change it if we grow or shrink in the future.
fixes #1040

mark all ranks known to graph when "all" is specified

---

t/Makefile.am
t/t1024-alloc-check.t

Problem: there is no test script for ensuring fluxion never allocates the same resources to multiple jobs.
Add a sharness script that utilizes the alloc-check plugin to account for allocated resources and catch errors.  At this point, it just includes an "expected failure" test for #1043.
Note that this PR requires a version of flux-core with flux-framework/flux-core#5304 (just merged). I wanted to get this posted as I saw that @milroy was looking into #1043.

testsuite: add test for double-booking

---

t/t1024-alloc-check.t

Problem: Once flux-framework/flux-core#5319 is fixed, broker ranks will not be drained if the epilog is running when a job is canceled. However, this causes t1024-alloc-check.t to fail since `flux resource undrain 0` will fail.
Don't fail if the undrain of rank 0 fails, so that this test will pass even after fixing the flux-core bug.

testsuite: t1024-alloc-check.t: do not fail if rank 0 not drained

---

NEWS.md

Here are some release notes for 0.28.0 which assume #1046 is merged.  Feel free to push updates directly to this branch.

NEWS.md: add release notes for 0.28.0

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
vscode.md

Problem: We do not yet have a developer environment for flux-sched. More specifically, to easily test the go bindings without needing to build a container, it would be nice to have this. I'm anticipating helping with #1008 and this would be super to have, so I've added an install of go 1.19 to the container.
Solution: Add a .devcontainer setup to flux-sched!

Add development environment

---

.mergify.yml

Rather than listing everything by name in two places, rely on the branch protections in the repo.

mergify: remove rule listing, use branch protection

---

resource/policies/dfu_match_policy_factory.cpp
resource/policies/dfu_match_policy_factory.hpp
resource/utilities/resource-query.cpp
t/t3033-resource-nodex.t

First cut to add a node exclusive first policy.  This seems to work, refactored one of the nodex tests to not be quite so duplicative and test this too.  In cases with no overlapping jobs, firstnodex is the same as hinodex, but it will only look for one match rather than scoring matches.
Need to test the performance, but this should be significantly faster than the other nodex policies.

Add first nodex policy

---

.devcontainer/Dockerfile

Problem: the current development environment (VSCode Development Container) is not using the latest base (jammy) and is missing dependencies python3-yaml and an updated cmake and ninja for building.
Solution: Update Dockerfile to use flux-core jammy and add missing dependencies!
This will be needed for me to test or work on #1062

fix: devcontainer to use jammy and install cmake

---

t/t1001-qmanager-basic.t

Problem: when building against the installed flux-core on a system with flux-coral2 installed, one of the 'make check' tests fails.
A grep for "finish" in a job eventlog succeeds where it failed before because the cray-pals port distributor jobtap plugin posts a prolog-finish event.
Aside: the cray-pals jobtap plugin is loaded by an rc script rather than the config file so that it is present in all instances, not just the system instance.
Use 'flux job wait-event finish' instead of dumping the human formatted eventlog to a file and grepping it.  Note that wait-event exits immediately with an error when the eventlog is complete but the requested event is missing.
Fixes #1073

testsuite: improve test event check

---

src/test/docker/bookworm/Dockerfile

Problem: Github actions build for arm is dying on a nosuid mounted filesystem under the container trying to use sudo
Solution: Set user to root, avoid sudo.  We may want to do this on more Dockerfiles, but it has only showed up in the arm build so far.
This specifically came up here: https://github.com/flux-framework/flux-sched/actions/runs/6189435988/job/16803524042
Apparently overlayfs honors nosetuid in mounts, why this only shows up in the virtualized runner I have no idea but it's easier to fix it this way than try and debug the runners themselves.

docker: avoid sudo in Dockerfile for arm runner

---

.github/workflows/main.yml

Problem: python 3.6 is end of life and is now cauing failures
for the ci pipeline linting and formatting stages.
Change python version to 3.8. Change black version to 22.3.0
to fix formatting error from new click release. This only
affects the ci linting and formatting checks.

ci: style checks change python version from 3.6 to 3.8

---

CMakeLists.txt
debian/control
debian/rules
src/python/CMakeLists.txt

This PR brings back the `make deb` target, which we've been using to build and install packages on test systems.
A `make dist` target, required by `scripts/debbuild.sh`, is added (and is now used by `make distcheck`), and `make dist` is fixed to work with slightly older versions of `git-archive` that do not support the `--add-virtual-file` option. Finally, the build system is forced to `cmake` in `debian/rules` since the fake `configure` script doesn't support all the requisite options.

build: resurrect `make deb`

---

.github/workflows/main.yml

This PR updates to the simpler `softprops/gh-release-action` action to create a release after a tag (as used by flux-core and other framework projects) and also removes the use of `set-output` which has been deprecated for awhile.

ci: remove deprecated syntax and update release action

---

src/test/checks_run.sh

I noticed that the `coverage` build is always reporting `Warning: make check failed, trying recheck in ./t`. Apparently, this isn't because `make check-code-coverage` is failing, but because one of the subsequent `coverage blah` steps is.
Possibly some change in the cmake `check-code-coverage` target is causing one of these steps to fail, or maybe it was always like this for flux-sched. Anyway, this PR just removes some of the post-check coverage steps and makes a couple others optional to avoid the extra unnecessary work of `make recheck`.

ci: fix coverage build

---

resource/traversers/dfu.cpp
t/t4011-match-duration.t

When a resource graph has a fixed duration (i.e. a non-zero expiration), Fluxion currently assigns the graph _duration_ to job requests that do not specify a duration. This results in job expirations that exceed the instance lifetime.
This PR fixes that by adjusting unspecified jobspec durations to the _remaining_ graph duration, instead of the entire graph duration. This results in the expiration of these jobs matching that of the instance.
The existing test that checked this behavior was also updated and fixed.

traverser: fix default job duration when no duration specified

---

resource/modules/resource_match.cpp
t/scripts/dmesg-grep.py
t/t4011-match-duration.t

This PR fixes a couple race conditions in `t/t4011-match-duration.t` which cause the test to fail occasionally.

testsuite: fix a couple race conditions in `t4011-match-duration.t`

---

resource/modules/resource_match.cpp
t/CMakeLists.txt
t/Makefile.am
t/scripts/flux-ion-resource.py
t/scripts/flux-jsonschemalint.py
t/t4012-set-status.t

The motivation for this PR comes from [this flux-coral2 issue](https://github.com/flux-framework/flux-coral2/issues/99). Rabbits can (and very often do) go down, and fluxion needs to avoid scheduling rabbit jobs on dead rabbits. Rabbit status is monitored by HPE software and reported in kubernetes objects, which flux-coral2 software checks. The flux-coral2 software needs a way to report to Fluxion that a rabbit has died (or resurrected).
This PR provides a way to do that. Flux-coral2 can now send a RPC like `sched-fluxion-resource.set_status /path/to/rabbit down` to mark a rabbit as down, and similarly to mark it up.
However, I did notice that marking all the nodes or racks in the resource graph didn't prevent jobs from running, hence the test failures. @milroy do you know whether this is …

Add a set-status RPC for marking vertices up or down

---

NEWS.md

Problem: There are no release notes for v0.31.0.
Add a section to NEWS.md with release notes for v0.31.0.

NEWS.md: add release notes for flux-sched v0.31.0

---

resource/readers/resource_reader_jgf.cpp
resource/schema/resource_data.cpp
t/t3025-resource-find.t

Problem: issue #1121 reported unexpected vertex status behavior when initializing resource graphs from JGF and rv1exec. The `resource_pool_t` ctor is missing the `status` member, which causes the default value of UP to be assigned when the ctor is called upon graph resizing during graph initialization.
Add the `status` member to the ctor to address the problem. 
Edit: the PR doesn't completely address `rv1exec` as that behavior is also due to the default `status` value being `UP`.
The JGF reader doesn't currently scrub the fetcher's `status` member. The missing reset causes vertices that are fetched after one that specifies a `status` in the JGF will inherit that vertex's status.
Add the capability to reset the fetcher `status`.

Fix `resource_pool_t` ctor and JGF reader

---

src/python/fluxion/resourcegraph/V1.py
t/CMakeLists.txt
t/Makefile.am
t/python/pycotap/__init__.py
t/python/t10001-resourcegraph.py

Problem: the FluxionResourcePoolV1 does not support setting
vertex status. However, some resources, such as rabbits, should
be initialized as down, and are only known to Fluxion through
JGF produced by the FluxResourcePool class.
Add a 'status' parameter to the FluxionResourcePoolV1 constructor,
with a default of 'up' to maintain backwards compatibility.
It sounds like there's a chance we'll change the JGF reader's default to 'down' in which case we'd want to change the behavior of the ResourceGraph class as well, I think.

Resource pool status

---

NEWS.md

Problem: There are no release notes for v0.32.0.
Add a section to NEWS.md with release notes for v0.32.0.

NEWS.md: add release notes for flux-sched v0.32.0

---

resource/policies/dfu_match_multilevel_id_impl.hpp
t/CMakeLists.txt
t/issues/t1035-fluxion-reload.sh
t/issues/t1129-match-overflow.sh

In issue #1129 @grondo reported `EOVERFLOW` errors for match requests for thousands of CPUs and GPUs. 
Currently, `calc_factor` computes the tie breaking factor with modular arithmetic. The computation returns -1 when `break_tie` is divisible by `m_multiply_by` (or in other circumstances in modular arithmetic).
The negative value of `tie` causes `std::numeric_limits<int64_t>::max () - tie` to overflow in the following integer check, generating a spurious `EOVERFLOW` errno: https://github.com/flux-framework/flux-sched/blob/3d953e34c8da698276c1ad8e17c14173c36580c5/resource/policies/dfu_match_multilevel_id_impl.hpp#L60
This PR fixes the computation to ensure `tie` is strictly positive by using `abs()`.

Fix overflow in `calc_factor`

---

scripts/debbuild.sh

Problem: Debian based systems may use the 'posix_local' scheme for Python installations, which causes `make deb` to break because the 'purelib' path is returned under /usr/local even when the flux-core prefix is /usr.
Use the workaround described in
https://gitlab.kitware.com/cmake/cmake/-/issues/25113
and set DEB_PYTHON_INSTALL_LAYOUT=deb to fix `make deb`.
There is probably some standard way to actually fix this issue, but since the deb builds are purely for testing at this time, this solution works for now.

debbuild: fix Python purelib paths on Debian systems

---

configure.ac

Problem: autotools borks because it goes looking for a Makefile for the fluxion shell, but support for that was dropped in #1102.
Drop it from the configure script as well.

configure: drop src/shell requirements

---

cmake/GolangSimple.cmake
resource/reapi/bindings/CMakeLists.txt
resource/reapi/bindings/go/src/test/CMakeLists.txt
t/t9001-golang-basic.t

PR #1094 Updated Fluxion to be build as a static library. Some projects like Fluence are clients of Fluxion and its REAPI and need to link Fluxion libraries as shared libraries to preserve license boundaries. This PR adds the capability to build the necessary shared libraries.

Build reapi_cli as a shared library

---

t/t4005-match-unsat.t
t/t4008-match-jgf.t

Problem: there are two tests that have trailing `&&` in the test_debug calls, and when these tests are run with the --debug flag in GitLab CI, they error out.
Remove those trailing ampersands.

testsuite: remove trailing ampersands in tests

---

t/t1023-multiqueue-constraints.t

Problem: some tests presume that only jobs submitted with the 'waitable' flag will contribute to the return value of flux job wait --all, but flux-framework/flux-core#8357 proposes to make all jobs waitable, regardless of the flag.
Ensure that t1023-multiqueue-constraints.t consumes residual wait state before starting the array of waitable jobs.

testsuite: prepare for flux_job_wait(3) change

---

CMakeLists.txt
cmake/FindValgrind.cmake
resource/planner/c++/CMakeLists.txt
resource/planner/c++/Makefile.am
resource/planner/c++/mintime_resource_tree.cpp
resource/planner/c++/mintime_resource_tree.hpp
resource/planner/c++/planner.cpp
resource/planner/c++/planner.hpp
resource/planner/c++/planner_internal_tree.cpp
resource/planner/c++/planner_internal_tree.hpp
resource/planner/c++/planner_multi.cpp
resource/planner/c++/planner_multi.hpp
resource/planner/c++/scheduled_point_tree.cpp
resource/planner/c++/scheduled_point_tree.hpp
resource/planner/c/planner.h
resource/planner/c/planner_c_interface.cpp
resource/planner/c/planner_multi.h
resource/planner/c/planner_multi_c_interface.cpp
resource/planner/test/planner_test01.cpp
resource/planner/test/planner_test02.cpp
resource/traversers/dfu_impl.hpp
t/t5000-valgrind.t

Edit: this PR has grown in scope to enable updates to `planner` and `planner_multi`
To update the Fluxion resource graph, its traverser will need to be reinitialized. The initialization process assembles vectors of resource counts and types via graph traversal to update the `planner_multi` pruning filters. Currently, counts and types are stored as separate vectors in `planner_multi` under the assumption that their order and size don't change. The index of a count must be the same as the index of the corresponding resource type string. This assumption is valid as long as the resource graph is static, but allowing the resource graph to change without updating the planners and their metadata will cause scheduling inconsistency (e.g., incorrect traversal pruning) because of incorrect resource …

Planner comparison and update

---

resource/modules/resource_match.cpp
resource/modules/resource_match_opts.cpp
resource/modules/resource_match_opts.hpp
resource/reapi/bindings/c++/reapi_cli_impl.hpp
resource/schema/resource_graph.hpp
resource/traversers/dfu_impl.cpp
resource/utilities/resource-query.cpp

As reported in issue #1137, the `sched.resource-status` RPC is so slow that Fluxion becomes unusable at large scale (16K simulated nodes).
This PR improves performance by implementing caching of `R all`, `R down`, and `R alloc` payloads. It also improves traversal performance for single-subsystem resource graphs by short-circuiting subsystem selector and edge comparisons.
Note that the search performance improvement applies to `find` searches as well as other traversals like `match allocate`.

Improve sched.resource-status RPC and search performance

---

NEWS.md

Problem: there are no release notes for version 0.33.0.
Add them.

NEWS.md: add release notes for v0.33.0

---

resource/traversers/dfu.hpp

Corrects typo 'becuase' into 'because' in file resource/traversers/dfu.hpp. 
Closes #1154

Corrects typo 'becuase' into 'because'.

---

resource/readers/resource_reader_jgf.cpp
src/python/fluxion/resourcegraph/V1.py
t/python/t10001-resourcegraph.py
t/t8001-util-ion-R.t

Given this vertex in JGF, resource-query reports it has no properties.
```json
{
"id": "35",
"metadata": {
"type": "node",
"basename": "node",
"name": "compute-01",
"id": 1,
"uniq_id": 35,
"rank": 0,
"exclusive": true,
"unit": "",
"size": 1,
"properties": ["pdebug"],
"paths": {
"containment": "/ElCapitan0/rack0/compute-01"
}
}
}
```
```
resource-query> g /ElCapitan0/rack0/compute-01
No properties were found for /ElCapitan0/rack0/compute-01 (vtx's uniq_id=35).
```
Looking at the reader, I found that it expects properties to be given as a mapping with keys the name of the property. When I changed the vertex in JGF to the following, the property was recognized. It looks like the reader had been silently failing on the type.
```json
{
"id": "35",
"metadata": {
"type": "node",
"basename": …
```

reader: fix jgf properties

---

resource/policies/dfu_match_policy_factory.cpp

problem: the firstnodex policy was added and tested, but couldn't be selected by users because it wouldn't be seen as a known policy.
solution: accept the firstnodex value as a known policy in `known_match_policy`

policies: add firstnodex to the known policies

---

resource/traversers/dfu_impl.cpp

Matching jobspecs with node constraints is currently implemented in such a way that the recursive `dom_*` call occurs before constraint checking.
This PR moves the node constraint check within the prune function to prevent unnecessary recursive dom_* calls, speeding up feasibility checks.
The following are comparative performance tests run on a laptop. The following test configuration is used to test without feasibility checking:
```bash
flux config load config.toml
flux module load resource noverify monitor-force-up
flux module load sched-fluxion-resource
flux module load sched-fluxion-qmanager
```
and the following is is contents of `config.toml`:
```toml
[resource]
noverify = true
norestrict = true
[[resource.config]]
hosts = "test[1-16384]"
cores = "0-63"
gpus = "0-8" …
```

Improve match performance with node constrains when feasibility is enabled

---

t/valgrind/valgrind.supp

Problem: valgrind tests fail in some environments where hwloc gpu plguins are installed.
For example it's now failing on my desktop which is Ubuntu 22.04 with libhwloc-plugins-2.7.0-2ubuntu1 installed.
Bring some valgrind suppressions we added in flux-core for this.

testsuite: add valgrind suppressions for hwloc

---

resource/modules/resource_match.cpp
resource/reapi/bindings/c++/reapi_module_impl.hpp
src/cmd/flux-ion-resource.py
t/t4000-match-params.t
t/t6002-graph-hwloc.t

Gathering match data is important for diagnosing performance problems in Fluxion. This PR updates the `stat` RPC topic to respond to flux-core as expected and implements `clear ()` functionality.
Resolves issue #1166.

Update match stats and implement stats-clear

---

CMakeLists.txt
resource/planner/c++/planner_multi.hpp

I realize this is odd timing for this, but it's been sitting for a while, and I keep tripping over myself trying to use interfaces that I know exist but don't in C++14.  IIRC @grondo did a test that we can build with gcc12+ everywhere we care about through the devtoolset to build our RPMs, it would help me a lot if we could finish this through as long as it doesn't cause deployment concerns.
problem: Many interfaces are made more cumbersome or slower by forcing the use of only up to c++14.
solution: As previously discussed, up the required C++ standard to 20 since we have devtoolset gcc everywhere that can compile to that standard.

up the required C++ standard to 20

---

t/python/subflux.py
t/python/t10001-resourcegraph.py

Problem: t10001-resourcegraph does not run under flux by default, leading to test failures when the flux package cannot be imported.
Add a script for running Python tests under flux and make t10001 use it.
Fixes #1172.

test: run t10001 under flux

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/base/queue_policy_base_impl.hpp
t/t1024-alloc-check.t

problem: The "remove" method was used for both handling the `free` and `cancel` RPCs. Under some code paths, remove de-allocates resources, so using it for a pending cancellation, even if it seems to be protected by checks, is unnecessarily dangerous.  Given the recent double-booking issue and a lack so far of other theories on how we get there, this is a possible culprit.
solution: Re-factor queue_policy_base_t remove into remove and remove_pending, the latter of which only operates on the pending states and has no code-paths that can result in a resource.cancel RPC being sent.  The remove_pending is used for both the cancel RPC and the part of the free RPC where the code was used before, should be a pure refactor.

qmanager: split remove to separate pending

---

.typos.toml
CMakeLists.txt
CMakePresets.json
cmake/sanitizers-cmake/.gitignore
cmake/sanitizers-cmake/CMakeLists.txt
cmake/sanitizers-cmake/LICENSE
cmake/sanitizers-cmake/README.md
cmake/sanitizers-cmake/cmake/FindASan.cmake
cmake/sanitizers-cmake/cmake/FindMSan.cmake
cmake/sanitizers-cmake/cmake/FindSanitizers.cmake
cmake/sanitizers-cmake/cmake/FindTSan.cmake
cmake/sanitizers-cmake/cmake/FindUBSan.cmake
cmake/sanitizers-cmake/cmake/asan-wrapper
cmake/sanitizers-cmake/cmake/sanitize-helpers.cmake
cmake/sanitizers-cmake/tests/CMakeLists.txt
cmake/sanitizers-cmake/tests/asan_test.cpp
cmake/sanitizers-cmake/tests/shortest.ext.test.cpp
cmake/update-sanitizers-cmake.sh
resource/CMakeLists.txt
resource/libjobspec/CMakeLists.txt
resource/planner/c++/CMakeLists.txt
resource/planner/c/CMakeLists.txt
resource/planner/test/CMakeLists.txt
resource/policies/base/test/CMakeLists.txt
resource/utilities/CMakeLists.txt

What it says on the tin, adding support for using sanitizers so we can leverage those to find issues with fluxion.  Also adds a first copy of a CMakePresets.json file so we can have a common set of known build and test configurations that we can all share.  For now this is just default and asan, but I think others could be worthwhile.

Add sanitizers

---

resource/modules/resource_match.cpp
t/issues/t1182-exclude-with-down-ranks.sh

This PR fixes #1182 and adds a test for the condition (verified that the test fails on current master).
This is a critical issue since currently Fluxion could assign down resources to jobs. The jobs then immediately fail and the next job is scheduled, eating through the entire queue.

resource: ensure all resources start in DOWN state when some ranks are excluded by configuration

---

qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
resource/modules/resource_match.cpp
t/t1006-qmanager-multiqueue.t

Problem: several log messages are not helpful and decrease the signal to noise ratio in the Flux log buffer in a large Flux instance.
Eliminate logging of:
- alloc success/denied/canceled
- free success
- resource-status success
One test had to be reworked a bit to not rely on these log messages.
Fixes #1185

reduce unnecessary logging

---

doc/CMakeLists.txt

problem: manpages rebuild on every invocation of the build
solution: remove the accidental ALL from the add_custom_command for manpages, that was causing cmake to constantly rebuild them trying to create a file named "ALL"

docs/cmake:stop constantly rebuilding manpages

---

.github/workflows/main.yml
NEWS.md

This PR attempts to update all deprecated actions in `workflow/main.yml`. 
As part of the update, the codecov uploader is updated from the bash version to the most recent action uploader. Be aware that this requires that `CODECOV_TOKEN` be set in the environment of the action (where I don't think the bash uploader did). The main repo gets this from the organization secrets, but if you have a personal fork, you'll have to set the `CODECOV_TOKEN` secret to continue getting codecov uploads to your user org in codecov.
We'll see how this works in a PR here...

ci: update deprecated github actions

---

resource/modules/resource_match.cpp
src/cmd/flux-ion-resource.py
t/t4000-match-params.t

Performance testing with Fluxion has revealed the need to save and output data on failed matches. This PR updates the resource module to track and report these stats.

Update stats output to include data for failed matches

---

src/test/docker/docker-run-checks.sh

problem: docker-run-checks.sh currently assumes that mounting $HOME to /home/$USER will match the outer system. Sometimes that is not the case. Example, my lima-managed vm uses /home/$USER.linux as the home directory for the vm user, which causes strange errors because of the mismatch.
solution: map $HOME to $HOME

docker-run-checks: ensure we match user's home

---

CMakeLists.txt

problem: cmake was looking for the version file in the build directory rather than the source directory, causing it not to be found in some common configurations.
solution: have it look in the source directory instead

cmake: look for ver file in source directory

---

NEWS.md

Problem: there are no release notes for v0.34.0.
Add them.

NEWS.md: add release notes for v0.34.0

---

qmanager/policies/base/queue_policy_base.hpp
resource/modules/resource_match.cpp
t/t4013-unreservable.sh

problem: if a job is pending and moved into the blocked state, it isn't removed by cancel
solution: if the job is not found in pending, try to remove it from blocked
As a note, I remember writing this logic at some point in the previous PR that added m_blocked.  I don't know when it got lost, but probably when a few other similar searches that we actually don't want got removed.  The job is now cancelled appropriately in this case at least.
fixes #1208

qmanager: search blocked jobs during pending removal

---

t/t6001-match-formats.t

problem: somehow we've had an invalid jq command in one of the sched tests for quite some time now
solution: give it the "." pattern rather than ""
This is actually in one of the commits in #1211, but it's driving me crazy not having this fixed in other branches.

test/match-formats: make jq command valid

---

resource/CMakeLists.txt
resource/modules/resource_match.cpp
resource/schema/perf_data.cpp
resource/schema/perf_data.hpp
resource/traversers/dfu.cpp
src/cmd/flux-ion-resource.py

Match performance variability observed on a large cluster has pointed to the need for storing and reporting jobids corresponding to the max succeeded and failed math times. This WIP also adds the capability to report the number of `select` iterations performed for the jobid corresponding to the max match times.
This PR is WIP as the current implementation for passing the iteration count may not be desirable.

Add jobid and schedule iteration count to match stats; make perf a global variable

---

.clang-format
.gitignore
qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
qmanager/policies/queue_policy_fcfs.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
src/test/checks_run.sh
t/t4013-unreservable.sh

fixes #1210
This is a bit of a big one, and may benefit from having each commit reviewed separately.  If anyone prefers a stacked push I can do that.
The main changes here are:
* Jobs that are determined to be blocked, cannot be reserved, do not count toward the queue_depth.  This means if there are 1000 blocked jobs, and two at the end, we will consider 1002 jobs even if the queue_depth is only 32. The observed behavior is substantially better than otherwise however, because it means we should always make progress on work that can run, where before the two jobs at the end would block forever if the 1000 blocked jobs stay blocked forever.
* The qmanager's backfill implementation now re-enters the reactor after processing a certain number of matches while leaving the scheduling loop …

qmanager: always process unblocked jobs and make bf reactive during sched loop

---

qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_fcfs.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
resource/reapi/bindings/c++/reapi.hpp
resource/reapi/bindings/c++/reapi_module_impl.hpp
src/test/docker/focal/Dockerfile

This isn't a _major_ performance issue, but we had been using a vector as a map key for a static set of 3 elements, casted to doubles for some reason, in qmanager.  This means every time we did a lookup, we did at least one, probably more like three, heap allocations and frees.  It made me twitch every time I saw it, so this refactors that out in favor of a simple struct with defaulted comparison operators and a method to construct it with the appropriate values in the job_t type.

avoid using std::vector as a map key

---

qmanager/policies/base/queue_policy_base.hpp
t/t1013-qmanager-priority.t

problem: if a job in reserved state, still pending in qmanager, gets reprioritized it's possible that it could unblock a job in the blocked queue and without doing a reconsideration it's possible we could get a priority inversion
solution: reconsider blocked jobs when a pending job is reprioritized
I have yet to make a reproducer that reliably needs this, but I'm pretty sure if we can do this sequence it will happen:
1. start a long-running job that uses a node
2. enqueue a high priority job that requires one of the resources used by the first so that it's reserved
3. enqueue a lower priority job that could run immediately, but wont because it's blocked by the reservation
4. reprioritize the reserved job to have a lower priority than the third

qmanager: reconsider blocked jobs on reprioritize

---

qmanager/policies/base/queue_policy_base.hpp

problem: we should always reconsider the queue, run the sched loop, when reconsidering blocked jobs. In some corner cases we did not because they are merged directly rather than being inserted individually.
solution: explicitly set schedulable.
PR redone from #1223 because of branching issue.

qpolicy/base: schedulable on reconsider

---

resource/policies/base/matcher.cpp

problem: the ALL resource type in the pruner specification was including the type of the anchor vertex, so in common uses like "ALL:core" all core vertices allocate a planner to track the number of cores they contain
solution: if the anchor and the target type match, don't track it
This saved roughly 600MB with a 16k node graph with 64 cores per node.  Also kinda trivial.  Looking for other low-hanging fruit.

pruner: don't track own type for pruning

---

resource/evaluators/expr_eval_vtx_target.cpp
resource/evaluators/expr_eval_vtx_target.hpp
resource/modules/resource_match.cpp
resource/policies/base/dfu_match_cb.cpp
resource/policies/base/dfu_match_cb.hpp
resource/policies/dfu_match_locality.cpp
resource/policies/dfu_match_locality.hpp
resource/policies/dfu_match_multilevel_id.hpp
resource/policies/dfu_match_multilevel_id_impl.hpp
resource/policies/dfu_match_var_aware.cpp
resource/policies/dfu_match_var_aware.hpp
resource/reapi/bindings/c++/reapi_cli.hpp
resource/reapi/bindings/c++/reapi_cli_impl.hpp
resource/schema/data_std.hpp
resource/schema/resource_graph.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu.hpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/utilities/README.md
resource/utilities/command.cpp
resource/utilities/command.hpp
resource/utilities/resource-query.cpp
resource/utilities/test/resource-bench.sh
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp

The filtered_graph buys us basically nothing, but it costs order 30%-80% depending on the operation and how we measure.  I need to run a performance study with and without, but for production cases it should always be a win, and it reduces compile times.  It's most noticeable with the many-time-point test such that there's a _ton_ of matches, but it should make at least a small difference everywhere.
This is stacked on top of #1224 because without it, this change made the race condition much more common and frequently hung one or more tests.
As part of routing out the filtered-graph types, I removed a number of "shared_ptr" arguments.  Overall my intention is that no regular pointer type argument should ever _own_ storage, but we can pass things by pointer when just sharing a reference to …

Excise filter

---

resource/schema/perf_data.hpp

The current calculation of average match times uses the total job count rather than the job count since last reset.
Use the correct count to compute the average (hence downstream calculations, too).

Fix match average calculation

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
resource/modules/resource_match.cpp
resource/reapi/bindings/c++/reapi_module_impl.hpp
t/t1004-qmanager-optimize.t

This is a replacement for #1226, though it doesn't yet have eager cancellation of the sched loop to immediately process job cancellations. The short version is that this makes our backfill queues completely asynchronous with respect to the resource module, and deals with the 10,000 allocs followed by 10,000 cancels test in about 45 seconds on my laptop. Assuming the numbers are comparable, that's a bit under 100x faster than the time @milroy reported for the test in #1222.
This also _completely_ changes the performance profile of flux under this kind of load.  During a flood of requests like that, match still shows up as something like 30%, but that's all.  The job-injest and qmanager modules rise to almost match it for consumption, and the yaml processing becomes a meaningful cost.  May …

qmanager: Asynchronously communicate with resource in the scheduling loop to allow job updates while matching

---

.github/workflows/main.yml

This is a rough one, no clue how we got along this far without it, maybe because the same thing runs on core it's actually just refreshing the correct manifest, not sure. Either way this should be a priority CI fix.
problem: somehow we've been updating the core manifest rather than the sched one, and either not hurting anything or not noticing, not sure which.  Either way, not great.
solution: actually push flux-sched's manifest

github-actions: actually push the flux-sched manifest

---

qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
t/t1019-qmanager-async.t

problem: The sched loop can take a long time to receive new updates like cancellations and reprioritize.
solution: Cancel the sched loop either immediately or when the current iteration is done to allow those to proceed when a cancel, reprio or free has been received.

qmanager: restart the sched loop on updates

---

resource/store/resource_graph_store.cpp
resource/store/resource_graph_store.hpp
resource/traversers/dfu.cpp
resource/traversers/dfu.hpp
resource/traversers/dfu_impl_update.cpp

problem: When a large number of possible time points exist, unreservable jobs cause N matches where N is the number of time points. This makes jobs that can't be matched potentially very expensive, and heavy use of constraints make the case common.
solution: iterate over just the node vertices checking for constraint matches, whether they are UP and whether it's possible to allocate them (either at the end of time, or in the case of allocate immediately). If all of those pass, the node is deemed "feasible" and counted. If less nodes are feasible than are required by the request, it's immediately rejected.
In a test with 300 time points, without this patch I get between 5 and 7.5 seconds for each failing match. With this patch the failed match stats in the same test report a minimum of …

dfu: add a quick-to-test feasibility precheck to match

---

NEWS.md

Problem: there are no release notes for v0.36.0.
Add them.
Waiting on #1232 and #1236.

NEWS.md: add release notes for v0.36.0

---

resource/traversers/dfu.cpp
resource/traversers/dfu_impl.cpp

problem: a few places were using `&(vec[0])` to get an address of the start of a potentially empty vector.  This is almost always actually safe in practice, but it's not allowed and technically could be treated like a null dereference as well.
solution: use the `vec.data()` method that exists specifically for this purpose
@milroy tagging you here since we happened to be talking about this code just the other day.  As far as I know this hasn't been touched recently, but maybe the hardening flags in the buildfarm did. 🤷

planner/dfu: avoid dereferencing empty vector

---

NEWS.md

Problem: there are no release notes for v0.36.1.
Add them.

NEWS.md: add release notes for v0.36.1

---

src/cmd/flux-ion-resource.py

Problem: a subcommand "func" is always required for ion resource, yet the current client spits out an error if the user types the command without help, subcommand, or other args.
Solution: if the func (subcommand) is missing, print the parser help and provide a meaningful message to the user.
I am starting to test out flux ion-resource (to learn about interaction with fluxion and the queue manager) and very naively I built and ran the command and saw this:
```bash
$ flux ion-resource
```
```console
Traceback (most recent call last):
File "/usr/libexec/flux/cmd/py-runner.py", line 94, in <module>
runpy.run_path(sys.argv[0], run_name="__main__")
File "<frozen runpy>", line 291, in run_path
File "<frozen runpy>", line 98, in _run_module_code
File "<frozen runpy>", line 88, in _run_code
File …
```

ion-resource: add meaningful error message when subcommand is missing

---

resource/traversers/dfu_impl.cpp

When `ALL` is specified for prune-filters of a leaf vertex type, other leaf vertices maintain a pruning filter for that resource type. For example, the default `ALL:core` adds `core` filters to `gpu` vertices. Since a leaf vertex is the terminus of a depth-first search of a single-subsystem graph, the extra pruning filters increase memory consumption unnecessarily.
Add a check that exits the pruning-filter priming function for leaf vertices.

Don't add pruning filter for leaf vertices

---

src/test/docker/docker-run-checks.sh
src/test/generate-matrix.py

This one is slightly urgent.  None of our CI runs will pass on EL8 until this is dealt with, fallout from rebuilding the fluxrm/testenv image on el8 is it picked up a newer valgrind, which changed the python environment on the system in a way that interacts badly with the older cmake in there.
problem: upstream el8 has added a new version of valgrind, which pulls in python3.11. The older cmake logic on el8 finds the newer python but fails to find any development dependencies for it and errors out.
solution: force cmake to use the system python3.6, it must be an absolute path as well for some reason

matrix: add explicit python path for el8

---

src/cmd/flux-ion-resource.py

Problem: the flux-ion-resource.py match has several subcommands that require a jobspec positional argument. Each subparser is calling the same logic to add it, which is redundant. 
Solution: iterate through a list to add the same argument to all of them, eliminating the redundancy and making it easier for the developer to read.

chore: flux ion-resource jobspec argument redundancy

---

resource/traversers/dfu.cpp

When diagnosing a recent scheduling problem, the `max-match-iters` count was observed to remain at its default value:
```json
"succeeded": {
"njobs": 323,
"njobs-reset": 323,
"max-match-jobid": 499941450105867264,
"max-match-iters": -1,
"stats": {
"min": 0.001378509,
"max": 6.2174810100000002,
"avg": 1.9132730813622281,
"variance": 2.3300616684658966
}
},
```
This early return can prevent the count from getting updated: https://github.com/flux-framework/flux-sched/blob/7f0105fcbcb3173be4d105d7ffabb6fa633e58f6/resource/traversers/dfu.cpp#L155
This PR fixes the behavior with a `goto` to jump to the end of `schedule` and set `perf.tmp_iter_count`.

traverser: set iter count when request_feasible returns < 0

---

.github/workflows/main.yml

problem: in CI we can't see what formatting was changed by the hooks
solution: add the `--show-diff-on-failure` flag so we can see what happened in case it doesn't repro easily elsewhere

pre-commit: show diff on failure

---

cmake/sanitizers-cmake/cmake/sanitize-helpers.cmake
resource/evaluators/test/CMakeLists.txt
resource/libjobspec/CMakeLists.txt
resource/schema/data_std.hpp
resource/schema/test/CMakeLists.txt
src/common/libintern/CMakeLists.txt
src/common/libintern/interner.cpp
src/common/libintern/interner.h
src/common/libintern/interner.hpp
src/common/libintern/test/interned_string_test.cpp
src/test/checks_run.sh
t/sharness.d/sched-sharness.sh
t/t1017-rv1-bootstrap.t
t/t1018-rv1-bootstrap2.t
t/t3027-resource-RV.t

problem: while subsystems are a very small stable set that users don't
produce input for, resource types are both dynamic and often coming from
untrusted user input, so immortal strings would mean a potential attack
vector for resource exhaustion.
solution:
1. Refactor the interned_string type to accept a "storage" class,
that provides the actual mechanism for interning. This changes our
immortal strings as well by caching the address of the relevant table
for quick lookup during interning and reducing our lock acquisitions.
A `dense_storage` intern string stores an integer in the range
0-num-strings in its group, with the group identified by a tag type,
largely like before but a bit more ergonomic for use in a large
project.
2. Add a new rc_storage backend that stores a …

interner/res_type: add a refcounted backend for interned strings

---

qmanager/modules/qmanager_callbacks.cpp
qmanager/policies/base/queue_policy_base.hpp
qmanager/policies/queue_policy_bf_base.hpp
qmanager/policies/queue_policy_bf_base_impl.hpp
qmanager/policies/queue_policy_fcfs.hpp
qmanager/policies/queue_policy_fcfs_impl.hpp
resource/modules/resource_match.cpp
resource/traversers/dfu_impl_update.cpp
t/issues/t6179-flux-core-housekeeping.sh

Recently, a large job on a large system was considered allocated by Fluxion, but was complete and released in flux-core (https://github.com/flux-framework/flux-core/issues/6179). The proposed solution was to amend RFC 27 to include an optional "final" boolean flag in the `.free` RPC. That flag can be used by Fluxion to determine if there is an allocation state discrepancy between flux-core and sched and take action based on that information.
This PR adds support to handle the optional "final" flag in the `.free` RPC. ~The current implementation only logs an error when a state discrepancy is detected, but doing a full cancellation of the job would be a straightforward addition to this PR.~ After further thought, executing a full cancel when a discrepancy exists between flux-core and -sched …

Support and handle optional "final" flag in .free RPC

---

qmanager/modules/qmanager.cpp
resource/modules/resource_match.cpp

This simple PR just brings flux-sched into line with the recent addition of the `feasibility` service for handling satsifiability requests in RFC 27.
For now, both the old `sched.feasibility` and `feasibility.check` RPCs are supported so that Fluxion can continue to work with existing flux-core which doesn't yet support `feasibility.check`.
The long term plan I think is to run `feasibility` as a separate module, so this is just a stopgap until that time.

update satisfiability RPC to conform with RFC 27

---

.github/workflows/main.yml
.pre-commit-config.yaml
.ruff.toml
CMakeLists.txt
README.md
debian/control
resource/CMakeLists.txt
resource/readers/resource_spec_grug.cpp
resource/readers/resource_spec_grug.hpp
resource/utilities/CMakeLists.txt
resource/utilities/grug2dot.cpp
resource/utilities/resource-query.cpp
resource/utilities/rq2.cpp
src/common/libintern/interner.hpp
src/test/checks_run.sh
src/test/docker/docker-run-checks.sh
src/test/docker/el8/Dockerfile
src/test/docker/el9/Dockerfile
src/test/docker/fedora34/Dockerfile
src/test/docker/fedora38/Dockerfile
src/test/docker/fedora40/Dockerfile
src/test/docker/noble/Dockerfile
src/test/generate-matrix.py
t/python/t10001-resourcegraph.py
t/scripts/flux-jsonschemalint.py
t/scripts/run_timeout.py
t/scripts/y2j.py

This is meant to solve a variety of build and CI issues we're facing, and also bring our requirements more up to date.  We actually barely need any built boost components anymore, so I'm removing them.  We may go the rest of the way, will consider it, but for now it's regex, system and filesystem that are all removed. 
This also explicitly checks compiler versions, note that the default initial gcc and clang for jammy fell off the back _but_ both gcc12 and clang15 are available in standard jammy apt repos, and in fact we had clang-15 pre-installed, so no change to OS requirements.  Since cmake was already checking for minimal C++20 support, this actually checks for explicit versions of gcc and clang, with an escape hatch to build with whatever.  The code currently builds, barely, with …

Update build and ci to enforce compiler versions, bump to C++23, remove vestigial deps, and generate images matching core

---

cmake/config_testing.cmake
qmanager/modules/qmanager_callbacks.cpp
resource/utilities/test/resource-bench.sh
src/test/docker/alpine/Dockerfile
src/test/generate-matrix.py
t/scripts/strerror_symbol
t/t1005-qmanager-conf.t
t/t1024-alloc-check.t
t/t3301-system-latestart.t

This is stacked on top of #1272 and #1273 and adds support for alpine linux on amd64 and arm64, with the attendant ci updates.  This also actually surfaced a very, very hard to repro bug in the jansson code I added for qmanager, so I'm seeing this as pretty useful right now.
(note that most of the changes in the diff are due to the stacking, it's just the alpine commit that's new here)

Resolve issues with Alpine linux and build release containers for amd64 and arm64

---

src/test/docker/docker-run-checks.sh

problem: the install-only checks were accidentally running checks instead of only installing
solution: export the INSTALL_ONLY variable so it propagates appropriately
This is a bit of a facepalm mistake.  It only actually causes a failure on the arm runners because they run out of time.

docker-run-checks: export INSTALL_ONLY

---

qmanager/modules/qmanager.cpp
resource/modules/resource_match.cpp
t/t1020-qmanager-feasibility.t
t/t3301-system-latestart.t

This PR fixes a typo identified in https://github.com/flux-framework/flux-core/pull/6223, changes feasibility service registration to occur before the module is forced to the running state, and fixes one test that used a deprecated `flux job-validator` option.
I apologize for the noise. This version has indeed had some testing against the pending flux-core changes. :facepalm:

move feasibility service into sched-fluxion-resource and fix associated test

---

resource/modules/resource_match.cpp

Problem: There are many cases in the testsuite where the Fluxion resource module is loaded alongside sched-simple for testing, but this currently fails because these two modules now conflict due to the feasibility service.
Since feasibilty is an optional service, and may soon move to a separate module anyway, make feasibility service registration optional.

resource: make feasibility service registration optional

---

qmanager/policies/base/queue_policy_base.hpp

problem: The shared pointer for the job_t gets released before the cancel call, causing a potential use-after-free if the job isn't held by another queue at the time.
solution: take a reference to the shared_ptr before erasing it from the m_jobs map

qmanager: fix lifetime issue in partial release

---

.pre-commit-config.yaml
scripts/build-matrix

problem: we have good scripts for running in our images locally, but not always with all the same flags as in CI
solution: add a script, build-matrix, that takes a name from the actions build matrix and runs docker_run_checks with the same flags as that matrix entry

scripts: add build-matrix script to ease matching ci

---

NEWS.md

Problem: there are no release notes for v0.38.0.
Add them.

NEWS.md: add release notes for v0.38.0

---

CMakePresets.json
resource/utilities/resource-query.cpp

problem: we're indexing the graph with an end iterator for vertices, which is invalid, instead of the current iterator for the edge we need
solution: use the correct iterator
fixes #1289
Also, this adds a new cmake preset called "rpm" to build with the site flags used by the build farm.

resource-query: fix segfault in graphml writer

---

CMakeLists.txt

Problem: flux-sched's version comes from `git describe`, which is passed to CMake. CMake validates versions using a regex in [`CMake/Source/cmProjectCommand.cxx`](https://github.com/Kitware/CMake/blob/a53e8e4e81d66be262dd01bba6555e2080794652/Source/cmProjectCommand.cxx#L238). When this is an invalid version, flux-sched can't build. This often happens in CI, forks, or stripped-down user environments, and often happens to new contributors.
Solution: Validate the version before passing to CMake. If the version is invalid, throw a descriptive warning with some suggestions.
Fixes #1291
This might be a little over-engineered, and suggestions about how to format the message are welcome.

build: add descriptive warning about version

---

resource/libjobspec/jobspec.cpp
resource/modules/resource_match.cpp
resource/schema/data_std.cpp
resource/schema/data_std.hpp
resource/utilities/command.cpp
resource/utilities/resource-query.cpp
src/common/libintern/interner.cpp
src/common/libintern/interner.hpp
src/common/libintern/scope_guard.hpp
t/data/resource/expected/satisfiability/002.R.out
t/data/resource/jobspecs/basics/bad_res_type.yaml
t/t4001-match-allocate.t

I'm still debating this change to be honest.  The refcounted strings for resource types are showing up as a meaningful cost in comparisons and refcounting, it's not terrible but it's also not great.  This solves the issue by making it so that dense storage interners have a notion of being "final" or placed in a state where new strings can't be added anymore. It also adds an interface to "open" a finalized interner for updates, on a per-thread basis, so that we can do things like database updates. To my surprise, this passed all but one of our tests without re-opening the interners, and that last one by re-opening them in update_resource.
The upside is that after this change, and without using it to optimize any of the type maps or anything like that, we get another 20-30% improvement in …

Dense resource type with DoS protection

---

resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
src/python/fluxion/resourcegraph/V1.py
t/python/t10001-resourcegraph.py
t/t1018-rv1-bootstrap2.t
t/t8001-util-ion-R.t

Posting this as a WIP so I can link to it / work against it in flux-coral2.

JGF simplification

---

NEWS.md

Problem: there are no release notes for v0.39.0.
Add them.
Depends on:
@zekemorton @milroy @trws anything else we should get in by tomorrow?

NEWS.md: add release notes for v0.39.0

---

resource/readers/resource_reader_rv1exec.cpp
t/CMakeLists.txt
t/rc/rc1-job
t/rc/rc3-job
t/sharness.d/sched-sharness.sh
t/t1026-rv1-partial-release.t

This PR fixes resource cancel with rv1exec when there is more than one entry in the Rv1 `R_lite` array. 
Currently for _every_ resource free request (whether a "partial" cancel or not) where not all ranks have the same set of cores or gpus allocated, users will see these nuisance error message in their logs:
```
sched-fluxion-qmanager[0]: remove: Final .free RPC failed to remove all resources for jobid 228417863981989888: Success
sched-fluxion-qmanager[0]: jobmanager_free_cb: remove (queue=default id=228417863981989888): Protocol error
```
Since my home cluster has a differing number of cores between nodes, I get these errors for almost every job.
The issue is that while `resource_reader_rv1exec_t::partial_cancel_internal()` loops over the entries in `R_lite`, it doesn't accumulate the …

readers: fix rv1exec cancel with multiple entries in `R_lite` array

---

resource/readers/resource_reader_jgf.cpp

Problem: if a vertex's ID is -1 in JGF, the reader will supply it with a default value. However, sometimes -1 is desired.
Do not replace an ID of -1 with a default value when reading in JGF. Instead use -2 as the signpost that no ID was supplied.
Fixes #1303

readers: allow id of -1 in JGF

---

src/test/generate-matrix.py

problem: we're not hooking up to the el8 container from core properly
solution: tag the container after the test, and match the core container with test-install
This is meant to match with #flux-core/6401 and ensure we propagate the el8 container all the way through.

matrix: add el8 tag and make it test-install

---

qmanager/policies/base/queue_policy_base.hpp
resource/planner/c/planner_multi_c_interface.cpp
resource/traversers/dfu_impl_update.cpp
t/CMakeLists.txt
t/data/resource/jgfs/issue1284.json
t/data/resource/jobspecs/issues/issue1284-noslot.json
t/data/resource/jobspecs/issues/issue1284.json
t/t1027-rv1-partial-release-brokerless-resources.t

Issue #1284 identified a problem where rabbits are not released due to a traverser error during partial cancellation. The traverser should skip the rest of the `mod_plan` function when an allocation is found and `mod_data.mod_type == job_modify_t::PARTIAL_CANCEL`. ~This PR adds a `goto` statement to return `0` under this circumstance.~ This PR is significantly updated in scope to reflect more comprehensive understanding of the problem.
This line is causing some of the errors reported in the related issues:  https://github.com/flux-framework/flux-sched/blob/996f999c9bc398845f91ea58851e517de63ad677/resource/traversers/dfu_impl_update.cpp#L436 That error condition (`rc !=0`) occurs because a partial cancel successfully removes the allocations of the other resource vertices (especially …

Resource: support partial cancel of resources external to broker ranks

---

t/t1006-qmanager-multiqueue.t
t/t1024-alloc-check.t

Problem: In the near future, the job.exception output in flux-core will change, resulting in failures in tests that expect a specific format.
Update the job.exception parsing in t1006-qmanager-multiqueue.t and t1024-alloc-check.t to be more flexible to future output changes.
----
in preparation for change in https://github.com/flux-framework/flux-core/pull/6453

t: update job.exception output checks

---

qmanager/modules/qmanager.cpp

Problem: the raw RPC interfaces are changing to use a `size_t `instead of `int` for payload size.
Update scheduler usage.
flux-framework/flux-core#6467 must be merged before this will pass CI.

qmanager: track API changes in core

---

qmanager/modules/qmanager_callbacks.cpp

The `.free` RPC no longer receives a response, and `schedutil_free_respond()` is a noop. `jobmanager_free_cb` currently contains a call to schedutil_free_respond, which misleadingly suggests that not sending the response could be an error condition in flux-core.
This short PR remove the call and associated error handling from the qmanager free callback.

Qmanager: remove no-longer-supported schedutil_free_respond()

---

qmanager/modules/qmanager.cpp
qmanager/modules/qmanager_callbacks.cpp
resource/modules/resource_match.cpp
resource/readers/resource_reader_jgf.cpp
resource/readers/resource_reader_jgf.hpp
t/t1026-rv1-partial-release.t

This changes qmanager to invoke the `sched.hello` request with the flag that tells it to allow partial allocations through.  schedutil then diminishes _R_ in the hello responses by the `free` set (if present) before handing it to the hello callback in qmanager.   We were wondering if fluxion would perhaps just handle this.
flux-framework/flux-core#6445 must be merged before it can work with flux-core master, however, preliminary testing with that branch appears to show a problem.  The sharness test added here fails when I reload the scheduler with one node in housekeeping, and fluxion says:
```
Dec 17 00:52:30.860604 UTC sched-fluxion-resource.err[0]: parse_R: json_unpack
Dec 17 00:52:30.860614 UTC sched-fluxion-resource.err[0]: run_update: parsing R: Invalid argument
Dec 17 …
```

qmanager: send partial-ok with sched.hello

---

resource/modules/resource_match.cpp
resource/reapi/bindings/c++/reapi_cli_impl.hpp
resource/traversers/dfu.cpp
resource/utilities/command.cpp

Recent debugging revealed that the traverser error message wasn't getting cleared after some traversal operations, leading to spurious or error logging that can be unrelated to the error cause.
Wrap each traverser function call with `clear_err_message ()` to ensure error messages are correctly attributed to the cause.

Clear traverser before traversal operations in dfu

---

.github/workflows/main.yml
src/test/generate-matrix.py

Problem: the alpine-arm64 build is failing and stopping the generate-manifests step from running.
Disable the alpine build, to be brought back once the arm64 build can be fixed.
See #1326

ci: drop alpine

---

NEWS.md

NEWS.md: add release notes for v0.41.0

---

.github/workflows/main.yml
src/test/generate-matrix.py

This does a couple of things to enable new arm runners:
1. add the runner to the matrix generator so we can choose between x86 and arm
2. remove the emulator support since we should no longer need it
3. reintroduce alpine
At least on a temporary basis this changes the matrix to always run the arm builds for testing purposes.

add Arm runners and bring back alpine

---

doc/man5/flux-config-sched-fluxion-resource.rst
resource/modules/resource_match.cpp
resource/modules/resource_match_opts.cpp
resource/modules/resource_match_opts.hpp
resource/policies/base/test/CMakeLists.txt
resource/policies/base/test/matcher_policy_factory_test02.cpp
resource/policies/dfu_match_policy_factory.cpp
resource/policies/dfu_match_policy_factory.hpp
t/CMakeLists.txt
t/conf.d/09-invalid-policy/sched-fluxion-resource.toml
t/t3037-resource-custom-policy.t
t/t4000-match-params.t
t/t4010-match-conf.t

Problem: the current fluxion policy matching factory doesn't allow for customizable policies.
Add a custom option and refactor existing policies to behave similarly. Add unit testing for the string parsing convenience functions.
Update documentation for existing and new custom match policies.
Outstanding to-do:

policy: expose internals of resource module policy factory to allow custom policies

---

resource/evaluators/expr_eval_api.cpp
resource/evaluators/expr_eval_api.hpp
resource/evaluators/expr_eval_target.hpp
resource/evaluators/expr_eval_vtx_target.cpp
resource/evaluators/expr_eval_vtx_target.hpp
resource/evaluators/test/expr_eval_test01.cpp
resource/planner/c/planner_c_interface.cpp
resource/planner/c/planner_multi.h
resource/planner/c/planner_multi_c_interface.cpp
resource/traversers/dfu_impl.cpp
resource/traversers/dfu_impl.hpp
resource/traversers/dfu_impl_update.cpp
resource/utilities/command.cpp
resource/writers/match_writers.cpp
resource/writers/match_writers.hpp
t/data/resource/expected/find-format/jgf.expected.agfilter.json
t/data/resource/expected/find-format/jgf.expected.jobid.alloc.agfilter.json
t/data/resource/expected/find-format/jgf.expected.jobid.alloc.json
t/data/resource/expected/find-format/jgf.expected.jobid.rsv.json
t/data/resource/expected/find-format/jgf.expected.jobid.span.agfilter.json
t/data/resource/expected/find-format/jgf.expected.jobid.span.json
t/data/resource/expected/find-format/jgf.expected.jobid.tag.agfilter.json
t/data/resource/expected/find-format/jgf.expected.jobid.tag.json
t/t1015-find-format.t

Errors in partial cancel are causing inability to schedule resources in production. While evidence points to orphaned (i.e., not cleared) vertex data such as aggregate filters, it is difficult to investigate and debug without being able to inspect the state of the vertices.
The PR adds capability to print vertex-specific data by `jobid` and an `agfilter` boolean. The state can be printed based on whether the jobid is in the `allocations`, `reservations`, `job2span`, and `tags` maps.
This PR is WIP because I need to add support for all writers.

Find by jobid and output aggregate filter data

---

NEWS.md

Problem: there are no release notes for v0.42.0.
Add them.

NEWS.md: add release notes for v0.42.0

---

resource/modules/resource_match.cpp
src/cmd/flux-ion-resource.py
t/t4006-properties.t

Problem: there is a use-case for removing properties from vertices, but there is no functionality for doing that via rpc.
Add a remove-property RPC.
The use-case is that compute nodes attached to down rabbits will have a property placed on them, and jobs that need to use rabbits will require that the property _not_ be present on nodes allocated to the job. However, when a rabbit comes up, the property will need to be removed from the node on its rack. That last part requires this PR.

resource: remove property

---

NEWS.md

Problem: flux-coral2 depends on functionality in #1332 (see e.g. https://github.com/flux-framework/flux-coral2/pull/266 and https://github.com/flux-framework/flux-coral2/pull/265), and so a new flux-coral2 RPM will require that PR, but there isn't a release yet that includes it.

NEWS.md: add release notes for v0.42.1

---

NEWS.md

Problem: there are no release notes for v0.42.2.
Add them.
Also fix release date for 0.42.1.

NEWS.md: add release notes for v0.42.2

---

src/common/yggdrasil/rbtree.cpp

problem: yggdrasil will not compile with clang++ 19+ because it adds an
invalid template parameter to a pair of calls to `insert_leaf_base`.
I'm not sure how this ever worked.
solution: remove the template parameter
I ran into this trying to test the recent issues on my Tumbleweed VM, all tests pass with the change locally and they are the only pair of calls that have this.

yggdrasil: fix invalid template calls

---

resource/modules/resource_match.cpp

Problem: A lead in the sched-fluxion-resource module is reported when running t2317-resource-shrink.t with FLUX_TEST_VAlGRIND=t set.
The leak is from the line
ctx->m_r_alloc = json_deep_copy (R_alloc);
Other cached R representations in the module ctx object are saved with `json::value::take()`. Use this for `ctx->m_r_alloc` as well, which seems to fix the leak.
I have no idea if this is the right fix :shrug:

resource: fix leak in `status_request_cb()`

---

resource/modules/resource_match.cpp
t/data/resource/rv1exec/tiny_rv1exec.json
t/t4011-match-duration.t

I noticed some errors in handling of Rv1 in Fluxion while testing #1345. Most notably, Fluxion does not support an expiration of `0.` as specified in [RFC 20](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_20.html#expiration), either in the initial Rv1 object used to initialize the resource graph or as a result of `flux update JOBID duration=0`. Additionally, RFC 20 specifies both `starttime` and `expiration` are optional, but Fluxion requires both keys.
This PR makes the necessary simple changes to bring Fluxion into compliance. This came up when testing the launch of Fluxion scheduled subinstances under sched-simple, which uses an expiration of `0.` to indicate unlimited (sched-fluxion-resource aborted at this point) It also may also come up if the duration of a …

comply with RFC 20 when parsing Rv1 `starttime` and `expiration`

---

resource/evaluators/expr_eval_vtx_target.cpp
resource/utilities/command.cpp
src/cmd/flux-ion-resource.py
t/t3025-resource-find.t
t/t4006-properties.t

Problem: there is no way to find resources by name and by property.
Add `names=HOSTLIST` and `property=PROP` operators to the evaluators and document them in resource-query.
Example usage:
```
resource-query> find hostlist=tuolumne[1,1001-1019] and sched-now=free
------tuolumne1[1:x]
------tuolumne1001[1:x]
------tuolumne1002[1:x]
------tuolumne1003[1:x]
------tuolumne1004[1:x]
------tuolumne1005[1:x]
------tuolumne1006[1:x]
------tuolumne1007[1:x]
------tuolumne1008[1:x]
------tuolumne1009[1:x]
------tuolumne1010[1:x]
------tuolumne1011[1:x]
------tuolumne1012[1:x]
------tuolumne1013[1:x]
------tuolumne1014[1:x]
------tuolumne1015[1:x]
------tuolumne1016[1:x]
------tuolumne1017[1:x]
------tuolumne1018[1:x]
------tuolumne1019[1:x]
---cluster0[1:x]
INFO: =============================
INFO: …
```

evaluators: find by name and by property

---

NEWS.md

Problem: there are no release notes for v0.44.0.
Add them.

NEWS.md: add release notes for v0.44.0

---

.github/workflows/main.yml

Problem: the ubuntu-20.04 was removed on April 15th.
Update to ubuntu 24.

ci: update ubuntu version for spelling

---

resource/modules/resource_match.cpp
t/t4012-set-status.t

Problem: the receipt of a `mark` RPC does not trigger qmanager to reconsider jobs.
If a vertex is marked as UP, send a response to the `sched-fluxion-resource.notify` RPC, so qmanager can reconsider jobs.
Draft until tests are added.

resource: send notify response on `mark` RPC

---

NEWS.md

Problem: there are no release notes for v0.45.0.
Add them.
Waiting on #1362 .

NEWS.md: add release notes for v0.45.0

---

NEWS.md

Problem: there are no release notes for v0.46.0.
Add them.

NEWS.md: add release notes for v0.46.0

---

etc/rc1.d/01-sched-fluxion
etc/rc3.d/01-sched-fluxion
qmanager/modules/qmanager.cpp
resource/modules/CMakeLists.txt
resource/modules/feasibility.cpp
resource/modules/resource.cpp
resource/modules/resource_match.cpp
resource/modules/resource_match.hpp
resource/schema/data_std.cpp
resource/schema/data_std.hpp
src/cmd/flux-ion-resource.py
t/CMakeLists.txt
t/conf.d/01-default/sched-fluxion-feasibility.toml
t/data/resource/jobspecs/satisfiability/shrink2.yaml
t/data/resource/jobspecs/satisfiability/shrink3.yaml
t/data/resource/jobspecs/satisfiability/shrink4.yaml
t/sharness.d/sched-sharness.sh
t/t1020-qmanager-feasibility.t
t/t2317-resource-shrink.t
t/t4005-match-unsat.t
t/t4012-set-status.t
t/t4014-match-feasibility.t
t/t4015-notify-feasibility.t

Problem: Feasibility checking takes up a significant amount of sched-fluxion-resource's time that could be better spent on scheduling.
Solution: Move feasibility checking into a new module, sched-fluxion-feasibility, that can run on multiple ranks.

modules: Move feasibility/satisfiability checking into a new module

---

.github/workflows/main.yml
src/test/docker-manifest.py

This PR pulls a couple recent ci updates from flux-core:
- switch the `generate-manfest` step to use `src/test/docker-manifest.py` (I don't think there was a problem here, but this does automatically keep manifest generation in sync with `generate-matrix.py`)
- add the tmate action which is conditionally run when restarting builds with the "debug" box checked

ci: add debug tmate action and use `docker-manifest.py` in generate-manifest step

---

src/test/docker-manifest.py

Problem: The `src/test/docker-manifest.py` script inadvertently contained a reference to flux-core in it, causing the manifest generation to occur in the wrong repo.
Update the script to specify flux-sched, not flux-core.

ci: fix docker-manifest.py

---

scripts/install-deps.sh
t/issues/t1035-fluxion-reload.sh
t/issues/t1182-exclude-with-down-ranks.sh
t/t1010-sync-modules.t
t/t2317-resource-shrink.t
t/t3300-system-dontblock.t
t/t4000-match-params.t
t/t4014-match-feasibility.t
t/t5100-issues-test-driver.t

Problem: some tests rely on flux-core <= 0.77 broker module runtime error handling, where a module spuriously exiting with error is not fatal to the Flux instance.
flux-framework/flux-core#6969 added a check so that if a module exits with error on its own, the instance shuts down with an error so that this condition can be more easily detected.
Temporarily set the broker attribute `broker.module-nopanic=1` in failing fluxion tests to get the old behavior.  At some point,  perhaps after flux-core-0.78.0 is released, tests should be updated to expect the new behavior and this commit may be reverted.
p.s. unrelated: also added pop!OS to `install-deps.sh` in this PR since that's what I'm using for development.

testsuite: set broker.module-nopanic=1

---

etc/modprobe/modprobe.d/fluxion.toml

Problem: sched-fluxion-qmanager and sched-fluxion-feasibility need sched-fluxion-resource in order to be loaded, but this is not reflected in the fluxion modprobe config.
Add
```
needs = ["sched-fluxion-resource"]
```
to the config for sched-fluxion-qmanager and sched-fluxion-resource so that if sched-fluxion-qmanager is disabled, these modules are disabled as well.

etc: add missing "needs" to modprobe config
