- .travis.yml
- Makefile
- t/Makefile
This PR separates travis testing from the minor RDL enhancements of #19 (sorry, these should have been separate from the beginning)
This should make it easier to review and merge this PR, and other PRs can proceed separately (and will benefit from whatever tests are in flux-sched at the time of the PR)
> Support Travis CI testing in flux-sched

- sched/schedsrv.c
And fixed a bug along the way.
> Replace deprecated flux_sendmsg() in sched module

- sched/schedsrv.c
Inserted a minimum requirement of one node into the resource request
logic.
> sched: Fix Issue 52

- resrc/resrc.c
- resrc/resrc.h
- resrc/resrc_reqst.c
- resrc/resrc_tree.c
- resrc/resrc_tree.h
- resrc/test/tresrc.c
- sched/schedplugin1.c
- sched/schedsrv.c
- t/sharness.d/flux-sharness.sh
- t/sharness.sh
- t/t2000-fcfs.t
- t/t2001-fcfs-aware.t
- t/t2002-easy.t
As promised, the deserialization code.  The sched build fails however with the "jobs scheduled in correct order" problem.
> Resrc deserialize

- simulator/scheduler.c
Stop gap measure: ported new code from sched/schedsrv.c to
simulator/scheduler.c that leverages the job_status_cb to eliminate
watching for the lwj.next-id.  This allows us to merge PR 480 to the
flux-core.
> simulator: Eliminate use of lwj.next-id

- README.md
Addresses https://github.com/flux-framework/flux-sched/issues/97
> README: minor edits to track latest behavior

- sched/flux-waitjob.c
- sched/schedsrv.c
- simulator/scheduler.c
- simulator/sim_execsrv.c
- simulator/simsrv.c
- simulator/simulator.c
- simulator/submitsrv.c
Addresses https://github.com/flux-framework/flux-sched/issues/112
> flux-sched: eliminate deprecated flux-core functions

- .travis.yml
- Makefile.inc
- resrc/test/tresrc.c
- sched/flux-waitjob.c
- sched/schedsrv.c
- simulator/scheduler.c
- simulator/simulator.c
- simulator/submitsrv.c
- simulator/test/tsched_lib.c
This addresses a number of compile-time warnings that improve code reliability.  It also fixes the Makefile.inc to track the new flux-core library names.
> Address warnings

- t/sharness.d/flux-sharness.sh
This PR needs to go in after flux-framework/flux-core#543 is merged.
> test/flux-sharness.sh: update logging options

- sched/schedsrv.c
This allows sched to be loaded on the broker command line, without arguments (arguments are a bit of a problem for size > 1 as discussed in flux-framework/flux-core#584)
It replaces `kvs_get_string()` with `kvs_watch_once()` with initial value of NULL, so that the response from the KVS is delayed until the value is non-NULL, as may be the case if resource-hwloc has not completed its initialization on all ranks.
This also fixes a leak of the `kvs_get_string()` result on all but the last iteration.
> schedsrv: fix build_hwloc_rs2rank synchronization

- resrc/resrc_tree.c
- sched/schedsrv.c
This commits some memory leak fixes from @SteVwonder submitted a number of weeks ago.  The code has undergone so many mods since the common base that it was easier to just cherry pick the relevant changes that remained.
> Plug leaks

- Makefile.am
Includes the same files that flux-core does.
> Add missing files to top Makefile.am's EXTRA_DIST

- README.md
- configure.ac
- sched/Makefile.am
- sched/sched.c
- sched/sched_backfill.c
- sched/sched_fcfs.c
- sched/schedsrv.c
- sched/scheduler.h
- t/t0001-basic.t
- t/t1000-jsc.t
- t/t2000-fcfs.t
- t/t2001-fcfs-aware.t
- t/t2002-easy.t
This PR addresses the items listed in [Issue 125](https://github.com/flux-framework/flux-sched/issues/125).  @garlick, let me know if you see anything I missed w/r/t this issue.  The changes needed to address [Issue 140](https://github.com/flux-framework/flux-sched/issues/140), as well as the work to cull sched's installed products to just the essential libraries, can be in a separate PR.
> Sched install improvements

- sched/sched.c
- sched/scheduler.h
- t/Makefile.am
- t/t1004-module-load.t
Miscellaneous follow-up to the work done to address Issue #144.  Includes a plugin replacement test.
> Test for Dynamic Sched Plugin Loading

- simulator/scheduler.c
> Fix gcc 5.2.1 compilation issue in simulator

- simulator/submitsrv.c
Affected message:  "no more jobs to submit"
> simulator:  Change log message type from error to debug

- resrc/resrc.c
- resrc/resrc_tree.c
- resrc/resrc_tree.h
- resrc/test/tresrc.c
- sched/sched.c
This PR has some minor changes that are self-contained and made in the lead up to more major overhaul.  I figured I would get these in the review, comment, and merge queue while I keep working on the big enchilada.
> Minor improvements

- rdl/test/trdl.c
- sched/flux-waitjob.c
- simulator/sim_execsrv.c
- simulator/simsrv.c
- simulator/submitsrv.c
- src/common/libutil/Makefile.am
- src/common/libutil/log.c
- src/common/libutil/log.h
- src/common/libutil/oom.h
- src/common/libutil/shortjson.h
- src/common/libutil/xzmalloc.c
This is a periodic duty of keeping the few flux-core/src/common files
that flux-sched copied in sync with flux-core
> logging:  Bring over the latest flux-core logging changes

- rdl/Makefile.am
- resrc/Makefile.am
- resrc/resrc.c
- resrc/resrc_tree.c
- sched/Makefile.am
and fixed the warnings that showed up in resrc.c and resrc_tree.c
> Makefile.am:  Added $(AM_*FLAGS) to definitions where missing

- src/common/libutil/shortjson.h
commit 1bac19fb1767520c29ee5e7498f99479e8edb992
> shortjson:  Pull over latest updates to shortjson.h

- resrc/resrc.c
- resrc/resrc_flow.c
- resrc/resrc_flow.h
- resrc/resrc_reqst.c
- resrc/resrc_tree.c
- resrc/test/tresrc.c
- sched/flux-waitjob.c
- sched/rsreader.c
- sched/sched.c
- simulator/sim_execsrv.c
- simulator/simsrv.c
- simulator/simulator.c
- simulator/submitsrv.c
- src/common/libutil/shortjson.h
Update shortjson.h from flux-core, which removes the JSON typedef.
Update the rest of the code to use json_object * in place of JSON.
> Upate shortjson.h from flux-core, remove JSON

- simulator/submitsrv.c
Track API changes in flux-core.
Merge after flux-framework/flux-core#835
> simulator: update flux_rpc_get() usage

- .travis.yml
- sched/plugin.c
- t/t2002-easy.t
> plugins: add dlopen RTLD_DEEPBIND flag

- simulator/simulator.c
- t/t2002-easy.t
Also improves error checking and logging of the simulator's KVS operations
Pre-requisites: https://github.com/flux-framework/flux-core/pull/872 must be merged first
Fixes: #214
> sim: Fix easy-backfilling test case

- sched/sched.c
This addresses the issue of jobs that don't divide evenly between nodes, counting the cores per node from the resource tree.
> count cores per node when building JSC request

- NEWS.md
- resrc/resrc.c
- sched/sched.c
- sched/sched_backfill.c
Address all three items in [Issue 224](https://github.com/flux-framework/flux-sched/issues/224).  In addition, I made minor tweaks to the backfill behavior based on the reserve-depth value.
> Misc fixes

- simulator/simsrv.c
- simulator/submitsrv.c
Refactor to use jansson style rpc & event functions instead of json-c in
simulator.
> simulator: Refactor rpc usage

- simulator/simulator.c
Track changes in flux-core.
Fixes #252
> simulator: update KVS lookup functions

- sched/sched.c
> sched: Fix a leak

- NEWS.md
- README.md
This PR updates README.md and NEWS.md in preparation for v0.8.0 tag and release
Address 2 issues:
- Issue #545 (@andre-merzky: So if you can give me a feedback on the new README.md, this should be very useful);
- Issue #544 (@cmisale: once this gets in, we should be able to tag/release 0.8.0 so that you can use a tagged name for your Kube+Flux work);
> Update README.md and NEWS.md

- .mergify.yml
> mergify: add config from flux-core

- qmanager/modules/qmanager.cpp
- resource/jobinfo/jobinfo.hpp
- resource/modules/resource_match.cpp
- resource/readers/resource_reader_jgf.cpp
- resource/writers/match_writers.cpp
Per @garlick's request, this PR is split from PR #663.  
This contains minor fixes, improvements and refactoring.
> Misc. clean-up in preparation for state reconstruction 

- NEWS.md
Here's a starting point for some v0.9.0 release notes.  Other please feel free to force push to this PR!  I just wanted to get the ball rolling.
> NEWS.md: add release notes for v0.9.0

- README.md
- resource/utilities/README.md
This PR updates the package dependency matrix
of our main README file and also adds fixes
for other misc documentation issue.
Fix Issue #647, #686 and #598.
> doc: update pkg dependency matrix and misc. fixes

- t/t5000-valgrind.t
- t/valgrind/valgrind-workload.sh
- t/valgrind/valgrind.supp
- t/valgrind/workload.d/00-job
Just some small updates to get valgrind running again in the test suite.
> testsuite: enable valgrind testing

- etc/01-sched-fluxion-resource-start
- etc/02-sched-fluxion-qmanager-start
- t/sharness.d/sched-sharness.sh
- t/t1001-qmanager-basic.t
- t/t1002-qmanager-reload.t
- t/t1003-qmanager-policy.t
- t/t1004-qmanager-optimize.t
- t/t1005-qmanager-conf.t
- t/t1006-qmanager-multiqueue.t
- t/t1007-recovery-full.t
- t/t1008-recovery-none.t
- t/t1009-recovery-multiqueue.t
- t/t1010-sync-modules.t
- t/t1011-dynstate-change.t
- t/t1012-find-status.t
- t/t1013-exclusion.t
- t/t1013-qmanager-priority.t
- t/t1014-annotation.t
- t/t2001-tree-real.t
- t/t4000-match-params.t
- t/t4004-match-hwloc.t
- t/t4009-match-update.t
- t/t6002-graph-hwloc.t
These are sched changes needed in conjunction with flux-framework/flux-core#3177
> avoid unloading sched-simple

- NEWS.md
Feel free to push any and all edits to this branch.
> NEWS.md: add NEWS entry for v0.12.0

- NEWS.md
> NEWS.md: prep for 0.15.0 tag

- resource/modules/resource_match.cpp
- resource/schema/infra_data.cpp
- resource/utilities/resource-query.cpp
- src/test/docker/fedora33/Dockerfile
- src/test/generate-matrix.py
> CI: Add fedora33 for gcc10

- .github/workflows/main.yml
This copies the fix for tarball generation and upload from flux-framework/flux-core#3638.
Fixes #832
> github: fixes for auto-release deployment

- resource/modules/resource_match.cpp
Update usage of `flux_msg_get_route_first()` (renamed to `flux_msg_route_first()`) per API changes in flux-core PR #3746 (https://github.com/flux-framework/flux-core/pull/3746)
Must wait until https://github.com/flux-framework/flux-core/pull/3746 is merged.
> resource: update for libflux API change

- resource/utilities/README.md
@dongahn found this typo while going over the README with me.
> docs: fix code sample in resource README

- NEWS.md
This is an initial draft of release notes for v0.23.0.
Once these are approved and merged, I can tag a release and build RPMs.
> NEWS.md: add release notes for v0.23.0

- t/t1007-recovery-full.t
- t/t1008-recovery-none.t
- t/t1014-annotation.t
Fix some minor test problems.
This is based on #971 (last two commits are the ones that belong to this PR).
> minor test cleanup

- t/t1006-qmanager-multiqueue.t
Problem: t1006-qmanager-multiqueue.t exploits the fact that jobs may be submitted with incorrect queue specifications when the frobnicator is disabled, but this method won't work once the job manager becomes queue-aware.
Submit test jobs with qmanager unloaded, then reconfigure queues and reload qmanager to trigger the job exceptions.
(This test was failing in CI for flux-framework/flux-core#4627)
> testsuite: fix coverage method for queue exception

- resource/modules/resource_match.cpp
- t/t1022-property-constraints.t
This possibly could have been accomplished by changing how exceptions are propagated and handled in the resource module, but I wasn't sure how to do that, so here we use a `flux_error_t` to propagate the exception error string back to where it can be returned in an error response to the feasibility RPC.
Fixes #1002
> resource: improve error messages for jobspec parse errors

- NEWS.md
Add release notes for flux-sched v0.26.0.
Feel free to directly push updates and corrections.
> NEWS.md: add release notes for flux-sched v0.26.0

- .github/workflows/main.yml
- t/Makefile.am
- t/t1022-property-constraints.t
when folks are asked to provide PA input, say "Al knows how to spell!"
> actions: update typo checker version

- NEWS.md
This is a set of release notes for v0.29.0. As usual feel free to push directly here for any additions or fixups.
> NEWS.md: add release notes for v0.29.0

- resource/modules/resource_match.cpp
- t/t4011-match-duration.t
This PR adds support for the `expiration` key in the [RFC 28](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_28.html#additional-acquire-responses) "Additional acquire responses".
Presence of this key indicates that the expiration of the instance resource set has been updated.
This is built on top of #1104 since this PR adds to the sharness tests which is modified there.
> resource: support resource expiration updates

- NEWS.md
Release notes for flux-sched v0.30.0.
> NEWS.md: add release notes for flux-sched v0.30.0

- NEWS.md
Problem: there are no release notes for version 0.33.1.
Add them.
> NEWS.md: add release notes for v0.33.1

- resource/schema/resource_graph.hpp
This is stacked on top of #1203, and is a performance enhancement.  For large numbers of constraint jobs especially out_edges was becoming a bottleneck.  Using this test script I saw a drop from ~7 minutes 30 seconds to 90 seconds on my laptop and a very significant shift in the weights in the perf output.
<details>
<summary> Test script </summary>
```bash
#!/usr/bin/env bash
#
test_description='
'
. `dirname $0`/sharness.sh
export TEST_UNDER_FLUX_QUORUM=1
export TEST_UNDER_FLUX_START_MODE=leader
rpc() {
flux python -c \
"import flux, json; print(flux.Flux().rpc(\"$1\").get_str())"
}
test_under_flux 16384 system
test_expect_success 'unload sched-simple' '
flux module remove -f sched-simple
'
test_expect_success 'update configuration' '
flux config load <<-'EOF'
[[resource.config]]
hosts = …
```
> avoid copying of std::map in out_edges

- NEWS.md
- t/valgrind/valgrind-workload.sh
Thought I'd get a `NEWS.md` update ready for the upcoming sched release.
Feel free to push directly here with updates or modifications.
> Add release notes for v0.35.0

- resource/schema/resource_graph.hpp
problem: I accidentally left this code in when removing the filtered graph
solution: remove it
> graph: remove unused subsystem selector class

- .github/workflows/main.yml
- src/test/docker/el9/Dockerfile
- src/test/docker/fedora40/Dockerfile
- src/test/docker/noble-golang/Dockerfile
- src/test/docker/noble/Dockerfile
- src/test/generate-matrix.py
problem: we're using old images and out of date WRT core
solution: pull in current versions and update build matrix
> actions/docker: add ~el9~,f40,noble drop focal

- NEWS.md
Problem: there are no release notes for v0.37.0.
Add them.
> NEWS.md: add release notes for v0.37.0

- t/sharness.d/flux-sharness.sh
- t/sharness.d/heredoc.sh
- t/t1001-qmanager-basic.t
- t/t1002-qmanager-reload.t
- t/t1003-qmanager-policy.t
- t/t1004-qmanager-optimize.t
- t/t1005-qmanager-conf.t
- t/t1011-dynstate-change.t
- t/t1012-find-status.t
- t/t1013-qmanager-priority.t
- t/t1014-annotation.t
- t/t1015-find-format.t
- t/t1017-rv1-bootstrap.t
- t/t1018-rv1-bootstrap2.t
- t/t1021-qmanager-nodex.t
- t/t1022-property-constraints.t
- t/t3025-resource-find.t
- t/t3027-resource-RV.t
- t/t3034-resource-pconstraints.t
- t/t4010-match-conf.t
- t/t5100-issues-test-driver.t
- t/t6002-graph-hwloc.t
- t/t8001-util-ion-R.t
problem: I've been using heaptrack a lot, and other tools that need to be wrapped around flux itself.  This is difficult without something to integrate with test_funder_flux
solution: add some env vars to do a heaptrack recording or add a generic wrapper
> flux-sharness: sync with flux-core

- .mergify.yml
problem: mergify is changing their option structure
solution: update to match new requirements and core
> mergify: update to new mergify.yml requirements

- resource/readers/resource_reader_jgf.cpp
- src/python/fluxion/jsongraph/objects/graph.py
- src/python/fluxion/resourcegraph/V1.py
- t/python/t10001-resourcegraph.py
PR #1293 is getting too much (locally anyway, I haven't pushed my changes recently), I need to start smaller.
> JGF: default edge subsystem

- NEWS.md
> NEWS.md: add release notes for v0.40.0

- resource/modules/resource_match.cpp
- t/t4006-properties.t
Problem: the `set_property`, `get_property`, and `remove_property` RPCs log an error message instead of returning one to the sender. That is a bad pattern.
Don't log the message, instead return it in the RPC response.
See also https://github.com/flux-framework/flux-coral2/issues/294.
> resource: make property RPCs return error message

- NEWS.md
Waiting on:
@milroy, @trws let me know if there are any others.
> NEWS.md: add release notes for v0.43.0

- NEWS.md
Problem: there are no release notes for v0.47.0.
Add them.
> NEWS.md: add release notes for v0.47.0
